

#include	"dTypes.h"
#include	"atvImageResource.h"
#include	"ImageOutput/atv_IMG_ID_Blue_english.c"
#include	"ImageOutput/atv_IMG_ID_Clock_english.c"
#include	"ImageOutput/atv_IMG_ID_Green_english.c"
#include	"ImageOutput/atv_IMG_ID_Mute_Icon_english.c"
#include	"ImageOutput/atv_IMG_ID_Red_english.c"
#include	"ImageOutput/atv_IMG_ID_Scroll_Bg_english.c"
#include	"ImageOutput/atv_IMG_ID_Scroll_Vernier_english.c"
#include	"ImageOutput/atv_IMG_ID_Yellow_english.c"
#include	"ImageOutput/atv_IMG_ID_adjust_icon_big_english.c"
#include	"ImageOutput/atv_IMG_ID_adjust_icon_small_english.c"
#include	"ImageOutput/atv_IMG_ID_adjust_icon_small_forbidden_english.c"
#include	"ImageOutput/atv_IMG_ID_background_english.c"
#include	"ImageOutput/atv_IMG_ID_box_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_button_background_left_english.c"
#include	"ImageOutput/atv_IMG_ID_button_background_middle_english.c"
#include	"ImageOutput/atv_IMG_ID_button_background_right_english.c"
#include	"ImageOutput/atv_IMG_ID_button_left_english.c"
#include	"ImageOutput/atv_IMG_ID_button_left_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_button_right_english.c"
#include	"ImageOutput/atv_IMG_ID_button_right_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_disk_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_disk_normal_english.c"
/* 电子书目前暂时不开放*/
//#include	"ImageOutput/atv_IMG_ID_ebk_icon_focus_small_english.c"
//#include	"ImageOutput/atv_IMG_ID_ebk_icon_normal_small_english.c"
//#include	"ImageOutput/atv_IMG_ID_ebook_icon_focus_english.c"
//#include	"ImageOutput/atv_IMG_ID_ebook_icon_normal_english.c"
//#include	"ImageOutput/atv_IMG_ID_ebook_title_cn_english.c"
//#include	"ImageOutput/atv_IMG_ID_ebook_title_en_english.c"
#include	"ImageOutput/atv_IMG_ID_focus_background_english.c"
#include	"ImageOutput/atv_IMG_ID_function_icon_big_english.c"
#include	"ImageOutput/atv_IMG_ID_function_icon_small_english.c"
#include	"ImageOutput/atv_IMG_ID_hint_background_english.c"
#include	"ImageOutput/atv_IMG_ID_hint_button_english.c"
#include	"ImageOutput/atv_IMG_ID_hint_direction_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_file_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_file_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_file_up_level_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_file_up_level_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_movie_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_movie_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_music_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_music_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_music_play_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_picture_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_picture_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_setting_english.c"
#include	"ImageOutput/atv_IMG_ID_icon_setting_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_image_icon_big_english.c"
#include	"ImageOutput/atv_IMG_ID_image_icon_small_english.c"
#include	"ImageOutput/atv_IMG_ID_left_arrow_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_left_arrow_no_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_loading_english.c"
#include	"ImageOutput/atv_IMG_ID_media_disk_english.c"
#include	"ImageOutput/atv_IMG_ID_media_pause_english.c"
#include	"ImageOutput/atv_IMG_ID_media_play_english.c"
#include	"ImageOutput/atv_IMG_ID_media_stop_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_backgroud_blue_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_left_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_left_disable_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_left_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_normal_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_normal_disable_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_normal_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_right_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_right_disable_english.c"
#include	"ImageOutput/atv_IMG_ID_menu_button_right_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_ld_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_lm_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_lu_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_md_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_middle_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_mu_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_rd_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_rm_english.c"
#include	"ImageOutput/atv_IMG_ID_movie_background_ru_english.c"
#include	"ImageOutput/atv_IMG_ID_music_list_loop_english.c"
#include	"ImageOutput/atv_IMG_ID_music_list_play_english.c"
#include	"ImageOutput/atv_IMG_ID_music_one_loop_english.c"
#include	"ImageOutput/atv_IMG_ID_music_pitch_on_english.c"
#include	"ImageOutput/atv_IMG_ID_music_pitch_on_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_music_random_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_file_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_file_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_focus_left_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_focus_middle_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_focus_right_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_left_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_middle_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_pane_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_pane_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_right_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_up_level_english.c"
#include	"ImageOutput/atv_IMG_ID_music_select_up_level_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_num_0_english.c"
#include	"ImageOutput/atv_IMG_ID_num_1_english.c"
#include	"ImageOutput/atv_IMG_ID_num_2_english.c"
#include	"ImageOutput/atv_IMG_ID_num_3_english.c"
#include	"ImageOutput/atv_IMG_ID_num_4_english.c"
#include	"ImageOutput/atv_IMG_ID_num_5_english.c"
#include	"ImageOutput/atv_IMG_ID_num_6_english.c"
#include	"ImageOutput/atv_IMG_ID_num_7_english.c"
#include	"ImageOutput/atv_IMG_ID_num_8_english.c"
#include	"ImageOutput/atv_IMG_ID_num_9_english.c"
#include	"ImageOutput/atv_IMG_ID_picture_menu_button_english.c"
#include	"ImageOutput/atv_IMG_ID_picture_menu_last_english.c"
#include	"ImageOutput/atv_IMG_ID_picture_menu_next_english.c"
#include	"ImageOutput/atv_IMG_ID_picture_menu_rotate_left_english.c"
#include	"ImageOutput/atv_IMG_ID_picture_menu_rotate_right_english.c"
#include	"ImageOutput/atv_IMG_ID_pos_english.c"
/* 图像位置菜单暂不显示，因此这些图暂不用*/
//#include	"ImageOutput/atv_IMG_ID_position_down_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_down_focus_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_left_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_left_focus_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_right_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_right_focus_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_up_english.c"
//#include	"ImageOutput/atv_IMG_ID_position_up_focus_english.c"
//#include	"ImageOutput/atv_IMG_ID_program_info_backplane_narrow_L_english.c"
//#include	"ImageOutput/atv_IMG_ID_program_info_backplane_narrow_M_english.c"
//#include	"ImageOutput/atv_IMG_ID_program_info_backplane_narrow_R_english.c"
//#include	"ImageOutput/atv_IMG_ID_program_info_backplane_wide_L_english.c"
//#include	"ImageOutput/atv_IMG_ID_program_info_backplane_wide_M_english.c"
//#include	"ImageOutput/atv_IMG_ID_program_info_backplane_wide_R_english.c"
#include	"ImageOutput/atv_IMG_ID_program_info_direction_down_english.c"
#include	"ImageOutput/atv_IMG_ID_program_info_direction_left_english.c"
#include	"ImageOutput/atv_IMG_ID_program_info_direction_right_english.c"
#include	"ImageOutput/atv_IMG_ID_program_info_direction_up_english.c"
#include	"ImageOutput/atv_IMG_ID_progress_front_english.c"
#include	"ImageOutput/atv_IMG_ID_pvr_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_pvr_normal_english.c"
#include	"ImageOutput/atv_IMG_ID_pvr_read_pos_english.c"
#include	"ImageOutput/atv_IMG_ID_pvr_title_ch_english.c"
#include	"ImageOutput/atv_IMG_ID_pvr_title_en_english.c"
#include	"ImageOutput/atv_IMG_ID_red_info_icon_english.c"
#include	"ImageOutput/atv_IMG_ID_right_arrow_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_right_arrow_no_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_left_enable_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_left_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_left_no_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_normal_enable_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_normal_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_normal_no_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_right_enable_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_right_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scroll_right_no_focus_english.c"
#include	"ImageOutput/atv_IMG_ID_scrool_one_english.c"
#include	"ImageOutput/atv_IMG_ID_scrool_two_english.c"
#include	"ImageOutput/atv_IMG_ID_search_left_english.c"
#include	"ImageOutput/atv_IMG_ID_search_leftx_english.c"
#include	"ImageOutput/atv_IMG_ID_search_right_english.c"
#include	"ImageOutput/atv_IMG_ID_search_rightx_english.c"
#include	"ImageOutput/atv_IMG_ID_signal_progress_english.c"
#include	"ImageOutput/atv_IMG_ID_signal_progress_background_english.c"
#include	"ImageOutput/atv_IMG_ID_time_icon_big_english.c"
#include	"ImageOutput/atv_IMG_ID_time_icon_small_english.c"
#include	"ImageOutput/atv_IMG_ID_time_icon_small_forbidden_english.c"
#include	"ImageOutput/atv_IMG_ID_title_backgroud_english.c"
#include	"ImageOutput/atv_IMG_ID_title_movie_english.c"
#include	"ImageOutput/atv_IMG_ID_title_movie_en_english.c"
#include	"ImageOutput/atv_IMG_ID_title_music_english.c"
#include	"ImageOutput/atv_IMG_ID_title_music_en_english.c"
#include	"ImageOutput/atv_IMG_ID_title_picture_english.c"
#include	"ImageOutput/atv_IMG_ID_title_picture_en_english.c"
#include	"ImageOutput/atv_IMG_ID_title_setting_english.c"
#include	"ImageOutput/atv_IMG_ID_title_setting_en_english.c"
#include	"ImageOutput/atv_IMG_ID_title_usb_english.c"
#include	"ImageOutput/atv_IMG_ID_title_usb_en_english.c"
#include	"ImageOutput/atv_IMG_ID_tuning_icon_big_english.c"
#include	"ImageOutput/atv_IMG_ID_tuning_icon_small_english.c"
#include	"ImageOutput/atv_IMG_ID_tuning_icon_small_forbidden_english.c"
#include	"ImageOutput/atv_IMG_ID_txt_icon_focus_small_english.c"
#include	"ImageOutput/atv_IMG_ID_txt_icon_normal_small_english.c"
#include	"ImageOutput/atv_IMG_ID_usb_small_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_bg_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_icon_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_icon_big_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_icon_small_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_left_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_middle_english.c"
#include	"ImageOutput/atv_IMG_ID_voice_right_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_ld_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_lm_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_lu_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_md_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_middle_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_mu_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_rd_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_rm_english.c"
#include	"ImageOutput/atv_IMG_ID_white_background_ru_english.c"

#include	"ImageOutput/atv_IMG_ID_WIFI_CONNECT_english.c"
#include	"ImageOutput/atv_IMG_ID_WIFI_LOCK_english.c"
#include	"ImageOutput/atv_IMG_ID_WIFI_NOTICE_english.c"
#include	"ImageOutput/atv_IMG_ID_info_english.c"

#include	"ImageOutput/atv_IMG_ID_main_zhilian_HDMI_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_bg_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_1_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_2_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_3_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_4_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_5_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_6_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_7_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_focse_8_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_souce_tv_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_source_av_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_source_dtv_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_source_media_english.c"
#include	"ImageOutput/atv_IMG_ID_main_zhilian_source_ypbpr_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_dlna_flag_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_mira_flag_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_phone_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_tv_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_tvweb_flag_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_wifi_pic_english.c"

#include	"ImageOutput/atv_IMG_ID_zhilian_main_dlna_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_iptv_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_media_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_mira_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_setting_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_source_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_zhilian_main_tsnet_pic_english.c"
#include	"ImageOutput/atv_IMG_ID_mini_airplay_english.c"
#include	"ImageOutput/atv_IMG_ID_music_icon_english.c"

#include	"ImageOutput/atv_IMG_ID_WIFI_1_english.c"
#include	"ImageOutput/atv_IMG_ID_WIFI_2_english.c"
#include	"ImageOutput/atv_IMG_ID_WIFI_3_english.c"
#include	"ImageOutput/atv_IMG_ID_WIFI_4_english.c"
#include	"ImageOutput/atv_IMG_ID_WIFI_bg_english.c"

typedef struct
{
	unsigned char *imgName;
	int imgSize;
}IMGITEM;




static PREFIXCONST IMGITEM POSTCONST _img_array__english[]=
{
	{atv_IMG_ID_Yellow_english, 1154},
	{atv_IMG_ID_adjust_icon_big_english, 7168},
	{atv_IMG_ID_adjust_icon_small_english, 1158},
	{atv_IMG_ID_adjust_icon_small_forbidden_english, 1067},
	{atv_IMG_ID_Blue_english, 1151},
	{atv_IMG_ID_box_focus_english, 237},
	{atv_IMG_ID_button_background_left_english, 180},
	{atv_IMG_ID_button_background_middle_english, 137},
	{atv_IMG_ID_button_background_right_english, 173},
	{atv_IMG_ID_button_left_english, 559},
	{atv_IMG_ID_button_left_focus_english, 717},
	{atv_IMG_ID_button_right_english, 514},
	{atv_IMG_ID_button_right_focus_english, 677},
	{atv_IMG_ID_Clock_english, 2070},
	{atv_IMG_ID_disk_focus_english, 1714},
	{atv_IMG_ID_focus_background_english, 3133},
	{atv_IMG_ID_function_icon_big_english, 9318},
	{atv_IMG_ID_function_icon_small_english, 2028},
	{atv_IMG_ID_Green_english, 1156},
	{atv_IMG_ID_hint_background_english, 1154},
	{atv_IMG_ID_hint_button_english, 336},
	{atv_IMG_ID_hint_direction_english, 3222},
	{atv_IMG_ID_image_icon_big_english, 8113},
	{atv_IMG_ID_image_icon_small_english, 1691},
	{atv_IMG_ID_left_arrow_focus_english, 831},
	{atv_IMG_ID_left_arrow_no_focus_english, 660},
	{atv_IMG_ID_menu_backgroud_blue_english, 3649},
	{atv_IMG_ID_menu_button_left_english, 190},
	{atv_IMG_ID_menu_button_left_disable_english, 282},
	{atv_IMG_ID_menu_button_left_focus_english, 225},
	{atv_IMG_ID_menu_button_normal_english, 128},
	{atv_IMG_ID_menu_button_normal_disable_english, 210},
	{atv_IMG_ID_menu_button_normal_focus_english, 166},
	{atv_IMG_ID_menu_button_right_english, 178},
	{atv_IMG_ID_menu_button_right_disable_english, 284},
	{atv_IMG_ID_menu_button_right_focus_english, 218},
	{atv_IMG_ID_Mute_Icon_english, 3514},
	{atv_IMG_ID_num_0_english, 2191},
	{atv_IMG_ID_num_1_english, 610},
	{atv_IMG_ID_num_2_english, 2116},
	{atv_IMG_ID_num_3_english, 2454},
	{atv_IMG_ID_num_4_english, 1332},
	{atv_IMG_ID_num_5_english, 2133},
	{atv_IMG_ID_num_6_english, 2628},
	{atv_IMG_ID_num_7_english, 1342},
	{atv_IMG_ID_num_8_english, 2664},
	{atv_IMG_ID_num_9_english, 2604},
	/* 图像位置菜单暂不显示，因此这些图暂不用*/
	{NULL, 0}, //{atv_IMG_ID_position_down_english, 576},
	{NULL, 0}, //{atv_IMG_ID_position_down_focus_english, 571},
	{NULL, 0}, //{atv_IMG_ID_position_left_english, 681},
	{NULL, 0}, //{atv_IMG_ID_position_left_focus_english, 675},
	{NULL, 0}, //{atv_IMG_ID_position_right_english, 677},
	{NULL, 0}, //{atv_IMG_ID_position_right_focus_english, 702},
	{NULL, 0}, //{atv_IMG_ID_position_up_english, 502},
	{NULL, 0}, //{atv_IMG_ID_position_up_focus_english, 510},
	{atv_IMG_ID_program_info_direction_down_english, 630},
	{atv_IMG_ID_program_info_direction_left_english, 665},
	{atv_IMG_ID_program_info_direction_right_english, 661},
	{atv_IMG_ID_program_info_direction_up_english, 657},
	{atv_IMG_ID_progress_front_english, 120},
	{atv_IMG_ID_pvr_read_pos_english, 501},
	{atv_IMG_ID_Red_english, 1147},
	{atv_IMG_ID_red_info_icon_english, 420},
	{atv_IMG_ID_right_arrow_focus_english, 782},
	{atv_IMG_ID_right_arrow_no_focus_english, 655},
	{atv_IMG_ID_Scroll_Bg_english, 199},
	{atv_IMG_ID_scroll_left_focus_english, 398},
	{atv_IMG_ID_scroll_left_no_focus_english, 332},
	{atv_IMG_ID_scroll_normal_focus_english, 166},
	{atv_IMG_ID_scroll_normal_no_focus_english, 128},
	{atv_IMG_ID_scroll_right_focus_english, 404},
	{atv_IMG_ID_scroll_right_no_focus_english, 329},
	{atv_IMG_ID_scroll_left_enable_english, 366},
	{atv_IMG_ID_scroll_normal_enable_english, 140},
	{atv_IMG_ID_scroll_right_enable_english, 364},
	{atv_IMG_ID_Scroll_Vernier_english, 222},
	{atv_IMG_ID_scrool_one_english, 115},
	{atv_IMG_ID_scrool_two_english, 108},
	{atv_IMG_ID_search_left_english, 193},
	{atv_IMG_ID_search_leftx_english, 198},
	{atv_IMG_ID_search_right_english, 182},
	{atv_IMG_ID_search_rightx_english, 201},
	{atv_IMG_ID_signal_progress_english, 189},
	{atv_IMG_ID_signal_progress_background_english, 189},
	{atv_IMG_ID_time_icon_big_english, 8490},
	{atv_IMG_ID_time_icon_small_english, 1916},
	{atv_IMG_ID_time_icon_small_forbidden_english, 1557},
	{atv_IMG_ID_title_backgroud_english, 162},
	{atv_IMG_ID_tuning_icon_big_english, 6696},
	{atv_IMG_ID_tuning_icon_small_english, 1257},
	{atv_IMG_ID_tuning_icon_small_forbidden_english, 1000},
	{atv_IMG_ID_voice_bg_english, 831},
	{atv_IMG_ID_voice_icon_english, 1515},
	{atv_IMG_ID_voice_icon_big_english, 7924},
	{atv_IMG_ID_voice_icon_small_english, 1667},
	{atv_IMG_ID_voice_left_english, 218},
	{atv_IMG_ID_voice_middle_english, 133},
	{atv_IMG_ID_voice_right_english, 196},
	{atv_IMG_ID_white_background_ld_english, 153},
	{atv_IMG_ID_white_background_lm_english, 144},
	{atv_IMG_ID_white_background_lu_english, 147},
	{atv_IMG_ID_white_background_md_english, 145},
	{atv_IMG_ID_white_background_middle_english, 136},
	{atv_IMG_ID_white_background_mu_english, 144},
	{atv_IMG_ID_white_background_rd_english, 149},
	{atv_IMG_ID_white_background_rm_english, 144},
	{atv_IMG_ID_white_background_ru_english, 150},

        {atv_IMG_ID_zhilian_main_dlna_flag_english, sizeof(atv_IMG_ID_zhilian_main_dlna_flag_english)},
	{atv_IMG_ID_zhilian_main_mira_flag_english, sizeof(atv_IMG_ID_zhilian_main_mira_flag_english)},
	{atv_IMG_ID_zhilian_main_tvweb_flag_english, sizeof(atv_IMG_ID_zhilian_main_tvweb_flag_english)},
	{atv_IMG_ID_zhilian_main_phone_pic_english, sizeof(atv_IMG_ID_zhilian_main_phone_pic_english)},
	{atv_IMG_ID_zhilian_main_tv_pic_english, sizeof(atv_IMG_ID_zhilian_main_tv_pic_english)},
	{atv_IMG_ID_zhilian_main_wifi_pic_english, sizeof(atv_IMG_ID_zhilian_main_wifi_pic_english)},
    
	{atv_IMG_ID_WIFI_CONNECT_english, sizeof(atv_IMG_ID_WIFI_CONNECT_english)},
	{atv_IMG_ID_WIFI_LOCK_english, sizeof(atv_IMG_ID_WIFI_LOCK_english)},
	{atv_IMG_ID_WIFI_NOTICE_english, sizeof(atv_IMG_ID_WIFI_NOTICE_english)},
	{atv_IMG_ID_info_english, sizeof(atv_IMG_ID_info_english)},

	{atv_IMG_ID_main_zhilian_bg_english, sizeof(atv_IMG_ID_main_zhilian_bg_english)},
	{atv_IMG_ID_main_zhilian_focse_1_english, sizeof(atv_IMG_ID_main_zhilian_focse_1_english)},
	{atv_IMG_ID_main_zhilian_focse_2_english, sizeof(atv_IMG_ID_main_zhilian_focse_2_english)},
	{atv_IMG_ID_main_zhilian_focse_3_english, sizeof(atv_IMG_ID_main_zhilian_focse_3_english)},
	{atv_IMG_ID_main_zhilian_focse_4_english, sizeof(atv_IMG_ID_main_zhilian_focse_4_english)},
	{atv_IMG_ID_main_zhilian_focse_5_english, sizeof(atv_IMG_ID_main_zhilian_focse_5_english)},
	{atv_IMG_ID_main_zhilian_focse_6_english, sizeof(atv_IMG_ID_main_zhilian_focse_6_english)},
	{atv_IMG_ID_main_zhilian_focse_7_english, sizeof(atv_IMG_ID_main_zhilian_focse_7_english)},
	{atv_IMG_ID_main_zhilian_focse_8_english, sizeof(atv_IMG_ID_main_zhilian_focse_8_english)},
	{atv_IMG_ID_main_zhilian_HDMI_english, sizeof(atv_IMG_ID_main_zhilian_HDMI_english)},
	{atv_IMG_ID_main_zhilian_pic_english, sizeof(atv_IMG_ID_main_zhilian_pic_english)},
	{atv_IMG_ID_main_zhilian_souce_tv_english, sizeof(atv_IMG_ID_main_zhilian_souce_tv_english)},
	{atv_IMG_ID_main_zhilian_source_av_english, sizeof(atv_IMG_ID_main_zhilian_source_av_english)},
	{atv_IMG_ID_main_zhilian_source_dtv_english, sizeof(atv_IMG_ID_main_zhilian_source_dtv_english)},
	{atv_IMG_ID_main_zhilian_source_media_english, sizeof(atv_IMG_ID_main_zhilian_source_media_english)},
	{atv_IMG_ID_main_zhilian_source_ypbpr_english, sizeof(atv_IMG_ID_main_zhilian_source_ypbpr_english)},
        {atv_IMG_ID_zhilian_main_dlna_pic_english, sizeof(atv_IMG_ID_zhilian_main_dlna_pic_english)},
	{atv_IMG_ID_zhilian_main_iptv_pic_english, sizeof(atv_IMG_ID_zhilian_main_iptv_pic_english)},
	{atv_IMG_ID_zhilian_main_media_pic_english, sizeof(atv_IMG_ID_zhilian_main_media_pic_english)},
	{atv_IMG_ID_zhilian_main_mira_pic_english, sizeof(atv_IMG_ID_zhilian_main_mira_pic_english)},
	{atv_IMG_ID_zhilian_main_setting_pic_english, sizeof(atv_IMG_ID_zhilian_main_setting_pic_english)},
	{atv_IMG_ID_zhilian_main_source_pic_english, sizeof(atv_IMG_ID_zhilian_main_source_pic_english)},
	{atv_IMG_ID_zhilian_main_tsnet_pic_english, sizeof(atv_IMG_ID_zhilian_main_tsnet_pic_english)},
	{atv_IMG_ID_mini_airplay_english, sizeof(atv_IMG_ID_mini_airplay_english)},
	{atv_IMG_ID_music_icon_english, sizeof(atv_IMG_ID_music_icon_english)},
	{atv_IMG_ID_WIFI_1_english, sizeof(atv_IMG_ID_WIFI_1_english)},
	{atv_IMG_ID_WIFI_2_english, sizeof(atv_IMG_ID_WIFI_2_english)},
	{atv_IMG_ID_WIFI_3_english, sizeof(atv_IMG_ID_WIFI_3_english)},
	{atv_IMG_ID_WIFI_4_english, sizeof(atv_IMG_ID_WIFI_4_english)},
	{atv_IMG_ID_WIFI_bg_english, sizeof(atv_IMG_ID_WIFI_bg_english)},
	{atv_IMG_ID_background_english, 51134},
	{atv_IMG_ID_disk_normal_english, 4470},
	/* 电子书目前暂时不开放*/
	{NULL, 0}, //{atv_IMG_ID_ebk_icon_focus_small_english, 966},
	{NULL, 0}, //{atv_IMG_ID_ebk_icon_normal_small_english, 539},
	{NULL, 0}, //{atv_IMG_ID_ebook_icon_focus_english, 1978},
	{NULL, 0}, //{atv_IMG_ID_ebook_icon_normal_english, 758},
	{NULL, 0}, //{atv_IMG_ID_ebook_title_cn_english, 3873},
	{NULL, 0}, //{atv_IMG_ID_ebook_title_en_english, 3816},
	{atv_IMG_ID_icon_file_english, 2286},
	{atv_IMG_ID_icon_file_focus_english, 1070},
	{atv_IMG_ID_icon_file_up_level_english, 4118},
	{atv_IMG_ID_icon_file_up_level_focus_english, 1551},
	{atv_IMG_ID_icon_movie_english, 4941},
	{atv_IMG_ID_icon_movie_focus_english, 1947},
	{atv_IMG_ID_icon_music_english, 3164},
	{atv_IMG_ID_icon_music_focus_english, 1172},
	{atv_IMG_ID_icon_music_play_english, 953},
	{atv_IMG_ID_icon_picture_english, 3593},
	{atv_IMG_ID_icon_picture_focus_english, 1571},
	{atv_IMG_ID_icon_setting_english, 5703},
	{atv_IMG_ID_icon_setting_focus_english, 2255},
	{atv_IMG_ID_loading_english, 10549},
	{atv_IMG_ID_media_disk_english, 1008},
	{atv_IMG_ID_media_pause_english, 504},
	{atv_IMG_ID_media_play_english, 932},
	{atv_IMG_ID_media_stop_english, 470},
	{atv_IMG_ID_movie_background_ld_english, 417},
	{atv_IMG_ID_movie_background_lm_english, 187},
	{atv_IMG_ID_movie_background_lu_english, 285},
	{atv_IMG_ID_movie_background_md_english, 217},
	{atv_IMG_ID_movie_background_middle_english, 143},
	{atv_IMG_ID_movie_background_mu_english, 154},
	{atv_IMG_ID_movie_background_rd_english, 442},
	{atv_IMG_ID_movie_background_rm_english, 189},
	{atv_IMG_ID_movie_background_ru_english, 344},
	{atv_IMG_ID_music_list_loop_english, 4582},
	{atv_IMG_ID_music_list_play_english, 4037},
	{atv_IMG_ID_music_one_loop_english, 4631},
	{atv_IMG_ID_music_pitch_on_english, 1041},
	{atv_IMG_ID_music_pitch_on_focus_english, 637},
	{atv_IMG_ID_music_random_english, 4702},
	{atv_IMG_ID_music_select_file_english, 714},
	{atv_IMG_ID_music_select_file_focus_english, 402},
	{atv_IMG_ID_music_select_focus_left_english, 417},
	{atv_IMG_ID_music_select_focus_middle_english, 131},
	{atv_IMG_ID_music_select_focus_right_english, 428},
	{atv_IMG_ID_music_select_left_english, 415},
	{atv_IMG_ID_music_select_middle_english, 133},
	{atv_IMG_ID_music_select_pane_english, 557},
	{atv_IMG_ID_music_select_pane_focus_english, 337},
	{atv_IMG_ID_music_select_right_english, 428},
	{atv_IMG_ID_music_select_up_level_english, 853},
	{atv_IMG_ID_music_select_up_level_focus_english, 470},
	{atv_IMG_ID_picture_menu_button_english, 805},
	{atv_IMG_ID_picture_menu_last_english, 1012},
	{atv_IMG_ID_picture_menu_next_english, 1027},
	{atv_IMG_ID_picture_menu_rotate_left_english, 1528},
	{atv_IMG_ID_picture_menu_rotate_right_english, 1507},
	{atv_IMG_ID_pos_english, 162},
	{atv_IMG_ID_pvr_focus_english, 2158},
	{atv_IMG_ID_pvr_normal_english, 794},
	{atv_IMG_ID_pvr_title_ch_english, 5206},
	{atv_IMG_ID_pvr_title_en_english, 2568},
	{atv_IMG_ID_title_movie_english, 4170},
	{atv_IMG_ID_title_movie_en_english, 4991},
	{atv_IMG_ID_title_music_english, 3502},
	{atv_IMG_ID_title_music_en_english, 4860},
	{atv_IMG_ID_title_picture_english, 3353},
	{atv_IMG_ID_title_picture_en_english, 4865},
	{atv_IMG_ID_title_setting_english, 3977},
	{atv_IMG_ID_title_setting_en_english, 5974},
	{atv_IMG_ID_title_usb_english, 7423},
	{atv_IMG_ID_title_usb_en_english, 3660},
	{atv_IMG_ID_txt_icon_focus_small_english, 919},
	{atv_IMG_ID_txt_icon_normal_small_english, 525},
	{atv_IMG_ID_usb_small_english, 1309},	
};

static PREFIXCONST IMGITEM POSTCONST _img_array__chinese[]=
{
	{atv_IMG_ID_Yellow_english, 1154},
	{atv_IMG_ID_adjust_icon_big_english, 7168},
	{atv_IMG_ID_adjust_icon_small_english, 1158},
	{atv_IMG_ID_adjust_icon_small_forbidden_english, 1067},
	{atv_IMG_ID_Blue_english, 1151},
	{atv_IMG_ID_box_focus_english, 237},
	{atv_IMG_ID_button_background_left_english, 180},
	{atv_IMG_ID_button_background_middle_english, 137},
	{atv_IMG_ID_button_background_right_english, 173},
	{atv_IMG_ID_button_left_english, 559},
	{atv_IMG_ID_button_left_focus_english, 717},
	{atv_IMG_ID_button_right_english, 514},
	{atv_IMG_ID_button_right_focus_english, 677},
	{atv_IMG_ID_Clock_english, 2070},
	{atv_IMG_ID_disk_focus_english, 1714},
	{atv_IMG_ID_focus_background_english, 3133},
	{atv_IMG_ID_function_icon_big_english, 9318},
	{atv_IMG_ID_function_icon_small_english, 2028},
	{atv_IMG_ID_Green_english, 1156},
	{atv_IMG_ID_hint_background_english, 1154},
	{atv_IMG_ID_hint_button_english, 336},
	{atv_IMG_ID_hint_direction_english, 3222},
	{atv_IMG_ID_image_icon_big_english, 8113},
	{atv_IMG_ID_image_icon_small_english, 1691},
	{atv_IMG_ID_left_arrow_focus_english, 831},
	{atv_IMG_ID_left_arrow_no_focus_english, 660},
	{atv_IMG_ID_menu_backgroud_blue_english, 3649},
	{atv_IMG_ID_menu_button_left_english, 190},
	{atv_IMG_ID_menu_button_left_disable_english, 282},
	{atv_IMG_ID_menu_button_left_focus_english, 225},
	{atv_IMG_ID_menu_button_normal_english, 128},
	{atv_IMG_ID_menu_button_normal_disable_english, 210},
	{atv_IMG_ID_menu_button_normal_focus_english, 166},
	{atv_IMG_ID_menu_button_right_english, 178},
	{atv_IMG_ID_menu_button_right_disable_english, 284},
	{atv_IMG_ID_menu_button_right_focus_english, 218},
	{atv_IMG_ID_Mute_Icon_english, 3514},
	{atv_IMG_ID_num_0_english, 2191},
	{atv_IMG_ID_num_1_english, 610},
	{atv_IMG_ID_num_2_english, 2116},
	{atv_IMG_ID_num_3_english, 2454},
	{atv_IMG_ID_num_4_english, 1332},
	{atv_IMG_ID_num_5_english, 2133},
	{atv_IMG_ID_num_6_english, 2628},
	{atv_IMG_ID_num_7_english, 1342},
	{atv_IMG_ID_num_8_english, 2664},
	{atv_IMG_ID_num_9_english, 2604},
	/* 图像位置菜单暂不显示，因此这些图暂不用*/
	{NULL, 0}, //{atv_IMG_ID_position_down_english, 576},
	{NULL, 0}, //{atv_IMG_ID_position_down_focus_english, 571},
	{NULL, 0}, //{atv_IMG_ID_position_left_english, 681},
	{NULL, 0}, //{atv_IMG_ID_position_left_focus_english, 675},
	{NULL, 0}, //{atv_IMG_ID_position_right_english, 677},
	{NULL, 0}, //{atv_IMG_ID_position_right_focus_english, 702},
	{NULL, 0}, //{atv_IMG_ID_position_up_english, 502},
	{NULL, 0}, //{atv_IMG_ID_position_up_focus_english, 510},
	{atv_IMG_ID_program_info_direction_down_english, 630},
	{atv_IMG_ID_program_info_direction_left_english, 665},
	{atv_IMG_ID_program_info_direction_right_english, 661},
	{atv_IMG_ID_program_info_direction_up_english, 657},
	{atv_IMG_ID_progress_front_english, 120},
	{atv_IMG_ID_pvr_read_pos_english, 501},
	{atv_IMG_ID_Red_english, 1147},
	{atv_IMG_ID_red_info_icon_english, 420},
	{atv_IMG_ID_right_arrow_focus_english, 782},
	{atv_IMG_ID_right_arrow_no_focus_english, 655},
	{atv_IMG_ID_Scroll_Bg_english, 199},
	{atv_IMG_ID_scroll_left_focus_english, 398},
	{atv_IMG_ID_scroll_left_no_focus_english, 332},
	{atv_IMG_ID_scroll_normal_focus_english, 166},
	{atv_IMG_ID_scroll_normal_no_focus_english, 128},
	{atv_IMG_ID_scroll_right_focus_english, 404},
	{atv_IMG_ID_scroll_right_no_focus_english, 329},
	{atv_IMG_ID_scroll_left_enable_english, 366},
	{atv_IMG_ID_scroll_normal_enable_english, 140},
	{atv_IMG_ID_scroll_right_enable_english, 364},
	{atv_IMG_ID_Scroll_Vernier_english, 222},
	{atv_IMG_ID_scrool_one_english, 115},
	{atv_IMG_ID_scrool_two_english, 108},
	{atv_IMG_ID_search_left_english, 193},
	{atv_IMG_ID_search_leftx_english, 198},
	{atv_IMG_ID_search_right_english, 182},
	{atv_IMG_ID_search_rightx_english, 201},
	{atv_IMG_ID_signal_progress_english, 189},
	{atv_IMG_ID_signal_progress_background_english, 189},
	{atv_IMG_ID_time_icon_big_english, 8490},
	{atv_IMG_ID_time_icon_small_english, 1916},
	{atv_IMG_ID_time_icon_small_forbidden_english, 1557},
	{atv_IMG_ID_title_backgroud_english, 162},
	{atv_IMG_ID_tuning_icon_big_english, 6696},
	{atv_IMG_ID_tuning_icon_small_english, 1257},
	{atv_IMG_ID_tuning_icon_small_forbidden_english, 1000},
	{atv_IMG_ID_voice_bg_english, 831},
	{atv_IMG_ID_voice_icon_english, 1515},
	{atv_IMG_ID_voice_icon_big_english, 7924},
	{atv_IMG_ID_voice_icon_small_english, 1667},
	{atv_IMG_ID_voice_left_english, 218},
	{atv_IMG_ID_voice_middle_english, 133},
	{atv_IMG_ID_voice_right_english, 196},
	{atv_IMG_ID_white_background_ld_english, 153},
	{atv_IMG_ID_white_background_lm_english, 144},
	{atv_IMG_ID_white_background_lu_english, 147},
	{atv_IMG_ID_white_background_md_english, 145},
	{atv_IMG_ID_white_background_middle_english, 136},
	{atv_IMG_ID_white_background_mu_english, 144},
	{atv_IMG_ID_white_background_rd_english, 149},
	{atv_IMG_ID_white_background_rm_english, 144},
	{atv_IMG_ID_white_background_ru_english, 150},

        {atv_IMG_ID_zhilian_main_dlna_flag_english, sizeof(atv_IMG_ID_zhilian_main_dlna_flag_english)},
	{atv_IMG_ID_zhilian_main_mira_flag_english, sizeof(atv_IMG_ID_zhilian_main_mira_flag_english)},
	{atv_IMG_ID_zhilian_main_tvweb_flag_english, sizeof(atv_IMG_ID_zhilian_main_tvweb_flag_english)},
	{atv_IMG_ID_zhilian_main_phone_pic_english, sizeof(atv_IMG_ID_zhilian_main_phone_pic_english)},
	{atv_IMG_ID_zhilian_main_tv_pic_english, sizeof(atv_IMG_ID_zhilian_main_tv_pic_english)},
	{atv_IMG_ID_zhilian_main_wifi_pic_english, sizeof(atv_IMG_ID_zhilian_main_wifi_pic_english)},
    
	{atv_IMG_ID_WIFI_CONNECT_english, sizeof(atv_IMG_ID_WIFI_CONNECT_english)},
	{atv_IMG_ID_WIFI_LOCK_english, sizeof(atv_IMG_ID_WIFI_LOCK_english)},
	{atv_IMG_ID_WIFI_NOTICE_english, sizeof(atv_IMG_ID_WIFI_NOTICE_english)},
	{atv_IMG_ID_info_english, sizeof(atv_IMG_ID_info_english)},

	{atv_IMG_ID_main_zhilian_bg_english, sizeof(atv_IMG_ID_main_zhilian_bg_english)},
	{atv_IMG_ID_main_zhilian_focse_1_english, sizeof(atv_IMG_ID_main_zhilian_focse_1_english)},
	{atv_IMG_ID_main_zhilian_focse_2_english, sizeof(atv_IMG_ID_main_zhilian_focse_2_english)},
	{atv_IMG_ID_main_zhilian_focse_3_english, sizeof(atv_IMG_ID_main_zhilian_focse_3_english)},
	{atv_IMG_ID_main_zhilian_focse_4_english, sizeof(atv_IMG_ID_main_zhilian_focse_4_english)},
	{atv_IMG_ID_main_zhilian_focse_5_english, sizeof(atv_IMG_ID_main_zhilian_focse_5_english)},
	{atv_IMG_ID_main_zhilian_focse_6_english, sizeof(atv_IMG_ID_main_zhilian_focse_6_english)},
	{atv_IMG_ID_main_zhilian_focse_7_english, sizeof(atv_IMG_ID_main_zhilian_focse_7_english)},
	{atv_IMG_ID_main_zhilian_focse_8_english, sizeof(atv_IMG_ID_main_zhilian_focse_8_english)},
	{atv_IMG_ID_main_zhilian_HDMI_english, sizeof(atv_IMG_ID_main_zhilian_HDMI_english)},
	{atv_IMG_ID_main_zhilian_pic_english, sizeof(atv_IMG_ID_main_zhilian_pic_english)},
	{atv_IMG_ID_main_zhilian_souce_tv_english, sizeof(atv_IMG_ID_main_zhilian_souce_tv_english)},
	{atv_IMG_ID_main_zhilian_source_av_english, sizeof(atv_IMG_ID_main_zhilian_source_av_english)},
	{atv_IMG_ID_main_zhilian_source_dtv_english, sizeof(atv_IMG_ID_main_zhilian_source_dtv_english)},
	{atv_IMG_ID_main_zhilian_source_media_english, sizeof(atv_IMG_ID_main_zhilian_source_media_english)},
	{atv_IMG_ID_main_zhilian_source_ypbpr_english, sizeof(atv_IMG_ID_main_zhilian_source_ypbpr_english)},
        {atv_IMG_ID_zhilian_main_dlna_pic_english, sizeof(atv_IMG_ID_zhilian_main_dlna_pic_english)},
	{atv_IMG_ID_zhilian_main_iptv_pic_english, sizeof(atv_IMG_ID_zhilian_main_iptv_pic_english)},
	{atv_IMG_ID_zhilian_main_media_pic_english, sizeof(atv_IMG_ID_zhilian_main_media_pic_english)},
	{atv_IMG_ID_zhilian_main_mira_pic_english, sizeof(atv_IMG_ID_zhilian_main_mira_pic_english)},
	{atv_IMG_ID_zhilian_main_setting_pic_english, sizeof(atv_IMG_ID_zhilian_main_setting_pic_english)},
	{atv_IMG_ID_zhilian_main_source_pic_english, sizeof(atv_IMG_ID_zhilian_main_source_pic_english)},
	{atv_IMG_ID_zhilian_main_tsnet_pic_english, sizeof(atv_IMG_ID_zhilian_main_tsnet_pic_english)},
	{atv_IMG_ID_mini_airplay_english, sizeof(atv_IMG_ID_mini_airplay_english)},	
        {atv_IMG_ID_music_icon_english, sizeof(atv_IMG_ID_music_icon_english)},
        {atv_IMG_ID_WIFI_1_english, sizeof(atv_IMG_ID_WIFI_1_english)},
	{atv_IMG_ID_WIFI_2_english, sizeof(atv_IMG_ID_WIFI_2_english)},
	{atv_IMG_ID_WIFI_3_english, sizeof(atv_IMG_ID_WIFI_3_english)},
	{atv_IMG_ID_WIFI_4_english, sizeof(atv_IMG_ID_WIFI_4_english)},
	{atv_IMG_ID_WIFI_bg_english, sizeof(atv_IMG_ID_WIFI_bg_english)},
	{atv_IMG_ID_background_english, 51134},
	{atv_IMG_ID_disk_normal_english, 4470},
	/* 电子书目前暂时不开放*/
	{NULL, 0}, //{atv_IMG_ID_ebk_icon_focus_small_english, 966},
	{NULL, 0}, //{atv_IMG_ID_ebk_icon_normal_small_english, 539},
	{NULL, 0}, //{atv_IMG_ID_ebook_icon_focus_english, 1978},
	{NULL, 0}, //{atv_IMG_ID_ebook_icon_normal_english, 758},
	{NULL, 0}, //{atv_IMG_ID_ebook_title_cn_english, 3873},
	{NULL, 0}, //{atv_IMG_ID_ebook_title_en_english, 3816},
	{atv_IMG_ID_icon_file_english, 2286},
	{atv_IMG_ID_icon_file_focus_english, 1070},
	{atv_IMG_ID_icon_file_up_level_english, 4118},
	{atv_IMG_ID_icon_file_up_level_focus_english, 1551},
	{atv_IMG_ID_icon_movie_english, 4941},
	{atv_IMG_ID_icon_movie_focus_english, 1947},
	{atv_IMG_ID_icon_music_english, 3164},
	{atv_IMG_ID_icon_music_focus_english, 1172},
	{atv_IMG_ID_icon_music_play_english, 953},
	{atv_IMG_ID_icon_picture_english, 3593},
	{atv_IMG_ID_icon_picture_focus_english, 1571},
	{atv_IMG_ID_icon_setting_english, 5703},
	{atv_IMG_ID_icon_setting_focus_english, 2255},
	{atv_IMG_ID_loading_english, 10549},
	{atv_IMG_ID_media_disk_english, 1008},
	{atv_IMG_ID_media_pause_english, 504},
	{atv_IMG_ID_media_play_english, 932},
	{atv_IMG_ID_media_stop_english, 470},
	{atv_IMG_ID_movie_background_ld_english, 417},
	{atv_IMG_ID_movie_background_lm_english, 187},
	{atv_IMG_ID_movie_background_lu_english, 285},
	{atv_IMG_ID_movie_background_md_english, 217},
	{atv_IMG_ID_movie_background_middle_english, 143},
	{atv_IMG_ID_movie_background_mu_english, 154},
	{atv_IMG_ID_movie_background_rd_english, 442},
	{atv_IMG_ID_movie_background_rm_english, 189},
	{atv_IMG_ID_movie_background_ru_english, 344},
	{atv_IMG_ID_music_list_loop_english, 4582},
	{atv_IMG_ID_music_list_play_english, 4037},
	{atv_IMG_ID_music_one_loop_english, 4631},
	{atv_IMG_ID_music_pitch_on_english, 1041},
	{atv_IMG_ID_music_pitch_on_focus_english, 637},
	{atv_IMG_ID_music_random_english, 4702},
	{atv_IMG_ID_music_select_file_english, 714},
	{atv_IMG_ID_music_select_file_focus_english, 402},
	{atv_IMG_ID_music_select_focus_left_english, 417},
	{atv_IMG_ID_music_select_focus_middle_english, 131},
	{atv_IMG_ID_music_select_focus_right_english, 428},
	{atv_IMG_ID_music_select_left_english, 415},
	{atv_IMG_ID_music_select_middle_english, 133},
	{atv_IMG_ID_music_select_pane_english, 557},
	{atv_IMG_ID_music_select_pane_focus_english, 337},
	{atv_IMG_ID_music_select_right_english, 428},
	{atv_IMG_ID_music_select_up_level_english, 853},
	{atv_IMG_ID_music_select_up_level_focus_english, 470},
	{atv_IMG_ID_picture_menu_button_english, 805},
	{atv_IMG_ID_picture_menu_last_english, 1012},
	{atv_IMG_ID_picture_menu_next_english, 1027},
	{atv_IMG_ID_picture_menu_rotate_left_english, 1528},
	{atv_IMG_ID_picture_menu_rotate_right_english, 1507},
	{atv_IMG_ID_pos_english, 162},
	{atv_IMG_ID_pvr_focus_english, 2158},
	{atv_IMG_ID_pvr_normal_english, 794},
	{atv_IMG_ID_pvr_title_ch_english, 5206},
	{atv_IMG_ID_pvr_title_en_english, 2568},
	{atv_IMG_ID_title_movie_english, 4170},
	{atv_IMG_ID_title_movie_en_english, 4991},
	{atv_IMG_ID_title_music_english, 3502},
	{atv_IMG_ID_title_music_en_english, 4860},
	{atv_IMG_ID_title_picture_english, 3353},
	{atv_IMG_ID_title_picture_en_english, 4865},
	{atv_IMG_ID_title_setting_english, 3977},
	{atv_IMG_ID_title_setting_en_english, 5974},
	{atv_IMG_ID_title_usb_english, 7423},
	{atv_IMG_ID_title_usb_en_english, 3660},
	{atv_IMG_ID_txt_icon_focus_small_english, 919},
	{atv_IMG_ID_txt_icon_normal_small_english, 525},
	{atv_IMG_ID_usb_small_english, 1309},	
};

static PREFIXCONST IMGITEM POSTCONST * _img_array_entries[]=
{
	_img_array__english,
	_img_array__chinese,
};
PREFIXCONST unsigned char *POSTCONST atv_LoadImageData(int ids, int lanid, int *size)
{
	if(ids>=atv_IMG_ID_ENUM_MAX||ids<atv_IMG_ID_START )
	{
		return NULL;
	}
	ids-=atv_IMG_ID_START;
	if(size)
	{
		*size=_img_array_entries[lanid][ids].imgSize;
	}
	return _img_array_entries[lanid][ids].imgName;
}
