#include "dFrame.h"
#include "tlanresource_tv.h"


static PREFIXCONST char POSTCONST tv_IDS_NULL_0[]="";
static PREFIXCONST char POSTCONST tv_IDS_NULL_1[]="";

static PREFIXCONST char POSTCONST tv_IDS_TV_0[]="Tv";
static PREFIXCONST char POSTCONST tv_IDS_TV_1[]="电视";

static PREFIXCONST char POSTCONST tv_IDS_VIDEO_0[]="Video";
static PREFIXCONST char POSTCONST tv_IDS_VIDEO_1[]="视频";

static PREFIXCONST char POSTCONST tv_IDS_MUSIC_0[]="Music";
static PREFIXCONST char POSTCONST tv_IDS_MUSIC_1[]="音乐";

static PREFIXCONST char POSTCONST tv_IDS_PHOTO_0[]="Photo";
static PREFIXCONST char POSTCONST tv_IDS_PHOTO_1[]="相片";

static PREFIXCONST char POSTCONST tv_IDS_RADIO_0[]="Radio";
static PREFIXCONST char POSTCONST tv_IDS_RADIO_1[]="收音机";

static PREFIXCONST char POSTCONST tv_IDS_TOOL_0[]="Tool";
static PREFIXCONST char POSTCONST tv_IDS_TOOL_1[]="工具";

static PREFIXCONST char POSTCONST tv_IDS_SUNDAY_0[]="Sunday";
static PREFIXCONST char POSTCONST tv_IDS_SUNDAY_1[]="星期日";

static PREFIXCONST char POSTCONST tv_IDS_MONDAY_0[]="Monday";
static PREFIXCONST char POSTCONST tv_IDS_MONDAY_1[]="星期一";

static PREFIXCONST char POSTCONST tv_IDS_TUESDAY_0[]="Tuesday";
static PREFIXCONST char POSTCONST tv_IDS_TUESDAY_1[]="星期二";

static PREFIXCONST char POSTCONST tv_IDS_WENDSDAY_0[]="Wendsday";
static PREFIXCONST char POSTCONST tv_IDS_WENDSDAY_1[]="星期三";

static PREFIXCONST char POSTCONST tv_IDS_THURSDAY_0[]="Thursday";
static PREFIXCONST char POSTCONST tv_IDS_THURSDAY_1[]="星期四";

static PREFIXCONST char POSTCONST tv_IDS_FRIDAY_0[]="Friday";
static PREFIXCONST char POSTCONST tv_IDS_FRIDAY_1[]="星期五";

static PREFIXCONST char POSTCONST tv_IDS_SATURDAY_0[]="Saturday";
static PREFIXCONST char POSTCONST tv_IDS_SATURDAY_1[]="星期六";

static PREFIXCONST char POSTCONST tv_IDS_SEARCH_CHANNEL_0[]="Search Channel";
static PREFIXCONST char POSTCONST tv_IDS_SEARCH_CHANNEL_1[]="搜台";

static PREFIXCONST char POSTCONST tv_IDS_LIST_CHANNEL_0[]="List_Channel";
static PREFIXCONST char POSTCONST tv_IDS_LIST_CHANNEL_1[]="节目列表";

static PREFIXCONST char POSTCONST tv_IDS_SHOW_SCALE_0[]="Show_Scale";
static PREFIXCONST char POSTCONST tv_IDS_SHOW_SCALE_1[]="显示比例";

static PREFIXCONST char POSTCONST tv_IDS_BRIGHT_0[]="Bright";
static PREFIXCONST char POSTCONST tv_IDS_BRIGHT_1[]="亮度";

static PREFIXCONST char POSTCONST tv_IDS_TRACK_0[]="Track";
static PREFIXCONST char POSTCONST tv_IDS_TRACK_1[]="声道";

static PREFIXCONST char POSTCONST tv_IDS_CANCEL_0[]="Cancel";
static PREFIXCONST char POSTCONST tv_IDS_CANCEL_1[]="取消";

static PREFIXCONST char POSTCONST tv_IDS_SCAN_CHANNEL_0[]="Scan Channel";
static PREFIXCONST char POSTCONST tv_IDS_SCAN_CHANNEL_1[]="正在搜台";

static PREFIXCONST char POSTCONST tv_IDS_DURING_TIME_0[]="During_Time";
static PREFIXCONST char POSTCONST tv_IDS_DURING_TIME_1[]="时长";

static PREFIXCONST char POSTCONST tv_IDS_SIZE_0[]="Size";
static PREFIXCONST char POSTCONST tv_IDS_SIZE_1[]="大小";

static PREFIXCONST char POSTCONST tv_IDS_CHOOSE_TIME_0[]="Choose_Time";
static PREFIXCONST char POSTCONST tv_IDS_CHOOSE_TIME_1[]="选时";

static PREFIXCONST char POSTCONST tv_IDS_PLAY_CONTROL_0[]="Play_Control";
static PREFIXCONST char POSTCONST tv_IDS_PLAY_CONTROL_1[]="播放控制";

static PREFIXCONST char POSTCONST tv_IDS_ORDER_PLAY_0[]="Order_Play";
static PREFIXCONST char POSTCONST tv_IDS_ORDER_PLAY_1[]="顺序";

static PREFIXCONST char POSTCONST tv_IDS_CIRCLE_PLAY_0[]="Circle_Play";
static PREFIXCONST char POSTCONST tv_IDS_CIRCLE_PLAY_1[]="循环";

static PREFIXCONST char POSTCONST tv_IDS_ALBUM_0[]="Album:";
static PREFIXCONST char POSTCONST tv_IDS_ALBUM_1[]="专辑:";

static PREFIXCONST char POSTCONST tv_IDS_SIGNER_0[]="Singer:";
static PREFIXCONST char POSTCONST tv_IDS_SIGNER_1[]="歌手:";

static PREFIXCONST char POSTCONST tv_IDS_E_BOOK_0[]="E-Book";
static PREFIXCONST char POSTCONST tv_IDS_E_BOOK_1[]="电子书";

static PREFIXCONST char POSTCONST tv_IDS_MOVIDE_MANAGE_0[]="Movie_Manage";
static PREFIXCONST char POSTCONST tv_IDS_MOVIDE_MANAGE_1[]="电影管理";

static PREFIXCONST char POSTCONST tv_IDS_FILE_MANAGE_0[]="File Manage";
static PREFIXCONST char POSTCONST tv_IDS_FILE_MANAGE_1[]="文件管理";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_0[]="Calendar";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_1[]="日历";

static PREFIXCONST char POSTCONST tv_IDS_SET_UP_0[]="Set Up";
static PREFIXCONST char POSTCONST tv_IDS_SET_UP_1[]="设置";

static PREFIXCONST char POSTCONST tv_IDS_LANGUAGE_CHOOSE_0[]="Choose Language";
static PREFIXCONST char POSTCONST tv_IDS_LANGUAGE_CHOOSE_1[]="语言选择";

static PREFIXCONST char POSTCONST tv_IDS_PRODUCT_INFO_0[]="Product_Info";
static PREFIXCONST char POSTCONST tv_IDS_PRODUCT_INFO_1[]="产品信息";

static PREFIXCONST char POSTCONST tv_IDS_DEFAULT_SET_0[]="Set to factory default ?";
static PREFIXCONST char POSTCONST tv_IDS_DEFAULT_SET_1[]="是否要恢复出厂设置？";

static PREFIXCONST char POSTCONST tv_IDS_OK_0[]="OK";
static PREFIXCONST char POSTCONST tv_IDS_OK_1[]="确定";

static PREFIXCONST char POSTCONST tv_IDS_OUTPUT_0[]="OutPut";
static PREFIXCONST char POSTCONST tv_IDS_OUTPUT_1[]="输出";

static PREFIXCONST char POSTCONST tv_IDS_INPUT_RANGE_0[]="Please Input Range";
static PREFIXCONST char POSTCONST tv_IDS_INPUT_RANGE_1[]="输入波段";

static PREFIXCONST char POSTCONST tv_IDS_LEFT_0[]="Left";
static PREFIXCONST char POSTCONST tv_IDS_LEFT_1[]="左声道";

static PREFIXCONST char POSTCONST tv_IDS_RIGHT_0[]="Right";
static PREFIXCONST char POSTCONST tv_IDS_RIGHT_1[]="右声道";

static PREFIXCONST char POSTCONST tv_IDS_STEREO_0[]="Stereo";
static PREFIXCONST char POSTCONST tv_IDS_STEREO_1[]="立体声";

static PREFIXCONST char POSTCONST tv_IDS_4TO3_0[]="4:3";
static PREFIXCONST char POSTCONST tv_IDS_4TO3_1[]="4:3";

static PREFIXCONST char POSTCONST tv_IDS_16T09_0[]="16:9";
static PREFIXCONST char POSTCONST tv_IDS_16T09_1[]="16:9";

static PREFIXCONST char POSTCONST tv_IDS_TV_CHANNEL_LIST_0[]="Tv Channel List";
static PREFIXCONST char POSTCONST tv_IDS_TV_CHANNEL_LIST_1[]="电视节目列表";

static PREFIXCONST char POSTCONST tv_IDS_RADIO_CHANNEL_LIST_0[]="Radio Channel List";
static PREFIXCONST char POSTCONST tv_IDS_RADIO_CHANNEL_LIST_1[]="广播节目列表";

static PREFIXCONST char POSTCONST tv_IDS_VOLUME_0[]="Volume";
static PREFIXCONST char POSTCONST tv_IDS_VOLUME_1[]="音量";

static PREFIXCONST char POSTCONST tv_IDS_AUTO_SCAN_0[]="Auto Scan";
static PREFIXCONST char POSTCONST tv_IDS_AUTO_SCAN_1[]="自动搜索";

static PREFIXCONST char POSTCONST tv_IDS_FILE_FORMAT_0[]="File Format";
static PREFIXCONST char POSTCONST tv_IDS_FILE_FORMAT_1[]="图片格式";

static PREFIXCONST char POSTCONST tv_IDS_FILE_SIZE_0[]="File Size";
static PREFIXCONST char POSTCONST tv_IDS_FILE_SIZE_1[]="图片尺寸";

static PREFIXCONST char POSTCONST tv_IDS_SLIDE_PLAY_0[]="Slide Play";
static PREFIXCONST char POSTCONST tv_IDS_SLIDE_PLAY_1[]="幻灯片播放";

static PREFIXCONST char POSTCONST tv_IDS_REVOLVE_0[]="Revolve";
static PREFIXCONST char POSTCONST tv_IDS_REVOLVE_1[]="旋转";

static PREFIXCONST char POSTCONST tv_IDS_MUSIC_ON_0[]="Music On";
static PREFIXCONST char POSTCONST tv_IDS_MUSIC_ON_1[]="音乐开";

static PREFIXCONST char POSTCONST tv_IDS_MUSIC_OFF_0[]="Music off";
static PREFIXCONST char POSTCONST tv_IDS_MUSIC_OFF_1[]="音乐关";

static PREFIXCONST char POSTCONST tv_IDS_SLIDE_SPEED_0[]="Slide Speed";
static PREFIXCONST char POSTCONST tv_IDS_SLIDE_SPEED_1[]="幻灯片速度";

static PREFIXCONST char POSTCONST tv_IDS_SLIDE_PAUSE_0[]="Slide Pause";
static PREFIXCONST char POSTCONST tv_IDS_SLIDE_PAUSE_1[]="幻灯片暂停";

static PREFIXCONST char POSTCONST tv_IDS_TWO_SECOND_0[]="Two Second";
static PREFIXCONST char POSTCONST tv_IDS_TWO_SECOND_1[]="2秒钟";

static PREFIXCONST char POSTCONST tv_IDS_FOUR_SECOND_0[]="Four Second";
static PREFIXCONST char POSTCONST tv_IDS_FOUR_SECOND_1[]="4秒钟";

static PREFIXCONST char POSTCONST tv_IDS_SIX_SECOND_0[]="Six Second";
static PREFIXCONST char POSTCONST tv_IDS_SIX_SECOND_1[]="6秒钟";

static PREFIXCONST char POSTCONST tv_IDS_EIGHT_SECOND_0[]="Eight Second";
static PREFIXCONST char POSTCONST tv_IDS_EIGHT_SECOND_1[]="8秒钟";

static PREFIXCONST char POSTCONST tv_IDS_TEN_SECOND_0[]="Ten Second";
static PREFIXCONST char POSTCONST tv_IDS_TEN_SECOND_1[]="10秒钟";

static PREFIXCONST char POSTCONST tv_IDS_TWELVE_SECOND_0[]="Twelve Second";
static PREFIXCONST char POSTCONST tv_IDS_TWELVE_SECOND_1[]="12秒钟";

static PREFIXCONST char POSTCONST tv_IDS_STORE_CHANGE_0[]="Store Change";
static PREFIXCONST char POSTCONST tv_IDS_STORE_CHANGE_1[]="存储器转换";

static PREFIXCONST char POSTCONST tv_IDS_BROADCAST_0[]="Broadcast";
static PREFIXCONST char POSTCONST tv_IDS_BROADCAST_1[]="广播";

static PREFIXCONST char POSTCONST tv_IDS_PROMPT_0[]="Prompt";
static PREFIXCONST char POSTCONST tv_IDS_PROMPT_1[]="提示";

static PREFIXCONST char POSTCONST tv_IDS_SELECT_DELETE_0[]="Delete ?";
static PREFIXCONST char POSTCONST tv_IDS_SELECT_DELETE_1[]="是否确认删除该文件？";

static PREFIXCONST char POSTCONST tv_IDS_NO_TV_0[]="No TV channels";
static PREFIXCONST char POSTCONST tv_IDS_NO_TV_1[]="没有电视节目";

static PREFIXCONST char POSTCONST tv_IDS_NO_RADIO_0[]="No Radio channels";
static PREFIXCONST char POSTCONST tv_IDS_NO_RADIO_1[]="没有广播节目";

static PREFIXCONST char POSTCONST tv_IDS_NO_SIGNAL_0[]="No Signal";
static PREFIXCONST char POSTCONST tv_IDS_NO_SIGNAL_1[]="信号中断";

static PREFIXCONST char POSTCONST tv_IDS_CUR_PROG_0[]="Current program:";
static PREFIXCONST char POSTCONST tv_IDS_CUR_PROG_1[]="正在播出:";

static PREFIXCONST char POSTCONST tv_IDS_NEXT_PROG_0[]="Next program :";
static PREFIXCONST char POSTCONST tv_IDS_NEXT_PROG_1[]="即将播出:";

static PREFIXCONST char POSTCONST tv_IDS_INVALID_CHAN_NUM_0[]="Invalid chan num";
static PREFIXCONST char POSTCONST tv_IDS_INVALID_CHAN_NUM_1[]="无效频道编号";

static PREFIXCONST char POSTCONST tv_IDS_RANDOM_PLAY_0[]="Random_Play";
static PREFIXCONST char POSTCONST tv_IDS_RANDOM_PLAY_1[]="随机";

static PREFIXCONST char POSTCONST tv_IDS_ONE_LOOP_PLAY_0[]="One_Loop_Play";
static PREFIXCONST char POSTCONST tv_IDS_ONE_LOOP_PLAY_1[]="单曲";

static PREFIXCONST char POSTCONST tv_IDS_FULL_SCREEN_0[]="Full_Screen";
static PREFIXCONST char POSTCONST tv_IDS_FULL_SCREEN_1[]="全屏";

static PREFIXCONST char POSTCONST tv_IDS_USB_0[]="Usb";
static PREFIXCONST char POSTCONST tv_IDS_USB_1[]="Usb";

static PREFIXCONST char POSTCONST tv_IDS_SD_0[]="Sd";
static PREFIXCONST char POSTCONST tv_IDS_SD_1[]="Sd";

static PREFIXCONST char POSTCONST tv_IDS_SLIDE_0[]="Slide";
static PREFIXCONST char POSTCONST tv_IDS_SLIDE_1[]="幻灯片";

static PREFIXCONST char POSTCONST tv_IDS_CHINESE_0[]="Chinese";
static PREFIXCONST char POSTCONST tv_IDS_CHINESE_1[]="中文";

static PREFIXCONST char POSTCONST tv_IDS_ENGLISH_0[]="English";
static PREFIXCONST char POSTCONST tv_IDS_ENGLISH_1[]="英文";

static PREFIXCONST char POSTCONST tv_IDS_BOXINFORMATION_0[]="Information";
static PREFIXCONST char POSTCONST tv_IDS_BOXINFORMATION_1[]="本机信息";

static PREFIXCONST char POSTCONST tv_IDS_HARDWAREEDITION_0[]="Hardware";
static PREFIXCONST char POSTCONST tv_IDS_HARDWAREEDITION_1[]="硬件版本";

static PREFIXCONST char POSTCONST tv_IDS_SOFTWAREEDITION_0[]="Software";
static PREFIXCONST char POSTCONST tv_IDS_SOFTWAREEDITION_1[]="软件版本";

static PREFIXCONST char POSTCONST tv_IDS_HEDITION_0[]="120.111.1.0";
static PREFIXCONST char POSTCONST tv_IDS_HEDITION_1[]="120.111.1.0";

static PREFIXCONST char POSTCONST tv_IDS_SEDITION_0[]="1.0.275-0.0.0.0";
static PREFIXCONST char POSTCONST tv_IDS_SEDITION_1[]="1.0.275-0.0.0.0";

static PREFIXCONST char POSTCONST tv_IDS_ISSUANCEDATE_0[]="Date";
static PREFIXCONST char POSTCONST tv_IDS_ISSUANCEDATE_1[]="发布日期";

static PREFIXCONST char POSTCONST tv_IDS_RECOVER_OK_0[]="Recover ok";
static PREFIXCONST char POSTCONST tv_IDS_RECOVER_OK_1[]="恢复成功";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_0[]="Record";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_1[]="录像";

static PREFIXCONST char POSTCONST tv_IDS_NO_FIND_DISK_0[]="No Find Disk";
static PREFIXCONST char POSTCONST tv_IDS_NO_FIND_DISK_1[]="没有发现磁盘";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_PLAYING_0[]="Record Play";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_PLAYING_1[]="录像播放";

static PREFIXCONST char POSTCONST tv_IDS_NO_SPACE_0[]="No Space";
static PREFIXCONST char POSTCONST tv_IDS_NO_SPACE_1[]="磁盘没有空间";

static PREFIXCONST char POSTCONST tv_IDS_ENTER_RECORD_0[]="Enter Record, Waiting…";
static PREFIXCONST char POSTCONST tv_IDS_ENTER_RECORD_1[]="开始录像,请稍等…";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_FAILED_0[]="Record Failed";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_FAILED_1[]="启动录制失败！";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_TIME_0[]="Record Time";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_TIME_1[]="录制时间";

static PREFIXCONST char POSTCONST tv_IDS_INPUT_RECORD_TIME_0[]="Please Input Record Time..";
static PREFIXCONST char POSTCONST tv_IDS_INPUT_RECORD_TIME_1[]="请输入录制的时间";

static PREFIXCONST char POSTCONST tv_IDS_STOP_RECORD_0[]="Stop Record";
static PREFIXCONST char POSTCONST tv_IDS_STOP_RECORD_1[]="是否停止录制？";

static PREFIXCONST char POSTCONST tv_IDS_REICORD_FILE_LARGE_0[]="The file's size more than 4G,saving andexit!";
static PREFIXCONST char POSTCONST tv_IDS_REICORD_FILE_LARGE_1[]="文件超过4G，保存数据并退出";

static PREFIXCONST char POSTCONST tv_IDS_INVAILD_INPUT_0[]="Invalid Input";
static PREFIXCONST char POSTCONST tv_IDS_INVAILD_INPUT_1[]="无效输入！";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_END_0[]="Record End";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_END_1[]="录制已完成，正在保存…";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_NOT_CHANGE_CHANNEL_0[]="Recording…";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_NOT_CHANGE_CHANNEL_1[]="录制中不允许换台！";

static PREFIXCONST char POSTCONST tv_IDS_BAD_SIGNAL_SAVING_0[]="Bad signal,saving and exit record !";
static PREFIXCONST char POSTCONST tv_IDS_BAD_SIGNAL_SAVING_1[]="信号中断，保存数据并退出";

static PREFIXCONST char POSTCONST tv_IDS_USB_REMOVED_0[]="USB device is removed";
static PREFIXCONST char POSTCONST tv_IDS_USB_REMOVED_1[]="USB设备已被移走";

static PREFIXCONST char POSTCONST tv_IDS_RECORD_TIME_OUT_0[]="Record Time Out";
static PREFIXCONST char POSTCONST tv_IDS_RECORD_TIME_OUT_1[]="录制时间已到";

static PREFIXCONST char POSTCONST tv_IDS_READ_DISK_INFO_0[]="Read Disk Info, Waiting…";
static PREFIXCONST char POSTCONST tv_IDS_READ_DISK_INFO_1[]="正在读取磁盘信息，请稍等…";

static PREFIXCONST char POSTCONST tv_IDS_NONGLI_0[]="The lunar calendar";
static PREFIXCONST char POSTCONST tv_IDS_NONGLI_1[]="农历";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_MONDAY_0[]="Mon";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_MONDAY_1[]="一";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_TUESDAY_0[]="Tue";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_TUESDAY_1[]="二";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_WENDSDAY_0[]="Wen";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_WENDSDAY_1[]="三";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_THURSDAY_0[]="Thu";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_THURSDAY_1[]="四";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_FRIDAY_0[]="Fri";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_FRIDAY_1[]="五";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SATURDAY_0[]="Sat";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SATURDAY_1[]="六";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SUNDAY_0[]="Sun";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SUNDAY_1[]="日";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SET_TIME_0[]="Set time";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SET_TIME_1[]="时间设置";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SET_DATE_0[]="Set date";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SET_DATE_1[]="日期选择";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_YEAR_0[]="Year";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_YEAR_1[]="年";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_MONTH_0[]="Month";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_MONTH_1[]="月";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_DAY_0[]="Day";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_DAY_1[]="日";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_HOUR_0[]="Hour";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_HOUR_1[]="时";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_MINUTE_0[]="Minute";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_MINUTE_1[]="分";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SECONDS_0[]="Seconds";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_SECONDS_1[]="秒";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_YEAR_0[]="You input year is error，please input again！";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_YEAR_1[]="您输入的年份不在1970~2050年之间，请重新输入！";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_MONTH_0[]="You input month is error，please input again！";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_MONTH_1[]="您输入的月份不在1~12月之间，请重新输入！";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_DATE_0[]="You input date is error, please input again！";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_DATE_1[]="您输入的日期不正确，请重新输入！";

static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_TIME_0[]="You input time is error，please input again！";
static PREFIXCONST char POSTCONST tv_IDS_CALENDAR_ERR_TIME_1[]="您输入的时间不正确，请重新输入！";

static PREFIXCONST char POSTCONST tv_IDS_NEW_SOFTWARE_0[]="New Software";
static PREFIXCONST char POSTCONST tv_IDS_NEW_SOFTWARE_1[]="软件更新";

static PREFIXCONST char POSTCONST tv_IDS_SW_UPDATE_0[]="New software found,update now?";
static PREFIXCONST char POSTCONST tv_IDS_SW_UPDATE_1[]="已有新版本软件，是否立即升级?";

static PREFIXCONST char POSTCONST tv_IDS_SW_UPDATE_MUST_0[]="New software found,system will update automatic,please do not power off!";
static PREFIXCONST char POSTCONST tv_IDS_SW_UPDATE_MUST_1[]="已有新版本软件，将自动进行升级，请勿断电!";

static PREFIXCONST char POSTCONST tv_IDS_MANUAL_SCAN_0[]="Manual Scan";
static PREFIXCONST char POSTCONST tv_IDS_MANUAL_SCAN_1[]="手动搜索";

static PREFIXCONST char POSTCONST tv_IDS_FREQUENCY_0[]="Frequency";
static PREFIXCONST char POSTCONST tv_IDS_FREQUENCY_1[]="频率";

static PREFIXCONST char POSTCONST tv_IDS_STRENGTH_0[]="Strength";
static PREFIXCONST char POSTCONST tv_IDS_STRENGTH_1[]="强度";

static PREFIXCONST char POSTCONST tv_IDS_QUALITY_0[]="Quality";
static PREFIXCONST char POSTCONST tv_IDS_QUALITY_1[]="质量";

static PREFIXCONST char POSTCONST tv_IDS_FIVE_SECOND_0[]="Five Second";
static PREFIXCONST char POSTCONST tv_IDS_FIVE_SECOND_1[]="5秒钟";

static PREFIXCONST char POSTCONST tv_IDS_FIFTEEN_SECOND_0[]="Fifteen Second";
static PREFIXCONST char POSTCONST tv_IDS_FIFTEEN_SECOND_1[]="15秒钟";

static PREFIXCONST char POSTCONST tv_IDS_THIRTY_SECOND_0[]="Thirty Second";
static PREFIXCONST char POSTCONST tv_IDS_THIRTY_SECOND_1[]="30秒钟";

static PREFIXCONST char POSTCONST tv_IDS_ONE_MINUTE_0[]="One Minute";
static PREFIXCONST char POSTCONST tv_IDS_ONE_MINUTE_1[]="1分钟";

static PREFIXCONST char POSTCONST tv_IDS_ALWAYS_EXIST_0[]="Always Exist";
static PREFIXCONST char POSTCONST tv_IDS_ALWAYS_EXIST_1[]="永不";

static PREFIXCONST char POSTCONST tv_IDS_TIME_OF_CLOSE_SCREEN_0[]="Time of close screen";
static PREFIXCONST char POSTCONST tv_IDS_TIME_OF_CLOSE_SCREEN_1[]="暗屏时间";

static PREFIXCONST char POSTCONST tv_IDS_TEN_PERCENT_0[]="Ten Percent";
static PREFIXCONST char POSTCONST tv_IDS_TEN_PERCENT_1[]="10%";

static PREFIXCONST char POSTCONST tv_IDS_TWENTY_PERCENT_0[]="Twenty Percent";
static PREFIXCONST char POSTCONST tv_IDS_TWENTY_PERCENT_1[]="20%";

static PREFIXCONST char POSTCONST tv_IDS_THIRTY_PRECENT_0[]="Thirty Percent";
static PREFIXCONST char POSTCONST tv_IDS_THIRTY_PRECENT_1[]="30%";

static PREFIXCONST char POSTCONST tv_IDS_FORTY_PERCENT_0[]="Forty Percent";
static PREFIXCONST char POSTCONST tv_IDS_FORTY_PERCENT_1[]="40%";

static PREFIXCONST char POSTCONST tv_IDS_FIFTY_PERCEN_0[]="Fifty Percent";
static PREFIXCONST char POSTCONST tv_IDS_FIFTY_PERCEN_1[]="50%";

static PREFIXCONST char POSTCONST tv_IDS_SIXTY_PERCENT_0[]="Sixty Percent";
static PREFIXCONST char POSTCONST tv_IDS_SIXTY_PERCENT_1[]="60%";

static PREFIXCONST char POSTCONST tv_IDS_SEVENTY_PERCENT_0[]="Seventy Percent";
static PREFIXCONST char POSTCONST tv_IDS_SEVENTY_PERCENT_1[]="70%";

static PREFIXCONST char POSTCONST tv_IDS_EIGHTY_PRECENT_0[]="Eight Percent";
static PREFIXCONST char POSTCONST tv_IDS_EIGHTY_PRECENT_1[]="80%";

static PREFIXCONST char POSTCONST tv_IDS_NINETY_PERCENT_0[]="Ninety Percent";
static PREFIXCONST char POSTCONST tv_IDS_NINETY_PERCENT_1[]="90%";

static PREFIXCONST char POSTCONST tv_IDS_HUNDRED_PERCENT_0[]="Hundred Percent";
static PREFIXCONST char POSTCONST tv_IDS_HUNDRED_PERCENT_1[]="100%";

static PREFIXCONST char POSTCONST tv_IDS_PLAY_FAILED_0[]="Play Failed";
static PREFIXCONST char POSTCONST tv_IDS_PLAY_FAILED_1[]="播放失败";


static PREFIXCONST char POSTCONST *language_prefix_English[]={
	tv_IDS_NULL_0,		// tv_tv_IDS_NULL
	tv_IDS_TV_0,		// tv_tv_IDS_TV
	tv_IDS_VIDEO_0,		// tv_tv_IDS_VIDEO
	tv_IDS_MUSIC_0,		// tv_tv_IDS_MUSIC
	tv_IDS_PHOTO_0,		// tv_tv_IDS_PHOTO
	tv_IDS_RADIO_0,		// tv_tv_IDS_RADIO
	tv_IDS_TOOL_0,		// tv_tv_IDS_TOOL
	tv_IDS_SUNDAY_0,		// tv_tv_IDS_SUNDAY
	tv_IDS_MONDAY_0,		// tv_tv_IDS_MONDAY
	tv_IDS_TUESDAY_0,		// tv_tv_IDS_TUESDAY
	tv_IDS_WENDSDAY_0,		// tv_tv_IDS_WENDSDAY
	tv_IDS_THURSDAY_0,		// tv_tv_IDS_THURSDAY
	tv_IDS_FRIDAY_0,		// tv_tv_IDS_FRIDAY
	tv_IDS_SATURDAY_0,		// tv_tv_IDS_SATURDAY
	tv_IDS_SEARCH_CHANNEL_0,		// tv_tv_IDS_SEARCH_CHANNEL
	tv_IDS_LIST_CHANNEL_0,		// tv_tv_IDS_LIST_CHANNEL
	tv_IDS_SHOW_SCALE_0,		// tv_tv_IDS_SHOW_SCALE
	tv_IDS_BRIGHT_0,		// tv_tv_IDS_BRIGHT
	tv_IDS_TRACK_0,		// tv_tv_IDS_TRACK
	tv_IDS_CANCEL_0,		// tv_tv_IDS_CANCEL
	tv_IDS_SCAN_CHANNEL_0,		// tv_tv_IDS_SCAN_CHANNEL
	tv_IDS_DURING_TIME_0,		// tv_tv_IDS_DURING_TIME
	tv_IDS_SIZE_0,		// tv_tv_IDS_SIZE
	tv_IDS_CHOOSE_TIME_0,		// tv_tv_IDS_CHOOSE_TIME
	tv_IDS_PLAY_CONTROL_0,		// tv_tv_IDS_PLAY_CONTROL
	tv_IDS_ORDER_PLAY_0,		// tv_tv_IDS_ORDER_PLAY
	tv_IDS_CIRCLE_PLAY_0,		// tv_tv_IDS_CIRCLE_PLAY
	tv_IDS_ALBUM_0,		// tv_tv_IDS_ALBUM
	tv_IDS_SIGNER_0,		// tv_tv_IDS_SIGNER
	tv_IDS_E_BOOK_0,		// tv_tv_IDS_E_BOOK
	tv_IDS_MOVIDE_MANAGE_0,		// tv_tv_IDS_MOVIDE_MANAGE
	tv_IDS_FILE_MANAGE_0,		// tv_tv_IDS_FILE_MANAGE
	tv_IDS_CALENDAR_0,		// tv_tv_IDS_CALENDAR
	tv_IDS_SET_UP_0,		// tv_tv_IDS_SET_UP
	tv_IDS_LANGUAGE_CHOOSE_0,		// tv_tv_IDS_LANGUAGE_CHOOSE
	tv_IDS_PRODUCT_INFO_0,		// tv_tv_IDS_PRODUCT_INFO
	tv_IDS_DEFAULT_SET_0,		// tv_tv_IDS_DEFAULT_SET
	tv_IDS_OK_0,		// tv_tv_IDS_OK
	tv_IDS_OUTPUT_0,		// tv_tv_IDS_OUTPUT
	tv_IDS_INPUT_RANGE_0,		// tv_tv_IDS_INPUT_RANGE
	tv_IDS_LEFT_0,		// tv_tv_IDS_LEFT
	tv_IDS_RIGHT_0,		// tv_tv_IDS_RIGHT
	tv_IDS_STEREO_0,		// tv_tv_IDS_STEREO
	tv_IDS_4TO3_0,		// tv_tv_IDS_4TO3
	tv_IDS_16T09_0,		// tv_tv_IDS_16T09
	tv_IDS_TV_CHANNEL_LIST_0,		// tv_tv_IDS_TV_CHANNEL_LIST
	tv_IDS_RADIO_CHANNEL_LIST_0,		// tv_tv_IDS_RADIO_CHANNEL_LIST
	tv_IDS_VOLUME_0,		// tv_tv_IDS_VOLUME
	tv_IDS_AUTO_SCAN_0,		// tv_tv_IDS_AUTO_SCAN
	tv_IDS_FILE_FORMAT_0,		// tv_tv_IDS_FILE_FORMAT
	tv_IDS_FILE_SIZE_0,		// tv_tv_IDS_FILE_SIZE
	tv_IDS_SLIDE_PLAY_0,		// tv_tv_IDS_SLIDE_PLAY
	tv_IDS_REVOLVE_0,		// tv_tv_IDS_REVOLVE
	tv_IDS_MUSIC_ON_0,		// tv_tv_IDS_MUSIC_ON
	tv_IDS_MUSIC_OFF_0,		// tv_tv_IDS_MUSIC_OFF
	tv_IDS_SLIDE_SPEED_0,		// tv_tv_IDS_SLIDE_SPEED
	tv_IDS_SLIDE_PAUSE_0,		// tv_tv_IDS_SLIDE_PAUSE
	tv_IDS_TWO_SECOND_0,		// tv_tv_IDS_TWO_SECOND
	tv_IDS_FOUR_SECOND_0,		// tv_tv_IDS_FOUR_SECOND
	tv_IDS_SIX_SECOND_0,		// tv_tv_IDS_SIX_SECOND
	tv_IDS_EIGHT_SECOND_0,		// tv_tv_IDS_EIGHT_SECOND
	tv_IDS_TEN_SECOND_0,		// tv_tv_IDS_TEN_SECOND
	tv_IDS_TWELVE_SECOND_0,		// tv_tv_IDS_TWELVE_SECOND
	tv_IDS_STORE_CHANGE_0,		// tv_tv_IDS_STORE_CHANGE
	tv_IDS_BROADCAST_0,		// tv_tv_IDS_BROADCAST
	tv_IDS_PROMPT_0,		// tv_tv_IDS_PROMPT
	tv_IDS_SELECT_DELETE_0,		// tv_tv_IDS_SELECT_DELETE
	tv_IDS_NO_TV_0,		// tv_tv_IDS_NO_TV
	tv_IDS_NO_RADIO_0,		// tv_tv_IDS_NO_RADIO
	tv_IDS_NO_SIGNAL_0,		// tv_tv_IDS_NO_SIGNAL
	tv_IDS_CUR_PROG_0,		// tv_tv_IDS_CUR_PROG
	tv_IDS_NEXT_PROG_0,		// tv_tv_IDS_NEXT_PROG
	tv_IDS_INVALID_CHAN_NUM_0,		// tv_tv_IDS_INVALID_CHAN_NUM
	tv_IDS_RANDOM_PLAY_0,		// tv_tv_IDS_RANDOM_PLAY
	tv_IDS_ONE_LOOP_PLAY_0,		// tv_tv_IDS_ONE_LOOP_PLAY
	tv_IDS_FULL_SCREEN_0,		// tv_tv_IDS_FULL_SCREEN
	tv_IDS_USB_0,		// tv_tv_IDS_USB
	tv_IDS_SD_0,		// tv_tv_IDS_SD
	tv_IDS_SLIDE_0,		// tv_tv_IDS_SLIDE
	tv_IDS_CHINESE_0,		// tv_tv_IDS_CHINESE
	tv_IDS_ENGLISH_0,		// tv_tv_IDS_ENGLISH
	tv_IDS_BOXINFORMATION_0,		// tv_tv_IDS_BOXINFORMATION
	tv_IDS_HARDWAREEDITION_0,		// tv_tv_IDS_HARDWAREEDITION
	tv_IDS_SOFTWAREEDITION_0,		// tv_tv_IDS_SOFTWAREEDITION
	tv_IDS_HEDITION_0,		// tv_tv_IDS_HEDITION
	tv_IDS_SEDITION_0,		// tv_tv_IDS_SEDITION
	tv_IDS_ISSUANCEDATE_0,		// tv_tv_IDS_ISSUANCEDATE
	tv_IDS_RECOVER_OK_0,		// tv_tv_IDS_RECOVER_OK
	tv_IDS_RECORD_0,		// tv_tv_IDS_RECORD
	tv_IDS_NO_FIND_DISK_0,		// tv_tv_IDS_NO_FIND_DISK
	tv_IDS_RECORD_PLAYING_0,		// tv_tv_IDS_RECORD_PLAYING
	tv_IDS_NO_SPACE_0,		// tv_tv_IDS_NO_SPACE
	tv_IDS_ENTER_RECORD_0,		// tv_tv_IDS_ENTER_RECORD
	tv_IDS_RECORD_FAILED_0,		// tv_tv_IDS_RECORD_FAILED
	tv_IDS_RECORD_TIME_0,		// tv_tv_IDS_RECORD_TIME
	tv_IDS_INPUT_RECORD_TIME_0,		// tv_tv_IDS_INPUT_RECORD_TIME
	tv_IDS_STOP_RECORD_0,		// tv_tv_IDS_STOP_RECORD
	tv_IDS_REICORD_FILE_LARGE_0,		// tv_tv_IDS_REICORD_FILE_LARGE
	tv_IDS_INVAILD_INPUT_0,		// tv_tv_IDS_INVAILD_INPUT
	tv_IDS_RECORD_END_0,		// tv_tv_IDS_RECORD_END
	tv_IDS_RECORD_NOT_CHANGE_CHANNEL_0,		// tv_tv_IDS_RECORD_NOT_CHANGE_CHANNEL
	tv_IDS_BAD_SIGNAL_SAVING_0,		// tv_tv_IDS_BAD_SIGNAL_SAVING
	tv_IDS_USB_REMOVED_0,		// tv_tv_IDS_USB_REMOVED
	tv_IDS_RECORD_TIME_OUT_0,		// tv_tv_IDS_RECORD_TIME_OUT
	tv_IDS_READ_DISK_INFO_0,		// tv_tv_IDS_READ_DISK_INFO
	tv_IDS_NONGLI_0,		// tv_tv_IDS_NONGLI
	tv_IDS_CALENDAR_MONDAY_0,		// tv_tv_IDS_CALENDAR_MONDAY
	tv_IDS_CALENDAR_TUESDAY_0,		// tv_tv_IDS_CALENDAR_TUESDAY
	tv_IDS_CALENDAR_WENDSDAY_0,		// tv_tv_IDS_CALENDAR_WENDSDAY
	tv_IDS_CALENDAR_THURSDAY_0,		// tv_tv_IDS_CALENDAR_THURSDAY
	tv_IDS_CALENDAR_FRIDAY_0,		// tv_tv_IDS_CALENDAR_FRIDAY
	tv_IDS_CALENDAR_SATURDAY_0,		// tv_tv_IDS_CALENDAR_SATURDAY
	tv_IDS_CALENDAR_SUNDAY_0,		// tv_tv_IDS_CALENDAR_SUNDAY
	tv_IDS_CALENDAR_SET_TIME_0,		// tv_tv_IDS_CALENDAR_SET_TIME
	tv_IDS_CALENDAR_SET_DATE_0,		// tv_tv_IDS_CALENDAR_SET_DATE
	tv_IDS_CALENDAR_YEAR_0,		// tv_tv_IDS_CALENDAR_YEAR
	tv_IDS_CALENDAR_MONTH_0,		// tv_tv_IDS_CALENDAR_MONTH
	tv_IDS_CALENDAR_DAY_0,		// tv_tv_IDS_CALENDAR_DAY
	tv_IDS_CALENDAR_HOUR_0,		// tv_tv_IDS_CALENDAR_HOUR
	tv_IDS_CALENDAR_MINUTE_0,		// tv_tv_IDS_CALENDAR_MINUTE
	tv_IDS_CALENDAR_SECONDS_0,		// tv_tv_IDS_CALENDAR_SECONDS
	tv_IDS_CALENDAR_ERR_YEAR_0,		// tv_tv_IDS_CALENDAR_ERR_YEAR
	tv_IDS_CALENDAR_ERR_MONTH_0,		// tv_tv_IDS_CALENDAR_ERR_MONTH
	tv_IDS_CALENDAR_ERR_DATE_0,		// tv_tv_IDS_CALENDAR_ERR_DATE
	tv_IDS_CALENDAR_ERR_TIME_0,		// tv_tv_IDS_CALENDAR_ERR_TIME
	tv_IDS_NEW_SOFTWARE_0,		// tv_tv_IDS_NEW_SOFTWARE
	tv_IDS_SW_UPDATE_0,		// tv_tv_IDS_SW_UPDATE
	tv_IDS_SW_UPDATE_MUST_0,		// tv_tv_IDS_SW_UPDATE_MUST
	tv_IDS_MANUAL_SCAN_0,		// tv_tv_IDS_MANUAL_SCAN
	tv_IDS_FREQUENCY_0,		// tv_tv_IDS_FREQUENCY
	tv_IDS_STRENGTH_0,		// tv_tv_IDS_STRENGTH
	tv_IDS_QUALITY_0,		// tv_tv_IDS_QUALITY
	tv_IDS_FIVE_SECOND_0,		// tv_tv_IDS_FIVE_SECOND
	tv_IDS_FIFTEEN_SECOND_0,		// tv_tv_IDS_FIFTEEN_SECOND
	tv_IDS_THIRTY_SECOND_0,		// tv_tv_IDS_THIRTY_SECOND
	tv_IDS_ONE_MINUTE_0,		// tv_tv_IDS_ONE_MINUTE
	tv_IDS_ALWAYS_EXIST_0,		// tv_tv_IDS_ALWAYS_EXIST
	tv_IDS_TIME_OF_CLOSE_SCREEN_0,		// tv_tv_IDS_TIME_OF_CLOSE_SCREEN
	tv_IDS_TEN_PERCENT_0,		// tv_tv_IDS_TEN_PERCENT
	tv_IDS_TWENTY_PERCENT_0,		// tv_tv_IDS_TWENTY_PERCENT
	tv_IDS_THIRTY_PRECENT_0,		// tv_tv_IDS_THIRTY_PRECENT
	tv_IDS_FORTY_PERCENT_0,		// tv_tv_IDS_FORTY_PERCENT
	tv_IDS_FIFTY_PERCEN_0,		// tv_tv_IDS_FIFTY_PERCEN
	tv_IDS_SIXTY_PERCENT_0,		// tv_tv_IDS_SIXTY_PERCENT
	tv_IDS_SEVENTY_PERCENT_0,		// tv_tv_IDS_SEVENTY_PERCENT
	tv_IDS_EIGHTY_PRECENT_0,		// tv_tv_IDS_EIGHTY_PRECENT
	tv_IDS_NINETY_PERCENT_0,		// tv_tv_IDS_NINETY_PERCENT
	tv_IDS_HUNDRED_PERCENT_0,		// tv_tv_IDS_HUNDRED_PERCENT
	tv_IDS_PLAY_FAILED_0,		// tv_tv_IDS_PLAY_FAILED
};

static PREFIXCONST char POSTCONST *language_prefix_Chinese[]={
	tv_IDS_NULL_1,		// tv_tv_IDS_NULL
	tv_IDS_TV_1,		// tv_tv_IDS_TV
	tv_IDS_VIDEO_1,		// tv_tv_IDS_VIDEO
	tv_IDS_MUSIC_1,		// tv_tv_IDS_MUSIC
	tv_IDS_PHOTO_1,		// tv_tv_IDS_PHOTO
	tv_IDS_RADIO_1,		// tv_tv_IDS_RADIO
	tv_IDS_TOOL_1,		// tv_tv_IDS_TOOL
	tv_IDS_SUNDAY_1,		// tv_tv_IDS_SUNDAY
	tv_IDS_MONDAY_1,		// tv_tv_IDS_MONDAY
	tv_IDS_TUESDAY_1,		// tv_tv_IDS_TUESDAY
	tv_IDS_WENDSDAY_1,		// tv_tv_IDS_WENDSDAY
	tv_IDS_THURSDAY_1,		// tv_tv_IDS_THURSDAY
	tv_IDS_FRIDAY_1,		// tv_tv_IDS_FRIDAY
	tv_IDS_SATURDAY_1,		// tv_tv_IDS_SATURDAY
	tv_IDS_SEARCH_CHANNEL_1,		// tv_tv_IDS_SEARCH_CHANNEL
	tv_IDS_LIST_CHANNEL_1,		// tv_tv_IDS_LIST_CHANNEL
	tv_IDS_SHOW_SCALE_1,		// tv_tv_IDS_SHOW_SCALE
	tv_IDS_BRIGHT_1,		// tv_tv_IDS_BRIGHT
	tv_IDS_TRACK_1,		// tv_tv_IDS_TRACK
	tv_IDS_CANCEL_1,		// tv_tv_IDS_CANCEL
	tv_IDS_SCAN_CHANNEL_1,		// tv_tv_IDS_SCAN_CHANNEL
	tv_IDS_DURING_TIME_1,		// tv_tv_IDS_DURING_TIME
	tv_IDS_SIZE_1,		// tv_tv_IDS_SIZE
	tv_IDS_CHOOSE_TIME_1,		// tv_tv_IDS_CHOOSE_TIME
	tv_IDS_PLAY_CONTROL_1,		// tv_tv_IDS_PLAY_CONTROL
	tv_IDS_ORDER_PLAY_1,		// tv_tv_IDS_ORDER_PLAY
	tv_IDS_CIRCLE_PLAY_1,		// tv_tv_IDS_CIRCLE_PLAY
	tv_IDS_ALBUM_1,		// tv_tv_IDS_ALBUM
	tv_IDS_SIGNER_1,		// tv_tv_IDS_SIGNER
	tv_IDS_E_BOOK_1,		// tv_tv_IDS_E_BOOK
	tv_IDS_MOVIDE_MANAGE_1,		// tv_tv_IDS_MOVIDE_MANAGE
	tv_IDS_FILE_MANAGE_1,		// tv_tv_IDS_FILE_MANAGE
	tv_IDS_CALENDAR_1,		// tv_tv_IDS_CALENDAR
	tv_IDS_SET_UP_1,		// tv_tv_IDS_SET_UP
	tv_IDS_LANGUAGE_CHOOSE_1,		// tv_tv_IDS_LANGUAGE_CHOOSE
	tv_IDS_PRODUCT_INFO_1,		// tv_tv_IDS_PRODUCT_INFO
	tv_IDS_DEFAULT_SET_1,		// tv_tv_IDS_DEFAULT_SET
	tv_IDS_OK_1,		// tv_tv_IDS_OK
	tv_IDS_OUTPUT_1,		// tv_tv_IDS_OUTPUT
	tv_IDS_INPUT_RANGE_1,		// tv_tv_IDS_INPUT_RANGE
	tv_IDS_LEFT_1,		// tv_tv_IDS_LEFT
	tv_IDS_RIGHT_1,		// tv_tv_IDS_RIGHT
	tv_IDS_STEREO_1,		// tv_tv_IDS_STEREO
	tv_IDS_4TO3_1,		// tv_tv_IDS_4TO3
	tv_IDS_16T09_1,		// tv_tv_IDS_16T09
	tv_IDS_TV_CHANNEL_LIST_1,		// tv_tv_IDS_TV_CHANNEL_LIST
	tv_IDS_RADIO_CHANNEL_LIST_1,		// tv_tv_IDS_RADIO_CHANNEL_LIST
	tv_IDS_VOLUME_1,		// tv_tv_IDS_VOLUME
	tv_IDS_AUTO_SCAN_1,		// tv_tv_IDS_AUTO_SCAN
	tv_IDS_FILE_FORMAT_1,		// tv_tv_IDS_FILE_FORMAT
	tv_IDS_FILE_SIZE_1,		// tv_tv_IDS_FILE_SIZE
	tv_IDS_SLIDE_PLAY_1,		// tv_tv_IDS_SLIDE_PLAY
	tv_IDS_REVOLVE_1,		// tv_tv_IDS_REVOLVE
	tv_IDS_MUSIC_ON_1,		// tv_tv_IDS_MUSIC_ON
	tv_IDS_MUSIC_OFF_1,		// tv_tv_IDS_MUSIC_OFF
	tv_IDS_SLIDE_SPEED_1,		// tv_tv_IDS_SLIDE_SPEED
	tv_IDS_SLIDE_PAUSE_1,		// tv_tv_IDS_SLIDE_PAUSE
	tv_IDS_TWO_SECOND_1,		// tv_tv_IDS_TWO_SECOND
	tv_IDS_FOUR_SECOND_1,		// tv_tv_IDS_FOUR_SECOND
	tv_IDS_SIX_SECOND_1,		// tv_tv_IDS_SIX_SECOND
	tv_IDS_EIGHT_SECOND_1,		// tv_tv_IDS_EIGHT_SECOND
	tv_IDS_TEN_SECOND_1,		// tv_tv_IDS_TEN_SECOND
	tv_IDS_TWELVE_SECOND_1,		// tv_tv_IDS_TWELVE_SECOND
	tv_IDS_STORE_CHANGE_1,		// tv_tv_IDS_STORE_CHANGE
	tv_IDS_BROADCAST_1,		// tv_tv_IDS_BROADCAST
	tv_IDS_PROMPT_1,		// tv_tv_IDS_PROMPT
	tv_IDS_SELECT_DELETE_1,		// tv_tv_IDS_SELECT_DELETE
	tv_IDS_NO_TV_1,		// tv_tv_IDS_NO_TV
	tv_IDS_NO_RADIO_1,		// tv_tv_IDS_NO_RADIO
	tv_IDS_NO_SIGNAL_1,		// tv_tv_IDS_NO_SIGNAL
	tv_IDS_CUR_PROG_1,		// tv_tv_IDS_CUR_PROG
	tv_IDS_NEXT_PROG_1,		// tv_tv_IDS_NEXT_PROG
	tv_IDS_INVALID_CHAN_NUM_1,		// tv_tv_IDS_INVALID_CHAN_NUM
	tv_IDS_RANDOM_PLAY_1,		// tv_tv_IDS_RANDOM_PLAY
	tv_IDS_ONE_LOOP_PLAY_1,		// tv_tv_IDS_ONE_LOOP_PLAY
	tv_IDS_FULL_SCREEN_1,		// tv_tv_IDS_FULL_SCREEN
	tv_IDS_USB_1,		// tv_tv_IDS_USB
	tv_IDS_SD_1,		// tv_tv_IDS_SD
	tv_IDS_SLIDE_1,		// tv_tv_IDS_SLIDE
	tv_IDS_CHINESE_1,		// tv_tv_IDS_CHINESE
	tv_IDS_ENGLISH_1,		// tv_tv_IDS_ENGLISH
	tv_IDS_BOXINFORMATION_1,		// tv_tv_IDS_BOXINFORMATION
	tv_IDS_HARDWAREEDITION_1,		// tv_tv_IDS_HARDWAREEDITION
	tv_IDS_SOFTWAREEDITION_1,		// tv_tv_IDS_SOFTWAREEDITION
	tv_IDS_HEDITION_1,		// tv_tv_IDS_HEDITION
	tv_IDS_SEDITION_1,		// tv_tv_IDS_SEDITION
	tv_IDS_ISSUANCEDATE_1,		// tv_tv_IDS_ISSUANCEDATE
	tv_IDS_RECOVER_OK_1,		// tv_tv_IDS_RECOVER_OK
	tv_IDS_RECORD_1,		// tv_tv_IDS_RECORD
	tv_IDS_NO_FIND_DISK_1,		// tv_tv_IDS_NO_FIND_DISK
	tv_IDS_RECORD_PLAYING_1,		// tv_tv_IDS_RECORD_PLAYING
	tv_IDS_NO_SPACE_1,		// tv_tv_IDS_NO_SPACE
	tv_IDS_ENTER_RECORD_1,		// tv_tv_IDS_ENTER_RECORD
	tv_IDS_RECORD_FAILED_1,		// tv_tv_IDS_RECORD_FAILED
	tv_IDS_RECORD_TIME_1,		// tv_tv_IDS_RECORD_TIME
	tv_IDS_INPUT_RECORD_TIME_1,		// tv_tv_IDS_INPUT_RECORD_TIME
	tv_IDS_STOP_RECORD_1,		// tv_tv_IDS_STOP_RECORD
	tv_IDS_REICORD_FILE_LARGE_1,		// tv_tv_IDS_REICORD_FILE_LARGE
	tv_IDS_INVAILD_INPUT_1,		// tv_tv_IDS_INVAILD_INPUT
	tv_IDS_RECORD_END_1,		// tv_tv_IDS_RECORD_END
	tv_IDS_RECORD_NOT_CHANGE_CHANNEL_1,		// tv_tv_IDS_RECORD_NOT_CHANGE_CHANNEL
	tv_IDS_BAD_SIGNAL_SAVING_1,		// tv_tv_IDS_BAD_SIGNAL_SAVING
	tv_IDS_USB_REMOVED_1,		// tv_tv_IDS_USB_REMOVED
	tv_IDS_RECORD_TIME_OUT_1,		// tv_tv_IDS_RECORD_TIME_OUT
	tv_IDS_READ_DISK_INFO_1,		// tv_tv_IDS_READ_DISK_INFO
	tv_IDS_NONGLI_1,		// tv_tv_IDS_NONGLI
	tv_IDS_CALENDAR_MONDAY_1,		// tv_tv_IDS_CALENDAR_MONDAY
	tv_IDS_CALENDAR_TUESDAY_1,		// tv_tv_IDS_CALENDAR_TUESDAY
	tv_IDS_CALENDAR_WENDSDAY_1,		// tv_tv_IDS_CALENDAR_WENDSDAY
	tv_IDS_CALENDAR_THURSDAY_1,		// tv_tv_IDS_CALENDAR_THURSDAY
	tv_IDS_CALENDAR_FRIDAY_1,		// tv_tv_IDS_CALENDAR_FRIDAY
	tv_IDS_CALENDAR_SATURDAY_1,		// tv_tv_IDS_CALENDAR_SATURDAY
	tv_IDS_CALENDAR_SUNDAY_1,		// tv_tv_IDS_CALENDAR_SUNDAY
	tv_IDS_CALENDAR_SET_TIME_1,		// tv_tv_IDS_CALENDAR_SET_TIME
	tv_IDS_CALENDAR_SET_DATE_1,		// tv_tv_IDS_CALENDAR_SET_DATE
	tv_IDS_CALENDAR_YEAR_1,		// tv_tv_IDS_CALENDAR_YEAR
	tv_IDS_CALENDAR_MONTH_1,		// tv_tv_IDS_CALENDAR_MONTH
	tv_IDS_CALENDAR_DAY_1,		// tv_tv_IDS_CALENDAR_DAY
	tv_IDS_CALENDAR_HOUR_1,		// tv_tv_IDS_CALENDAR_HOUR
	tv_IDS_CALENDAR_MINUTE_1,		// tv_tv_IDS_CALENDAR_MINUTE
	tv_IDS_CALENDAR_SECONDS_1,		// tv_tv_IDS_CALENDAR_SECONDS
	tv_IDS_CALENDAR_ERR_YEAR_1,		// tv_tv_IDS_CALENDAR_ERR_YEAR
	tv_IDS_CALENDAR_ERR_MONTH_1,		// tv_tv_IDS_CALENDAR_ERR_MONTH
	tv_IDS_CALENDAR_ERR_DATE_1,		// tv_tv_IDS_CALENDAR_ERR_DATE
	tv_IDS_CALENDAR_ERR_TIME_1,		// tv_tv_IDS_CALENDAR_ERR_TIME
	tv_IDS_NEW_SOFTWARE_1,		// tv_tv_IDS_NEW_SOFTWARE
	tv_IDS_SW_UPDATE_1,		// tv_tv_IDS_SW_UPDATE
	tv_IDS_SW_UPDATE_MUST_1,		// tv_tv_IDS_SW_UPDATE_MUST
	tv_IDS_MANUAL_SCAN_1,		// tv_tv_IDS_MANUAL_SCAN
	tv_IDS_FREQUENCY_1,		// tv_tv_IDS_FREQUENCY
	tv_IDS_STRENGTH_1,		// tv_tv_IDS_STRENGTH
	tv_IDS_QUALITY_1,		// tv_tv_IDS_QUALITY
	tv_IDS_FIVE_SECOND_1,		// tv_tv_IDS_FIVE_SECOND
	tv_IDS_FIFTEEN_SECOND_1,		// tv_tv_IDS_FIFTEEN_SECOND
	tv_IDS_THIRTY_SECOND_1,		// tv_tv_IDS_THIRTY_SECOND
	tv_IDS_ONE_MINUTE_1,		// tv_tv_IDS_ONE_MINUTE
	tv_IDS_ALWAYS_EXIST_1,		// tv_tv_IDS_ALWAYS_EXIST
	tv_IDS_TIME_OF_CLOSE_SCREEN_1,		// tv_tv_IDS_TIME_OF_CLOSE_SCREEN
	tv_IDS_TEN_PERCENT_1,		// tv_tv_IDS_TEN_PERCENT
	tv_IDS_TWENTY_PERCENT_1,		// tv_tv_IDS_TWENTY_PERCENT
	tv_IDS_THIRTY_PRECENT_1,		// tv_tv_IDS_THIRTY_PRECENT
	tv_IDS_FORTY_PERCENT_1,		// tv_tv_IDS_FORTY_PERCENT
	tv_IDS_FIFTY_PERCEN_1,		// tv_tv_IDS_FIFTY_PERCEN
	tv_IDS_SIXTY_PERCENT_1,		// tv_tv_IDS_SIXTY_PERCENT
	tv_IDS_SEVENTY_PERCENT_1,		// tv_tv_IDS_SEVENTY_PERCENT
	tv_IDS_EIGHTY_PRECENT_1,		// tv_tv_IDS_EIGHTY_PRECENT
	tv_IDS_NINETY_PERCENT_1,		// tv_tv_IDS_NINETY_PERCENT
	tv_IDS_HUNDRED_PERCENT_1,		// tv_tv_IDS_HUNDRED_PERCENT
	tv_IDS_PLAY_FAILED_1,		// tv_tv_IDS_PLAY_FAILED
};

static PREFIXCONST char POSTCONST **_language_resource_entry[]={
	language_prefix_English, 
	language_prefix_Chinese, 
};


#define	LAN_COUNT	2
PREFIXCONST char* POSTCONST tv_LoadIdsRes(int ids, int lanid)
{
	if(ids>=tv_IDS_ENUM_MAX||ids<tv_LAN_ENUM_START||lanid<0||lanid>=LAN_COUNT)
		return NULL;
	ids-=tv_LAN_ENUM_START;
	return _language_resource_entry[lanid][ids];
}

