#ifndef __HTK_GTK_H__
#define __HTK_GTK_H__

#include <htk/htk.h>

G_BEGIN_DECLS

/* common.vala */
typedef HtkArrowType GtkArrowType;
#define GTK_ARROW_UP    HTK_ARROW_UP
#define GTK_ARROW_DOWN  HTK_ARROW_DOWN
#define GTK_ARROW_LEFT  HTK_ARROW_LEFT
#define GTK_ARROW_RIGHT HTK_ARROW_RIGHT
#define GTK_ARROW_NONE  HTK_ARROW_NONE
typedef HtkCellRendererState GtkCellRendererState;
#define GTK_CELL_RENDERER_SELECTED    HTK_CELL_RENDERER_SELECTED
#define GTK_CELL_RENDERER_PRELIT      HTK_CELL_RENDERER_PRELIT
#define GTK_CELL_RENDERER_INSENSITIVE HTK_CELL_RENDERER_INSENSITIVE
#define GTK_CELL_RENDERER_SORTED      HTK_CELL_RENDERER_SORTED
#define GTK_CELL_RENDERER_FOCUSED     HTK_CELL_RENDERER_FOCUSED
typedef HtkDeleteType GtkDeleteType;
#define GTK_DELETE_CHARS             HTK_DELETE_CHARS
#define GTK_DELETE_WORD_ENDS         HTK_DELETE_WORD_ENDS
#define GTK_DELETE_WORDS             HTK_DELETE_WORDS
#define GTK_DELETE_DISPLAY_LINES     HTK_DELETE_DISPLAY_LINES
#define GTK_DELETE_DISPLAY_LINE_ENDS HTK_DELETE_DISPLAY_LINE_ENDS
#define GTK_DELETE_PARAGRAPH_ENDS    HTK_DELETE_PARAGRAPH_ENDS
#define GTK_DELETE_PARAGRAPHS        HTK_DELETE_PARAGRAPHS
#define GTK_DELETE_WHITESPACE        HTK_DELETE_WHITESPACE
typedef HtkDirectionType GtkDirectionType;
#define GTK_DIR_TAB_FORWARD  HTK_DIR_TAB_FORWARD
#define GTK_DIR_TAB_BACKWARD HTK_DIR_TAB_BACKWARD
#define GTK_DIR_UP           HTK_DIR_UP
#define GTK_DIR_DOWN         HTK_DIR_DOWN
#define GTK_DIR_LEFT         HTK_DIR_LEFT
#define GTK_DIR_RIGHT        HTK_DIR_RIGHT
typedef HtkFileChooserAction GtkFileChooserAction;
#define GTK_FILE_CHOOSER_ACTION_OPEN          HTK_FILE_CHOOSER_ACTION_OPEN
#define GTK_FILE_CHOOSER_ACTION_SAVE          HTK_FILE_CHOOSER_ACTION_SAVE
#define GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER HTK_FILE_CHOOSER_ACTION_SELECT_FOLDER
#define GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER HTK_FILE_CHOOSER_ACTION_CREATE_FOLDER
typedef HtkIconSize GtkIconSize;
#define GTK_ICON_SIZE_INVALID       HTK_ICON_SIZE_INVALID
#define GTK_ICON_SIZE_MENU          HTK_ICON_SIZE_MENU
#define GTK_ICON_SIZE_SMALL_TOOLBAR HTK_ICON_SIZE_SMALL_TOOLBAR
#define GTK_ICON_SIZE_LARGE_TOOLBAR HTK_ICON_SIZE_LARGE_TOOLBAR
#define GTK_ICON_SIZE_BUTTON        HTK_ICON_SIZE_BUTTON
#define GTK_ICON_SIZE_DND           HTK_ICON_SIZE_DND
#define GTK_ICON_SIZE_DIALOG        HTK_ICON_SIZE_DIALOG
typedef HtkImageType GtkImageType;
#define GTK_IMAGE_EMPTY HTK_IMAGE_EMPTY
#define GTK_IMAGE_STOCK HTK_IMAGE_STOCK
typedef HtkJustification GtkJustification;
#define GTK_JUSTIFY_LEFT   HTK_JUSTIFY_LEFT
#define GTK_JUSTIFY_RIGHT  HTK_JUSTIFY_RIGHT
#define GTK_JUSTIFY_CENTER HTK_JUSTIFY_CENTER
#define GTK_JUSTIFY_FILL   HTK_JUSTIFY_FILL
typedef HtkMovementStep GtkMovementStep;
#define GTK_MOVEMENT_LOGICAL_POSITIONS HTK_MOVEMENT_LOGICAL_POSITIONS
#define GTK_MOVEMENT_VISUAL_POSITIONS  HTK_MOVEMENT_VISUAL_POSITIONS
#define GTK_MOVEMENT_WORDS             HTK_MOVEMENT_WORDS
#define GTK_MOVEMENT_DISPLAY_LINES     HTK_MOVEMENT_DISPLAY_LINES
#define GTK_MOVEMENT_DISPLAY_LINE_ENDS HTK_MOVEMENT_DISPLAY_LINE_ENDS
#define GTK_MOVEMENT_PARAGRAPHS        HTK_MOVEMENT_PARAGRAPHS
#define GTK_MOVEMENT_PARAGRAPH_ENDS    HTK_MOVEMENT_PARAGRAPH_ENDS
#define GTK_MOVEMENT_PAGES             HTK_MOVEMENT_PAGES
#define GTK_MOVEMENT_BUFFER_ENDS       HTK_MOVEMENT_BUFFER_ENDS
#define GTK_MOVEMENT_HORIZONTAL_PAGES  HTK_MOVEMENT_HORIZONTAL_PAGES
typedef HtkPackType GtkPackType;
#define GTK_PACK_START HTK_PACK_START
#define GTK_PACK_END   HTK_PACK_END
typedef HtkPolicyType GtkPolicyType;
#define GTK_POLICY_ALWAYS    HTK_POLICY_ALWAYS
#define GTK_POLICY_AUTOMATIC HTK_POLICY_AUTOMATIC
#define GTK_POLICY_NEVER     HTK_POLICY_NEVER
typedef HtkPositionType GtkPositionType;
#define GTK_POS_LEFT   HTK_POS_LEFT
#define GTK_POS_RIGHT  HTK_POS_RIGHT
#define GTK_POS_TOP    HTK_POS_TOP
#define GTK_POS_BOTTOM HTK_POS_BOTTON
typedef HtkScrollType GtkScrollType;
#define GTK_SCROLL_NONE          HTK_SCROLL_NONE
#define GTK_SCROLL_JUMP          HTK_SCROLL_JUMP
#define GTK_SCROLL_STEP_BACKWARD HTK_SCROLL_STEP_BACKWARD
#define GTK_SCROLL_STEP_FORWARD  HTK_SCROLL_STEP_FORWARD
#define GTK_SCROLL_PAGE_BACKWARD HTK_SCROLL_PAGE_BACKWARD
#define GTK_SCROLL_PAGE_FORWARD  HTK_SCROLL_PAGE_FORWARD
#define GTK_SCROLL_STEP_UP       HTK_SCROLL_STEP_UP
#define GTK_SCROLL_STEP_DOWN     HTK_SCROLL_STEP_DOWN
#define GTK_SCROLL_PAGE_UP       HTK_SCROLL_PAGE_UP
#define GTK_SCROLL_PAGE_DOWN     HTK_SCROLL_PAGE_DOWN
#define GTK_SCROLL_STEP_LEFT     HTK_SCROLL_STEP_LEFT
#define GTK_SCROLL_STEP_RIGHT    HTK_SCROLL_STEP_RIGHT
#define GTK_SCROLL_PAGE_LEFT     HTK_SCROLL_PAGE_LEFT
#define GTK_SCROLL_PAGE_RIGHT    HTK_SCROLL_PAGE_RIGHT
#define GTK_SCROLL_START         HTK_SCROLL_START
#define GTK_SCROLL_END           HTK_SCROLL_END
typedef HtkSelectionMode GtkSelectionMode;
#define GTK_SELECTION_NONE HTK_SELECTION_NONE
#define GTK_SELECTION_SINGLE HTK_SELECTION_SINGLE
#define GTK_SELECTION_BROWSE HTK_SELECTION_BROWSE
#define GTK_SELECTION_MULTIPLE HTK_SELECTION_MULTIPLE
#define GTK_SELECTION_EXTENDED HTK_SELECTION_EXTENDED
typedef HtkShadowType GtkShadowType;
#define GTK_SHADOW_NONE       HTK_SHADOW_NONE
#define GTK_SHADOW_IN         HTK_SHADOW_IN
#define GTK_SHADOW_OUT        HTK_SHADOW_OUT
#define GTK_SHADOW_ETCHED_IN  HTK_SHADOW_ETCHED_IN
#define GTK_SHADOW_ETCHED_OUT HTK_SHADOW_ETCHED_OUT
typedef HtkStateType GtkStateType;
#define GTK_STATE_NORMAL      HTK_STATE_NORMAL
#define GTK_STATE_ACTIVE      HTK_STATE_ACTIVE
#define GTK_STATE_PRELIGHT    HTK_STATE_PRELIGHT
#define GTK_STATE_SELECTED    HTK_STATE_SELECTED
#define GTK_STATE_INSENSITIVE HTK_STATE_INSENSITIVE
typedef HtkTextDirection GtkTextDirection;
#define GTK_TEXT_DIR_NONE HTK_TEXT_DIR_NONE
#define GTK_TEXT_DIR_LTR  HTK_TEXT_DIR_LTR
#define GTK_TEXT_DIR_RTL  HTK_TEXT_DIR_RTL
typedef HtkTreeViewGridLines GtkTreeViewGridLines;
#define GTK_TREE_VIEW_GRID_LINES_NONE       HTK_TREE_VIEW_GRID_LINES_NONE
#define GTK_TREE_VIEW_GRID_LINES_HORIZONTAL HTK_TREE_VIEW_GRID_LINES_HORIZONTAL
#define GTK_TREE_VIEW_GRID_LINES_VERTICAL   HTK_TREE_VIEW_GRID_LINES_VERTICAL
#define GTK_TREE_VIEW_GRID_LINES_BOTH       HTK_TREE_VIEW_GRID_LINES_BOTH
typedef HtkOrientation GtkOrientation;
#define GTK_ORIENTATION_HORIZONTAL HTK_ORIENTATION_HORIZONTAL
#define GTK_ORIENTATION_VERTICAL   HTK_ORIENTATION_VERTICAL
typedef HtkWindowPosition GtkWindowPosition;
#define GTK_WIN_POS_NONE             HTK_WIN_POS_NONE
#define GTK_WIN_POS_CENTER           HTK_WIN_POS_CENTER
#define GTK_WIN_POS_MOUSE            HTK_WIN_POS_MOUSE
#define GTK_WIN_POS_CENTER_ALWAYS    HTK_WIN_POS_CENTER_ALWAYS
#define GTK_WIN_POS_CENTER_ON_PARENT HTK_WIN_POS_CENTER_ON_PARENT
typedef HtkWindowType GtkWindowType;
#define GTK_WINDOW_TOPLEVEL HTK_WINDOW_TOPLEVEL
#define GTK_WINDOW_POPUP    HTK_WINDOW_POPUP

/* common.vala */
typedef HtkAllocation GtkAllocation;
typedef HtkRequisition GtkRequisition;
/* htk/stock.vala */
typedef HtkStockItem GtkStockItem;

/* common.vala */
typedef HtkCallback GtkCallback;
typedef HtkKeySnoopFunc GtkKeySnoopFunc;
typedef HtkMenuPositionFunc GtkMenuPositionFunc;

/* hdk/window-*.vala */
#define gtk_init htk_init
#define gtk_main htk_main
#define gtk_main_quit htk_main_quit

/* htk/arrow.vala */
typedef HtkArrow GtkArrow;
typedef HtkArrowClass GtkArrowClass;
#define GTK_ARROW HTK_ARROW
#define GTK_ARROW_CLASS HTK_ARROW_CLASS
#define GTK_ARROW_GET_CLASS HTK_ARROW_GET_CLASS
#define GTK_IS_ARROW HTK_IS_ARROW
#define GTK_IS_ARROW_CLASS HTK_IS_ARROW_CLASS
#define GTK_TYPE_ARROW HTK_TYPE_ARROW
#define gtk_arrow_get_type htk_arrow_get_type
#define gtk_arrow_new htk_arrow_new
#define gtk_arrow_set htk_arrow_set

/* htk/adjustment.vala */
typedef HtkAdjustment GtkAdjustment;
typedef HtkAdjustmentClass GtkAdjustmentClass;
#define GTK_ADJUSTMENT HTK_ADJUSTMENT
#define GTK_IS_ADJUSTMENT HTK_IS_ADJUSTMENT
#define gtk_adjustment_get_lower htk_adjustment_get_lower
#define gtk_adjustment_get_page_increment htk_adjustment_get_page_increment
#define gtk_adjustment_get_page_size htk_adjustment_get_page_size
#define gtk_adjustment_get_step_increment htk_adjustment_get_step_increment
#define gtk_adjustment_get_type htk_adjustment_get_type
#define gtk_adjustment_get_upper htk_adjustment_get_upper
#define gtk_adjustment_get_value htk_adjustment_get_value
#define gtk_adjustment_new htk_adjustment_new
#define gtk_adjustment_set_lower htk_adjustment_set_lower
#define gtk_adjustment_set_page_increment htk_adjustment_set_page_increment
#define gtk_adjustment_set_page_size htk_adjustment_set_page_size
#define gtk_adjustment_set_step_increment htk_adjustment_set_step_increment
#define gtk_adjustment_set_upper htk_adjustment_set_upper
#define gtk_adjustment_set_value htk_adjustment_set_value

/* htk/bin.vala */
typedef HtkBin GtkBin;
typedef HtkBinClass GtkBinClass;
#define GTK_BIN HTK_BIN
#define GTK_IS_BIN HTK_IS_BIN
#define gtk_bin_get_child htk_bin_get_child
#define gtk_bin_get_type htk_bin_get_type

/* htk/box.vala */
typedef HtkBox GtkBox;
typedef HtkBoxClass GtkBoxClass;
typedef HtkBoxChild GtkBoxChild;
#define GTK_BOX HTK_BOX
#define GTK_IS_BOX HTK_IS_BOX
#define gtk_box_get_type htk_box_get_type
#define gtk_box_pack_start htk_box_pack_start

/* htk/button.vala */
typedef HtkButton GtkButton;
typedef HtkButtonClass GtkButtonClass;
#define GTK_BUTTON HTK_BUTTON
#define GTK_IS_BUTTON HTK_IS_BUTTON
#define gtk_button_clicked htk_button_clicked
#define gtk_button_get_image htk_button_get_image
#define gtk_button_get_image_position htk_button_get_image_position
#define gtk_button_get_label htk_button_get_label
#define gtk_button_get_type htk_button_get_type
#define gtk_button_new htk_button_new
#define gtk_button_new_with_label htk_button_new_with_label
#define gtk_button_set_image htk_button_set_image
#define gtk_button_set_image_position htk_button_set_image_position
#define gtk_button_set_label htk_button_set_label

/* htk/cell-layout.vala */
typedef HtkCellLayout GtkCellLayout;
typedef HtkCellLayoutIface GtkCellLayoutIface;
#define GTK_CELL_LAYOUT HTK_CELL_LAYOUT
#define GTK_IS_CELL_LAYOUT HTK_IS_CELL_LAYOUT
#define GTK_TYPE_CELL_LAYOUT HTK_TYPE_CELL_LAYOUT
#define GTK_CELL_LAYOUT_GET_IFACE HTK_CELL_LAYOUT_GET_IFACE
#define gtk_cell_layout_add_attribute htk_cell_layout_add_attribute
#define gtk_cell_layout_clear htk_cell_layout_clear
#define gtk_cell_layout_clear_attributes htk_cell_layout_clear_attributes
#define gtk_cell_layout_get_cells htk_cell_layout_get_cells
#define gtk_cell_layout_get_type htk_cell_layout_get_type
#define gtk_cell_layout_pack_end htk_cell_layout_pack_end
#define gtk_cell_layout_pack_start htk_cell_layout_pack_start
#define gtk_cell_layout_set_attributes htk_cell_layout_set_attributes

/* htk/cell-renderer.vala */
typedef HtkCellRenderer GtkCellRenderer;
typedef HtkCellRendererClass GtkCellRendererClass;
#define GTK_CELL_RENDERER HTK_CELL_RENDERER
#define GTK_CELL_RENDERER_CLASS HTK_CELL_RENDERER_CLASS
#define GTK_CELL_RENDERER_GET_CLASS HTK_CELL_RENDERER_GET_CLASS
#define GTK_IS_CELL_RENDERER HTK_IS_CELL_RENDERER
#define GTK_IS_CELL_RENDERER_CLASS HTK_IS_CELL_RENDERER_CLASS
#define GTK_TYPE_CELL_RENDERER HTK_TYPE_CELL_RENDERER
#define gtk_cell_renderer_activate htk_cell_renderer_activate
#define gtk_cell_renderer_get_alignment htk_cell_renderer_get_alignment
#define gtk_cell_renderer_get_fixed_size htk_cell_renderer_get_fixed_size
#define gtk_cell_renderer_get_padding htk_cell_renderer_get_padding
#define gtk_cell_renderer_get_size htk_cell_renderer_get_size
#define gtk_cell_renderer_get_type htk_cell_renderer_get_type
#define gtk_cell_renderer_get_visible htk_cell_renderer_get_visible
#define gtk_cell_renderer_render htk_cell_renderer_render
#define gtk_cell_renderer_set_alignment htk_cell_renderer_set_alignment
#define gtk_cell_renderer_set_fixed_size htk_cell_renderer_set_fixed_size
#define gtk_cell_renderer_set_padding htk_cell_renderer_set_padding
#define gtk_cell_renderer_set_visible htk_cell_renderer_set_visible

/* htk/cell-renderer-pixbuf.vala */
typedef HtkCellRendererPixbuf GtkCellRendererPixbuf;
typedef HtkCellRendererPixbufClass GtkCellRendererPixbufClass;
#define GTK_CELL_RENDERER_PIXBUF HTK_CELL_RENDERER_PIXBUF
#define GTK_CELL_RENDERER_PIXBUF_CLASS HTK_CELL_RENDERER_PIXBUF_CLASS
#define GTK_CELL_RENDERER_PIXBUF_GET_CLASS HTK_CELL_RENDERER_PIXBUF_GET_CLASS
#define GTK_IS_CELL_RENDERER_PIXBUF HTK_IS_CELL_RENDERER_PIXBUF
#define GTK_IS_CELL_RENDERER_PIXBUF_CLASS HTK_IS_CELL_RENDERER_PIXBUF_CLASS
#define GTK_TYPE_CELL_RENDERER_PIXBUF HTK_TYPE_CELL_RENDERER_PIXBUF
#define gtk_cell_renderer_pixbuf_get_type htk_cell_renderer_pixbuf_get_type
#define gtk_cell_renderer_pixbuf_new htk_cell_renderer_pixbuf_new

/* htk/cell-renderer-text.vala */
typedef HtkCellRendererText GtkCellRendererText;
typedef HtkCellRendererTextClass GtkCellRendererTextClass;
#define GTK_CELL_RENDERER_TEXT HTK_CELL_RENDERER_TEXT
#define GTK_CELL_RENDERER_TEXT_CLASS HTK_CELL_RENDERER_TEXT_CLASS
#define GTK_CELL_RENDERER_TEXT_GET_CLASS HTK_CELL_RENDERER_TEXT_GET_CLASS
#define GTK_IS_CELL_RENDERER_TEXT HTK_IS_CELL_RENDERER_TEXT
#define GTK_IS_CELL_RENDERER_TEXT_CLASS HTK_IS_CELL_RENDERER_TEXT_CLASS
#define GTK_TYPE_CELL_RENDERER_TEXT HTK_TYPE_CELL_RENDERER_TEXT
#define gtk_cell_renderer_text_get_type htk_cell_renderer_text_get_type
#define gtk_cell_renderer_text_new htk_cell_renderer_text_new

/* htk/cell-view.vala */
typedef HtkCellView GtkCellView;
typedef HtkCellViewClass GtkCellViewClass;
#define GTK_CELL_VIEW HTK_CELL_VIEW
#define GTK_CELL_VIEW_CLASS HTK_CELL_VIEW_CLASS
#define GTK_CELL_VIEW_GET_CLASS HTK_CELL_VIEW_GET_CLASS
#define GTK_IS_CELL_VIEW HTK_IS_CELL_VIEW
#define GTK_IS_CELL_VIEW_CLASS HTK_IS_CELL_VIEW_CLASS
#define GTK_TYPE_CELL_VIEW HTK_TYPE_CELL_VIEW
#define gtk_cell_view_get_displayed_row htk_cell_view_get_displayed_row
#define gtk_cell_view_get_model htk_cell_view_get_model
#define gtk_cell_view_get_size_of_row htk_cell_view_get_size_of_row
#define gtk_cell_view_get_type htk_cell_view_get_type
#define gtk_cell_view_new htk_cell_view_new
#define gtk_cell_view_set_displayed_row htk_cell_view_set_displayed_row
#define gtk_cell_view_set_model htk_cell_view_set_model

/* htk/checkbutton.vala */
typedef HtkCheckButton GtkCheckButton;
typedef HtkCheckButtonClass GtkCheckButtonClass;
#define GTK_CHECK_BUTTON HTK_CHECK_BUTTON
#define GTK_IS_CHECK_BUTTON HTK_IS_CHECK_BUTTON
#define gtk_check_button_get_type htk_check_button_get_type
#define gtk_check_button_new htk_check_button_new
#define gtk_check_button_new_with_label htk_check_button_new_with_label

/* htk/clist.vala */
typedef HtkCList GtkCList;
typedef HtkCListClass GtkCListClass;
#define GTK_CLIST HTK_CLIST
#define GTK_IS_CLIST HTK_IS_CLIST
#define gtk_clist_append htk_clist_append
#define gtk_clist_clear htk_clist_clear
#define gtk_clist_column_titles_hide htk_clist_column_titles_hide
#define gtk_clist_column_titles_show htk_clist_column_titles_show
#define gtk_clist_get_row_data htk_clist_get_row_data
#define gtk_clist_get_text htk_clist_get_text
#define gtk_clist_get_type htk_clist_get_type
#define gtk_clist_insert htk_clist_insert
#define gtk_clist_new htk_clist_new
#define gtk_clist_prepend htk_clist_prepend
#define gtk_clist_remove htk_clist_remove
#define gtk_clist_select_row htk_clist_select_row
#define gtk_clist_set_column_auto_resize htk_clist_set_column_auto_resize
#define gtk_clist_set_column_title htk_clist_set_column_title
#define gtk_clist_set_column_width htk_clist_set_column_width
#define gtk_clist_set_row_data htk_clist_set_row_data
#define gtk_clist_set_row_height htk_clist_set_row_height
#define gtk_clist_set_selection_mode htk_clist_set_selection_mode
#define gtk_clist_set_text htk_clist_set_text
#define gtk_clist_unselect_row htk_clist_unselect_row

/* htk/combo-box.vala */
typedef HtkComboBox GtkComboBox;
typedef HtkComboBoxClass GtkComboBoxClass;
#define GTK_COMBO_BOX HTK_COMBO_BOX
#define GTK_IS_COMBO_BOX HTK_IS_COMBO_BOX
#define gtk_combo_box_append_text htk_combo_box_append_text
#define gtk_combo_box_get_active htk_combo_box_get_active
#define gtk_combo_box_get_active_text htk_combo_box_get_active_text
#define gtk_combo_box_get_type htk_combo_box_get_type
#define gtk_combo_box_insert_text htk_combo_box_insert_text
#define gtk_combo_box_new_text htk_combo_box_new_text
#define gtk_combo_box_popdown htk_combo_box_popdown
#define gtk_combo_box_popup htk_combo_box_popup
#define gtk_combo_box_prepend_text htk_combo_box_prepend_text
#define gtk_combo_box_remove_text htk_combo_box_remove_text
#define gtk_combo_box_set_active htk_combo_box_set_active

/* htk/container.vala */
typedef HtkContainer GtkContainer;
typedef HtkContainerClass GtkContainerClass;
#define GTK_CONTAINER HTK_CONTAINER
#define GTK_IS_CONTAINER HTK_IS_CONTAINER
#define gtk_container_add htk_container_add
#define gtk_container_forall htk_container_forall
#define gtk_container_foreach htk_container_foreach
#define gtk_container_get_children htk_container_get_children
#define gtk_container_get_type htk_container_get_type
#define gtk_container_remove htk_container_remove
#define gtk_container_set_focus_child htk_container_set_focus_child

/* htk/drawing-area.vala */
typedef HtkDrawingArea GtkDrawingArea;
typedef HtkDrawingAreaClass GtkDrawingAreaClass;
#define GTK_DRAWING_AREA HTK_DRAWING_AREA
#define GTK_IS_DRAWING_AREA HTK_IS_DRAWING_AREA
#define gtk_drawing_area_get_type htk_drawing_area_get_type
#define gtk_drawing_area_new htk_drawing_area_new

/* htk/entry.vala */
typedef HtkEntry GtkEntry;
typedef HtkEntryClass GtkEntryClass;
#define GTK_ENTRY HTK_ENTRY
#define GTK_IS_ENTRY HTK_IS_ENTRY
#define gtk_entry_append_text htk_entry_append_text
#define gtk_entry_get_layout htk_entry_get_layout
#define gtk_entry_get_text htk_entry_get_text
#define gtk_entry_get_text_length htk_entry_get_text_length
#define gtk_entry_get_type htk_entry_get_type
#define gtk_entry_new htk_entry_new
#define gtk_entry_prepend_text htk_entry_prepend_text
#define gtk_entry_set_position htk_entry_set_position
#define gtk_entry_set_text htk_entry_set_text

/* htk/filechooser.vala */
typedef HtkFileChooser GtkFileChooser;
#define GTK_FILE_CHOOSER HTK_FILE_CHOOSER
#define GTK_IS_FILE_CHOOSER HTK_IS_FILE_CHOOSER
#define gtk_file_chooser_get_action htk_file_chooser_get_action
#define gtk_file_chooser_get_file htk_file_chooser_get_file
#define gtk_file_chooser_get_filename htk_file_chooser_get_filename
#define gtk_file_chooser_get_filenames htk_file_chooser_get_filenames
#define gtk_file_chooser_get_select_multiple htk_file_chooser_get_select_multiple
#define gtk_file_chooser_get_uri htk_file_chooser_get_uri
#define gtk_file_chooser_select_all htk_file_chooser_select_all
#define gtk_file_chooser_select_filename htk_file_chooser_select_filename
#define gtk_file_chooser_set_action htk_file_chooser_set_action
#define gtk_file_chooser_set_select_multiple htk_file_chooser_set_select_multiple
#define gtk_file_chooser_set_uri htk_file_chooser_set_uri
#define gtk_file_chooser_unselect_all htk_file_chooser_unselect_all
#define gtk_file_chooser_unselect_filename htk_file_chooser_unselect_filename

/* htk/filechooserdialog.vala */
typedef HtkFileChooserDialog GtkFileChooserDialog;
typedef HtkFileChooserDialogClass GtkFileChooserDialogClass;
#define GTK_FILE_CHOOSER_DIALOG HTK_FILE_CHOOSER_DIALOG
#define GTK_IS_FILE_CHOOSER_DIALOG HTK_IS_FILE_CHOOSER_DIALOG
#define gtk_file_chooser_dialog_new htk_file_chooser_dialog_new

/* htk/filechooserwidget.vala */
typedef HtkFileChooserWidget GtkFileChooserWidget;
typedef HtkFileChooserWidgetClass GtkFileChooserWidgetClass;
#define GTK_FILE_CHOOSER_WIDGET HTK_FILE_CHOOSER_WIDGET
#define GTK_IS_FILE_CHOOSER_WIDGET HTK_IS_FILE_CHOOSER_WIDGET
#define gtk_file_chooser_widget_new htk_file_chooser_widget_new

/* htk/fixed.vala */
typedef HtkFixed GtkFixed;
typedef HtkFixedClass GtkFixedClass;
#define GTK_FIXED HTK_FIXED
#define GTK_FIXED_CLASS HTK_FIXED_CLASS
#define GTK_FIXED_GET_CLASS HTK_FIXED_GET_CLASS
#define GTK_IS_FIXED HTK_IS_FIXED
#define GTK_IS_FIXED_CLASS HTK_IS_FIXED_CLASS
#define GTK_TYPE_FIXED HTK_TYPE_FIXED
#define gtk_fixed_get_type htk_fixed_get_type
#define gtk_fixed_move htk_fixed_move
#define gtk_fixed_new htk_fixed_new
#define gtk_fixed_put htk_fixed_put

/* htk/hbox.vala */
typedef HtkHBox GtkHBox;
typedef HtkHBoxClass GtkHBoxClass;
#define GTK_HBOX HTK_HBOX
#define GTK_IS_HBOX HTK_IS_HBOX
#define gtk_hbox_get_type htk_hbox_get_type
#define gtk_hbox_new htk_hbox_new

/* htk/hpaned.vala */
typedef HtkHPaned GtkHPaned;
typedef HtkHPanedClass GtkHPanedClass;
#define GTK_HPANED HTK_HPANED
#define GTK_IS_HPANED HTK_IS_HPANED
#define gtk_hpaned_get_type htk_hpaned_get_type
#define gtk_hpaned_new htk_hpaned_new

/* htk/hscale.vala */
typedef HtkHScale GtkHScale;
typedef HtkHScaleClass GtkHScaleClass;
#define GTK_HSCALE HTK_HSCALE
#define GTK_IS_HSCALE HTK_IS_HSCALE
#define gtk_hscale_get_type htk_hscale_get_type
#define gtk_hscale_new htk_hscale_new

/* htk/hscrollbar.vala */
typedef HtkHScrollbar GtkHScrollbar;
typedef HtkHScrollbarClass GtkHScrollbarClass;
#define GTK_HSCROLLBAR HTK_HSCROLLBAR
#define GTK_IS_HSCROLLBAR HTK_IS_HSCROLLBAR
#define gtk_hscrollbar_get_type htk_hscrollbar_get_type
#define gtk_hscrollbar_new htk_hscrollbar_new

/* htk/hseparator.vala */
typedef HtkHSeparator GtkHSeparator;
typedef HtkHSeparatorClass GtkHSeparatorClass;
#define GTK_HSEPARATOR HTK_HSEPARATOR
#define GTK_IS_HSEPARATOR HTK_IS_HSEPARATOR
#define gtk_hseparator_get_type htk_hseparator_get_type
#define gtk_hseparator_new htk_hseparator_new

/* htk/icon.vala */
typedef HtkIconFactory GtkIconFactory;
typedef HtkIconSet GtkIconSet;
typedef HtkIconSource GtkIconSource;
#define GTK_ICON HTK_ICON
#define GTK_IS_ICON HTK_IS_ICON
#define gtk_icon_factory_get_type htk_icon_factory_get_type
#define gtk_icon_factory_lookup htk_icon_factory_lookup
#define gtk_icon_factory_lookup_default htk_icon_factory_lookup_default
#define gtk_icon_factory_new htk_icon_factory_new
#define gtk_icon_set_get_type htk_icon_set_get_type
#define gtk_icon_set_new htk_icon_set_new
#define gtk_icon_set_render_icon htk_icon_set_render_icon
#define gtk_icon_source_get_type htk_icon_source_get_type
#define gtk_icon_source_new htk_icon_source_new

/* htk/icon-view.vala */
typedef HtkIconView GtkIconView;
typedef HtkIconViewClass GtkIconViewClass;
#define GTK_ICON_VIEW HTK_ICON_VIEW
#define GTK_ICON_VIEW_CLASS HTK_ICON_VIEW_CLASS
#define GTK_ICON_VIEW_GET_CLASS HTK_ICON_VIEW_GET_CLASS
#define GTK_IS_ICON_VIEW HTK_IS_ICON_VIEW
#define GTK_IS_ICON_VIEW_CLASS HTK_IS_ICON_VIEW_CLASS
#define GTK_TYPE_ICON_VIEW HTK_TYPE_ICON_VIEW
#define gtk_icon_view_get_item_orientation htk_icon_view_get_item_orientation
#define gtk_icon_view_get_model htk_icon_view_get_model
#define gtk_icon_view_new htk_icon_view_new
#define gtk_icon_view_new_with_model htk_icon_view_new_with_model
#define gtk_icon_view_set_item_orientation htk_icon_view_set_item_orientation
#define gtk_icon_view_set_model htk_icon_view_set_model

/* htk/im-context.vala */
typedef HtkIMContext GtkIMContext;
typedef HtkIMContextClass GtkIMContextClass;
#define GTK_IM_CONTEXT HTK_IM_CONTEXT
#define GTK_IS_IM_CONTEXT HTK_IS_IM_CONTEXT
#define GTK_IM_CONTEXT_CLASS HTK_IM_CONTEXT_CLASS
#define gtk_im_context_delete_surrounding htk_im_context_delete_surrounding
#define gtk_im_context_filter_keypress htk_im_context_filter_keypress
#define gtk_im_context_focus_in htk_im_context_focus_in
#define gtk_im_context_focus_out htk_im_context_focus_out
#define gtk_im_context_get_preedit_string htk_im_context_get_preedit_string
#define gtk_im_context_get_surrounding htk_im_context_get_surrounding
#define gtk_im_context_get_type htk_im_context_get_type
#define gtk_im_context_reset htk_im_context_reset
#define gtk_im_context_set_client_window htk_im_context_set_client_window
#define gtk_im_context_set_cursor_location htk_im_context_set_cursor_location
#define gtk_im_context_set_surrounding htk_im_context_set_surrounding
#define gtk_im_context_set_use_preedit htk_im_context_set_use_preedit

/* htk/image.vala */
typedef HtkImage GtkImage;
typedef HtkImageClass GtkImageClass;
#define GTK_IMAGE HTK_IMAGE
#define GTK_IS_IMAGE HTK_IS_IMAGE
#define gtk_image_clear htk_image_clear
#define gtk_image_get_type htk_image_get_type
#define gtk_image_new htk_image_new
#define gtk_image_new_from_file htk_image_new_from_file
#define gtk_image_new_from_stock htk_image_new_from_stock
#define gtk_image_set_from_file htk_image_set_from_file
#define gtk_image_set_from_stock htk_image_set_from_stock

/* htk/item.vala */
typedef HtkItem GtkItem;
typedef HtkItemClass GtkItemClass;
#define GTK_ITEM HTK_ITEM
#define GTK_IS_ITEM HTK_IS_ITEM
#define gtk_item_deselect htk_item_deselect
#define gtk_item_get_type htk_item_get_type
#define gtk_item_select htk_item_select
#define gtk_item_toggle htk_item_toggle

/* htk/label.vala */
typedef HtkLabel GtkLabel;
typedef HtkLabelClass GtkLabelClass;
#define GTK_LABEL HTK_LABEL
#define GTK_IS_LABEL HTK_IS_LABEL
#define gtk_label_get_layout htk_label_get_layout
#define gtk_label_get_text htk_label_get_text
#define gtk_label_get_type htk_label_get_type
#define gtk_label_new htk_label_new
#define gtk_label_set_text htk_label_set_text

/* htk/list-store.vala */
typedef HtkListStore GtkListStore;
typedef HtkListStoreClass GtkListStoreClass;
#define GTK_LIST_STORE HTK_LIST_STORE
#define GTK_LIST_STORE_CLASS HTK_LIST_STORE_CLASS
#define GTK_LIST_STORE_GET_CLASS HTK_LIST_STORE_GET_CLASS
#define GTK_IS_LIST_STORE HTK_IS_LIST_STORE
#define GTK_IS_LIST_STORE_CLASS HTK_IS_LIST_STORE_CLASS
#define GTK_TYPE_LIST_STORE HTK_TYPE_LIST_STORE
#define gtk_list_store_append htk_list_store_append
#define gtk_list_store_clear htk_list_store_clear
#define gtk_list_store_get_type htk_list_store_get_type
#define gtk_list_store_insert htk_list_store_insert
#define gtk_list_store_insert_after htk_list_store_insert_after
#define gtk_list_store_insert_before htk_list_store_insert_before
#define gtk_list_store_iter_is_valid htk_list_store_iter_is_valid
#define gtk_list_store_new htk_list_store_new
#define gtk_list_store_newv htk_list_store_newv
#define gtk_list_store_prepend htk_list_store_prepend
#define gtk_list_store_remove htk_list_store_remove
#define gtk_list_store_set htk_list_store_set
#define gtk_list_store_set_column_types htk_list_store_set_column_types
#define gtk_list_store_set_valist htk_list_store_set_valist
#define gtk_list_store_set_value htk_list_store_set_value

/* htk/menu.vala */
typedef HtkMenu GtkMenu;
typedef HtkMenuClass GtkMenuClass;
#define GTK_MENU HTK_MENU
#define GTK_IS_MENU HTK_IS_MENU
#define GTK_TYPE_IM_CONTEXT HTK_TYPE_IM_CONTEXT
#define gtk_menu_get_type htk_menu_get_type
#define gtk_menu_new htk_menu_new
#define gtk_menu_popdown htk_menu_popdown
#define gtk_menu_popup htk_menu_popup
#define gtk_menu_set_title htk_menu_set_title

/* htk/menu-item.vala */
typedef HtkMenuItem GtkMenuItem;
typedef HtkMenuItemClass GtkMenuItemClass;
#define GTK_MENU_ITEM HTK_MENU_ITEM
#define GTK_IS_MENU_ITEM HTK_IS_MENU_ITEM
#define gtk_menu_item_activate htk_menu_item_activate
#define gtk_menu_item_get_label htk_menu_item_get_label
#define gtk_menu_item_get_submenu htk_menu_item_get_submenu
#define gtk_menu_item_get_type htk_menu_item_get_type
#define gtk_menu_item_new htk_menu_item_new
#define gtk_menu_item_new_with_label htk_menu_item_new_with_label
#define gtk_menu_item_set_label htk_menu_item_set_label
#define gtk_menu_item_set_submenu htk_menu_item_set_submenu

/* htk/menu-shell.vala */
typedef HtkMenuShell GtkMenuShell;
typedef HtkMenuShellClass GtkMenuShellClass;
#define GTK_MENU_SHELL HTK_MENU_SHELL
#define GTK_IS_MENU_SHELL HTK_IS_MENU_SHELL
#define gtk_menu_shell_activate_item htk_menu_shell_activate_item
#define gtk_menu_shell_append htk_menu_shell_append
#define gtk_menu_shell_get_type htk_menu_shell_get_type
#define gtk_menu_shell_insert htk_menu_shell_insert
#define gtk_menu_shell_prepend htk_menu_shell_prepend

/* htk/misc.vala */
typedef HtkMisc GtkMisc;
typedef HtkMiscClass GtkMiscClass;
#define GTK_MISC HTK_MISC
#define GTK_IS_MISC HTK_IS_MISC
#define gtk_misc_get_alignment htk_misc_get_alignment
#define gtk_misc_get_padding htk_misc_get_padding
#define gtk_misc_get_type htk_misc_get_type
#define gtk_misc_set_alignment htk_misc_set_alignment
#define gtk_misc_set_padding htk_misc_set_padding

/* htk/notebook.vala */
typedef HtkNotebook GtkNotebook;
typedef HtkNotebookClass GtkNotebookClass;
typedef HtkNotebookPage GtkNotebookPage;
#define GTK_NOTEBOOK HTK_NOTEBOOK
#define GTK_IS_NOTEBOOK HTK_IS_NOTEBOOK
#define gtk_notebook_append_page htk_notebook_append_page
#define gtk_notebook_get_current_page htk_notebook_get_current_page
#define gtk_notebook_get_n_pages htk_notebook_get_n_pages
#define gtk_notebook_get_nth_page htk_notebook_get_nth_page
#define gtk_notebook_get_type htk_notebook_get_type
#define gtk_notebook_new htk_notebook_new
#define gtk_notebook_next_page htk_notebook_next_page
#define gtk_notebook_page_num htk_notebook_page_num
#define gtk_notebook_prev_page htk_notebook_prev_page
#define gtk_notebook_remove_page htk_notebook_remove_page
#define gtk_notebook_set_current_page htk_notebook_set_current_page

/* htk/object.vala */
typedef HtkObject GtkObject;
#define GTK_OBJECT HTK_OBJECT
#define GTK_IS_OBJECT HTK_IS_OBJECT
#define gtk_object_get_type htk_object_get_type

/* htk/paned.vala */
typedef HtkPaned GtkPaned;
typedef HtkPanedClass GtkPanedClass;
#define GTK_PANED HTK_PANED
#define GTK_IS_PANED HTK_IS_PANED
#define gtk_paned_add1 htk_paned_add1
#define gtk_paned_add2 htk_paned_add2
#define gtk_paned_get_child1 htk_paned_get_child1
#define gtk_paned_get_child2 htk_paned_get_child2
#define gtk_paned_get_type htk_paned_get_type
#define gtk_paned_pack1 htk_paned_pack1
#define gtk_paned_pack2 htk_paned_pack2

/* htk/progress.vala */
typedef HtkProgress GtkProgress;
typedef HtkProgressClass GtkProgressClass;
#define GTK_PROGRESS HTK_PROGRESS
#define GTK_IS_PROGRESS HTK_IS_PROGRESS
#define gtk_progress_get_current_percentage htk_progress_get_current_percentage
#define gtk_progress_get_type htk_progress_get_type
#define gtk_progress_set_format_string htk_progress_set_format_string
#define gtk_progress_set_percentage htk_progress_set_percentage
#define gtk_progress_set_show_text htk_progress_set_show_text

/* htk/progressbar.vala */
typedef HtkProgressBar GtkProgressBar;
typedef HtkProgressBarClass GtkProgressBarClass;
#define GTK_PROGRESS_BAR HTK_PROGRESS_BAR
#define GTK_IS_PROGRESS_BAR HTK_IS_PROGRESS_BAR
#define gtk_progress_bar_get_fraction htk_progress_bar_get_fraction
#define gtk_progress_bar_get_text htk_progress_bar_get_text
#define gtk_progress_bar_get_type htk_progress_bar_get_type
#define gtk_progress_bar_new htk_progress_bar_new
#define gtk_progress_bar_set_fraction htk_progress_bar_set_fraction
#define gtk_progress_bar_set_text htk_progress_bar_set_text

/* htk/radiobutton.vala */
typedef HtkRadioButton GtkRadioButton;
typedef HtkRadioButtonClass GtkRadioButtonClass;
#define GTK_RADIO HTK_RADIO
#define GTK_IS_RADIO HTK_IS_RADIO
#define gtk_radio_button_get_type htk_radio_button_get_type
#define gtk_radio_button_new htk_radio_button_new
#define gtk_radio_button_new_with_label htk_radio_button_new_with_label

/* htk/range.vala */
typedef HtkRange GtkRange;
typedef HtkRangeClass GtkRangeClass;
#define GTK_RANGE HTK_RANGE
#define GTK_IS_RANGE HTK_IS_RANGE
#define gtk_range_get_adjustment htk_range_get_adjustment
#define gtk_range_get_type htk_range_get_type
#define gtk_range_set_adjustment htk_range_set_adjustment

/* htk/scale.vala */
typedef HtkScale GtkScale;
typedef HtkScaleClass GtkScaleClass;
#define GTK_SCALE HTK_SCALE
#define GTK_IS_SCALE HTK_IS_SCALE
#define gtk_scale_get_type htk_scale_get_type
#define gtk_scale_new htk_scale_new

/* htk/scrollbar.vala */
typedef HtkScrollbar GtkScrollbar;
typedef HtkScrollbarClass GtkScrollbarClass;
#define GTK_SCROLLBAR HTK_SCROLLBAR
#define GTK_IS_SCROLLBAR HTK_IS_SCROLLBAR
#define gtk_scrollbar_get_type htk_scrollbar_get_type

/* htk/scrolled-window.vala */
typedef HtkScrolledWindow GtkScrolledWindow;
typedef HtkScrolledWindowClass GtkScrolledWindowClass;
#define GTK_SCROLLED_WINDOW HTK_SCROLLED_WINDOW
#define GTK_IS_SCROLLED_WINDOW HTK_IS_SCROLLED_WINDOW
#define gtk_scrolled_window_add_with_viewport htk_scrolled_window_add_with_viewport
#define gtk_scrolled_window_get_hadjustment htk_scrolled_window_get_hadjustment
#define gtk_scrolled_window_get_hscrollbar htk_scrolled_window_get_hscrollbar
#define gtk_scrolled_window_get_type htk_scrolled_window_get_type
#define gtk_scrolled_window_get_vadjustment htk_scrolled_window_get_vadjustment
#define gtk_scrolled_window_get_vscrollbar htk_scrolled_window_get_vscrollbar
#define gtk_scrolled_window_new htk_scrolled_window_new
#define gtk_scrolled_window_set_hadjustment htk_scrolled_window_set_hadjustment
#define gtk_scrolled_window_set_policy htk_scrolled_window_set_policy
#define gtk_scrolled_window_set_vadjustment htk_scrolled_window_set_vadjustment

/* htk/separator.vala */
typedef HtkSeparator GtkSeparator;
typedef HtkSeparatorClass GtkSeparatorClass;
#define GTK_SEPARATOR HTK_SEPARATOR
#define GTK_IS_SEPARATOR HTK_IS_SEPARATOR
//#define gtk_separator_get_type htk_separator_get_type

/* htk/spinner.vala */
typedef HtkSpinner GtkSpinner;
typedef HtkSpinnerClass GtkSpinnerClass;
#define GTK_SPINNER HTK_SPINNER
#define GTK_SPINNER_CLASS HTK_SPINNER_CLASS
#define GTK_SPINNER_GET_CLASS HTK_SPINNER_GET_CLASS
#define GTK_IS_SPINNER HTK_IS_SPINNER
#define GTK_IS_SPINNER_CLASS HTK_IS_SPINNER_CLASS
#define GTK_TYPE_SPINNER HTK_TYPE_SPINNER
#define gtk_spinner_get_type htk_spinner_get_type
#define gtk_spinner_new htk_spinner_new
#define gtk_spinner_start htk_spinner_start
#define gtk_spinner_stop htk_spinner_stop

/* htk/style.vala */
typedef HtkStyle GtkStyle;
typedef HtkStyleClass GtkStyleClass;
#define GTK_STYLE HTK_STYLE
#define GTK_IS_STYLE HTK_IS_STYLE
#define gtk_style_apply_default_background htk_style_apply_default_background
#define gtk_style_get_type htk_style_get_type
#define gtk_style_lookup_icon_set htk_style_lookup_icon_set
#define gtk_style_new htk_style_new

/* htk/text-buffer.vala */
typedef HtkTextBuffer GtkTextBuffer;
typedef HtkTextBufferClass GtkTextBufferClass;
#define GTK_TEXT_BUFFER HTK_TEXT_BUFFER
#define GTK_IS_TEXT_BUFFER HTK_IS_TEXT_BUFFER
#define gtk_text_buffer_backspace htk_text_buffer_backspace
#define gtk_text_buffer_delete htk_text_buffer_delete
#define gtk_text_buffer_get_modified htk_text_buffer_get_modified
#define gtk_text_buffer_get_start_iter htk_text_buffer_get_start_iter
#define gtk_text_buffer_get_text htk_text_buffer_get_text
#define gtk_text_buffer_get_type htk_text_buffer_get_type
#define gtk_text_buffer_insert htk_text_buffer_insert
#define gtk_text_buffer_insert_at_cursor htk_text_buffer_insert_at_cursor
#define gtk_text_buffer_new htk_text_buffer_new
#define gtk_text_buffer_set_modified htk_text_buffer_set_modified
#define gtk_text_buffer_set_text htk_text_buffer_set_text

/* htk/text-iter.vala */
typedef HtkTextIter GtkTextIter;
#define gtk_text_iter_backward_char htk_text_iter_backward_char
#define gtk_text_iter_backward_line htk_text_iter_backward_line
#define gtk_text_iter_equal htk_text_iter_equal
#define gtk_text_iter_forward_char htk_text_iter_forward_char
#define gtk_text_iter_forward_line htk_text_iter_forward_line

/* htk/text-view.vala */
typedef HtkTextView GtkTextView;
typedef HtkTextViewClass GtkTextViewClass;
#define GTK_TEXT_VIEW HTK_TEXT_VIEW
#define GTK_IS_TEXT_VIEW HTK_IS_TEXT_VIEW
#define gtk_text_view_get_buffer htk_text_view_get_buffer
#define gtk_text_view_get_editable htk_text_view_get_editable
#define gtk_text_view_get_type htk_text_view_get_type
#define gtk_text_view_new htk_text_view_new
#define gtk_text_view_set_buffer htk_text_view_set_buffer
#define gtk_text_view_set_editable htk_text_view_set_editable

/* htk/togglebutton.vala */
typedef HtkToggleButton GtkToggleButton;
typedef HtkToggleButtonClass GtkToggleButtonClass;
#define GTK_TOGGLE HTK_TOGGLE
#define GTK_IS_TOGGLE HTK_IS_TOGGLE
#define gtk_toggle_button_get_inconsistent htk_toggle_button_get_inconsistent
#define gtk_toggle_button_get_type htk_toggle_button_get_type
#define gtk_toggle_button_new htk_toggle_button_new
#define gtk_toggle_button_new_with_label htk_toggle_button_new_with_label
#define gtk_toggle_button_set_inconsistent htk_toggle_button_set_inconsistent

/* htk/tree-model.vala */
typedef HtkTreeIter GtkTreeIter;
#define GTK_TYPE_TREE_ITER HTK_TYPE_TREE_ITER
#define gtk_tree_iter_copy htk_tree_iter_copy
#define gtk_tree_iter_free htk_tree_iter_free
#define gtk_tree_iter_get_type htk_tree_iter_get_type

/* htk/tree-model.vala */
typedef HtkTreeModel GtkTreeModel;
#define GTK_TREE_MODEL HTK_TREE_MODEL
#define GTK_IS_TREE_MODEL HTK_IS_TREE_MODEL
#define GTK_TYPE_TREE_MODEL HTK_TYPE_TREE_MODEL
#define gtk_tree_model_get htk_tree_model_get
#define gtk_tree_model_get_column_type htk_tree_model_get_column_type
#define gtk_tree_model_get_iter htk_tree_model_get_iter
#define gtk_tree_model_get_iter_first htk_tree_model_get_iter_first
#define gtk_tree_model_get_n_columns htk_tree_model_get_n_columns
#define gtk_tree_model_get_type htk_tree_model_get_type
#define gtk_tree_model_get_valist htk_tree_model_get_valist
#define gtk_tree_model_get_value htk_tree_model_get_value
#define gtk_tree_model_iter_children htk_tree_model_iter_children
#define gtk_tree_model_iter_has_child htk_tree_model_iter_has_child
#define gtk_tree_model_iter_n_children htk_tree_model_iter_n_children
#define gtk_tree_model_iter_next htk_tree_model_iter_next
#define gtk_tree_model_iter_nth_child htk_tree_model_iter_nth_child
#define gtk_tree_model_iter_parent htk_tree_model_iter_parent
#define gtk_tree_model_ref_node htk_tree_model_ref_node
#define gtk_tree_model_row_changed htk_tree_model_row_changed
#define gtk_tree_model_row_deleted htk_tree_model_row_deleted
#define gtk_tree_model_row_inserted htk_tree_model_row_inserted
#define gtk_tree_model_unref_node htk_tree_model_unref_node

/* htk/tree-model.vala */
typedef HtkTreePath GtkTreePath;
#define GTK_TYPE_TREE_PATH HTK_TYPE_TREE_PATH
#define gtk_tree_path_append_index htk_tree_path_append_index
#define gtk_tree_path_copy htk_tree_path_copy
#define gtk_tree_path_free htk_tree_path_free
#define gtk_tree_path_get_type htk_tree_path_get_type
#define gtk_tree_path_new htk_tree_path_new
#define gtk_tree_path_new_first htk_tree_path_new_first

/* htk/tree-model.vala */
typedef HtkTreeRowReference GtkTreeRowReference;
#define gtk_tree_row_reference_free htk_tree_row_reference_free
#define gtk_tree_row_reference_get_model htk_tree_row_reference_get_model
#define gtk_tree_row_reference_get_path htk_tree_row_reference_get_path
#define gtk_tree_row_reference_new htk_tree_row_reference_new
#define gtk_tree_row_reference_valid htk_tree_row_reference_valid

/* htk/vbox.vala */
typedef HtkVBox GtkVBox;
typedef HtkVBoxClass GtkVBoxClass;
#define GTK_VBOX HTK_VBOX
#define GTK_IS_VBOX HTK_IS_VBOX
#define gtk_vbox_get_type htk_vbox_get_type
#define gtk_vbox_new htk_vbox_new

/* htk/viewport.vala */
typedef HtkViewport GtkViewport;
typedef HtkViewportClass GtkViewportClass;
#define GTK_VIEWPORT HTK_VIEWPORT
#define GTK_IS_VIEWPORT HTK_IS_VIEWPORT
#define gtk_viewport_get_hadjustment htk_viewport_get_hadjustment
#define gtk_viewport_get_vadjustment htk_viewport_get_vadjustment
#define gtk_viewport_get_type htk_viewport_get_type
#define gtk_viewport_new htk_viewport_new
#define gtk_viewport_set_hadjustment htk_viewport_set_hadjustment
#define gtk_viewport_set_vadjustment htk_viewport_set_vadjustment

/* htk/vpaned.vala */
typedef HtkVPaned GtkVPaned;
typedef HtkVPanedClass GtkVPanedClass;
#define GTK_VPANED HTK_VPANED
#define GTK_IS_VPANED HTK_IS_VPANED
#define gtk_vpaned_get_type htk_vpaned_get_type
#define gtk_vpaned_new htk_vpaned_new

/* htk/vscale.vala */
typedef HtkVScale GtkVScale;
typedef HtkVScaleClass GtkVScaleClass;
#define GTK_VSCALE HTK_VSCALE
#define GTK_IS_VSCALE HTK_IS_VSCALE
#define gtk_vscale_get_type htk_vscale_get_type
#define gtk_vscale_new htk_vscale_new

/* htk/vscrollbar.vala */
typedef HtkVScrollbar GtkVScrollbar;
typedef HtkVScrollbarClass GtkVScrollbarClass;
#define GTK_VSCROLLBAR HTK_VSCROLLBAR
#define GTK_IS_VSCROLLBAR HTK_IS_VSCROLLBAR
#define gtk_vscrollbar_get_type htk_vscrollbar_get_type
#define gtk_vscrollbar_new htk_vscrollbar_new

/* htk/vseparator.vala */
typedef HtkVSeparator GtkVSeparator;
typedef HtkVSeparatorClass GtkVSeparatorClass;
#define GTK_VSEPARATOR HTK_VSEPARATOR
#define GTK_IS_VSEPARATOR HTK_IS_VSEPARATOR
#define gtk_vseparator_get_type htk_vseparator_get_type
#define gtk_vseparator_new htk_vseparator_new

/* htk/widget.vala */
typedef HtkWidget GtkWidget;
typedef HtkWidgetClass GtkWidgetClass;
#define GTK_WIDGET HTK_WIDGET
#define GTK_IS_WIDGET HTK_IS_WIDGET
#define gtk_widget_child_focus htk_widget_child_focus
#define gtk_widget_create_pango_context htk_widget_create_pango_context
#define gtk_widget_create_pango_layout htk_widget_create_pango_layout
#define gtk_widget_get_can_focus htk_widget_get_can_focus
#define gtk_widget_get_direction htk_widget_get_direction
#define gtk_widget_get_pango_context htk_widget_get_pango_context
#define gtk_widget_get_parent_window htk_widget_get_parent_window
#define gtk_widget_get_size_request htk_widget_get_size_request
#define gtk_widget_get_toplevel htk_widget_get_toplevel
#define gtk_widget_get_type htk_widget_get_type
#define gtk_widget_grab_focus htk_widget_grab_focus
#define gtk_widget_hide htk_widget_hide
#define gtk_widget_hide_all htk_widget_hide_all
#define gtk_widget_is_ancestor htk_widget_is_ancestor
#define gtk_widget_map htk_widget_map
#define gtk_widget_modify_bg htk_widget_modify_bg
#define gtk_widget_modify_fg htk_widget_modify_fg
#define gtk_widget_modify_text htk_widget_modify_text
#define gtk_widget_queue_draw htk_widget_queue_draw
#define gtk_widget_queue_draw_area htk_widget_queue_draw_area
#define gtk_widget_queue_resize htk_widget_queue_resize
#define gtk_widget_realize htk_widget_realize
#define gtk_widget_render_icon htk_widget_render_icon
#define gtk_widget_set_can_focus htk_widget_set_can_focus
#define gtk_widget_set_parent htk_widget_set_parent
#define gtk_widget_set_scroll_adjustments htk_widget_set_scroll_adjustments
#define gtk_widget_set_size_request htk_widget_set_size_request
#define gtk_widget_show htk_widget_show
#define gtk_widget_show_all htk_widget_show_all
#define gtk_widget_size_allocate htk_widget_size_allocate
#define gtk_widget_size_request htk_widget_size_request
#define gtk_widget_style_get htk_widget_style_get
#define gtk_widget_style_get_valist htk_widget_style_get_valist
#define gtk_widget_unmap htk_widget_unmap
#define gtk_widget_unparent htk_widget_unparent
#define gtk_widget_unrealize htk_widget_unrealize

/* htk/window.vala */
typedef HtkWindow GtkWindow;
typedef HtkWindowClass GtkWindowClass;
#define GTK_WINDOW HTK_WINDOW
#define GTK_IS_WINDOW HTK_IS_WINDOW
#define gtk_window_get_position htk_window_get_position
#define gtk_window_get_type htk_window_get_type
#define gtk_window_move htk_window_move
#define gtk_window_new htk_window_new
#define gtk_window_set_accept_focus htk_window_set_accept_focus
#define gtk_window_set_position htk_window_set_position
#define gtk_window_set_title htk_window_set_title

/* htk/stock.vala */
#define gtk_stock_add htk_stock_add
#define gtk_stock_add_static htk_stock_add_static
#define gtk_stock_list_ids htk_stock_list_ids

/* htk/htk.vala */
#define gtk_key_snooper_install htk_key_snooper_install
#define gtk_key_snooper_remove htk_key_snooper_remove

/* htk/style.vala */
#define gtk_paint_check htk_style_paint_check
#define gtk_paint_flat_box htk_style_paint_flat_box
#define gtk_paint_focus htk_style_paint_focus
#define gtk_paint_layout htk_style_paint_layout
#define gtk_paint_option htk_style_paint_option
#define gtk_paint_slider htk_style_paint_slider
//#define gtk_draw_insertion_cursor htk_style_draw_insertion_cursor
//#define gdk_draw_pixbuf htk_style_draw_pixbuf

G_END_DECLS

#endif//__HTK_GTK_H__
