#
##  Makefile
#
include $(PROJECT_CONFIG)

## 子目录
SUBDIRS	= haierv1 haierv2

## 目标文件
OBJS	+=	dadporting.o dad_data_store.o

## 生成目标
O_TARGET	=	o_target.o

## 编译规则
include $(WORKROOT)/project/$(PROJECT)/make/project_rule.mk

