

#include	"dTypes.h"
#include	"tImageResource_tv.h"
#include	"ImageOutput\tv_IMG_ID_Audio_Progress_Bg_english.c"
#include	"ImageOutput\tv_IMG_ID_Background_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Black_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Bright1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Calendar_date1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Calendar_date2_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Calendar_set1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Calendar_set2_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Channel_list1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Red_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Search_Channel1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Show_Scale1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_Track1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_list_left_english.c"
#include	"ImageOutput\tv_IMG_ID_Bottom_list_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_Bright_Sign1_english.c"
#include	"ImageOutput\tv_IMG_ID_Bright_Sign2_english.c"
#include	"ImageOutput\tv_IMG_ID_Button_Yes1_english.c"
#include	"ImageOutput\tv_IMG_ID_Button_Yes2_english.c"
#include	"ImageOutput\tv_IMG_ID_Calendar_focus_english.c"
#include	"ImageOutput\tv_IMG_ID_Calendar_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_Calendar_input_long_english.c"
#include	"ImageOutput\tv_IMG_ID_Calendar_input_short_english.c"
#include	"ImageOutput\tv_IMG_ID_Calendar_time_english.c"
#include	"ImageOutput\tv_IMG_ID_Channel_List_left1_english.c"
#include	"ImageOutput\tv_IMG_ID_Channel_List_left2_english.c"
#include	"ImageOutput\tv_IMG_ID_Channel_List_middle1_english.c"
#include	"ImageOutput\tv_IMG_ID_Channel_List_middle2_english.c"
#include	"ImageOutput\tv_IMG_ID_Channel_List_right1_english.c"
#include	"ImageOutput\tv_IMG_ID_Channel_List_right2_english.c"
#include	"ImageOutput\tv_IMG_ID_EBook_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_Ebook_manage2_english.c"
#include	"ImageOutput\tv_IMG_ID_Elect_volume_english.c"
#include	"ImageOutput\tv_IMG_ID_Elect_volume1_english.c"
#include	"ImageOutput\tv_IMG_ID_Elect_volume2_english.c"
#include	"ImageOutput\tv_IMG_ID_Elect_volume3_english.c"
#include	"ImageOutput\tv_IMG_ID_Elect_volume4_english.c"
#include	"ImageOutput\tv_IMG_ID_FM_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_FM_Freq_Dian_english.c"
#include	"ImageOutput\tv_IMG_ID_FM_MHz_english.c"
#include	"ImageOutput\tv_IMG_ID_Fm_bottom_left_english.c"
#include	"ImageOutput\tv_IMG_ID_Fm_bottom_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_Fm_bottom_right_english.c"
#include	"ImageOutput\tv_IMG_ID_Full_Screen_White_english.c"
#include	"ImageOutput\tv_IMG_ID_Left1_english.c"
#include	"ImageOutput\tv_IMG_ID_Left2_english.c"
#include	"ImageOutput\tv_IMG_ID_Loop_Play_english.c"
#include	"ImageOutput\tv_IMG_ID_Menu_Buttom_english.c"
#include	"ImageOutput\tv_IMG_ID_Music_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_Music_Off_english.c"
#include	"ImageOutput\tv_IMG_ID_Music_On_english.c"
#include	"ImageOutput\tv_IMG_ID_One_Loop_Play_english.c"
#include	"ImageOutput\tv_IMG_ID_Order_Play_english.c"
#include	"ImageOutput\tv_IMG_ID_Photo_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_Pop_Box_left_english.c"
#include	"ImageOutput\tv_IMG_ID_Pop_Box_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_Pop_Box_right_english.c"
#include	"ImageOutput\tv_IMG_ID_Progress_Bar1_english.c"
#include	"ImageOutput\tv_IMG_ID_Random_Play_english.c"
#include	"ImageOutput\tv_IMG_ID_Right1_english.c"
#include	"ImageOutput\tv_IMG_ID_Right2_english.c"
#include	"ImageOutput\tv_IMG_ID_Screen_16_White_english.c"
#include	"ImageOutput\tv_IMG_ID_Screen_4_White_english.c"
#include	"ImageOutput\tv_IMG_ID_Search_Box_english.c"
#include	"ImageOutput\tv_IMG_ID_Select_english.c"
#include	"ImageOutput\tv_IMG_ID_Select_Backgroud_english.c"
#include	"ImageOutput\tv_IMG_ID_Select_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_Select_Time_english.c"
#include	"ImageOutput\tv_IMG_ID_Signal1_english.c"
#include	"ImageOutput\tv_IMG_ID_Signal2_english.c"
#include	"ImageOutput\tv_IMG_ID_Signal3_english.c"
#include	"ImageOutput\tv_IMG_ID_Signal4_english.c"
#include	"ImageOutput\tv_IMG_ID_Signal5_english.c"
#include	"ImageOutput\tv_IMG_ID_Signal6_english.c"
#include	"ImageOutput\tv_IMG_ID_Slide_Pause_english.c"
#include	"ImageOutput\tv_IMG_ID_Slide_Play_english.c"
#include	"ImageOutput\tv_IMG_ID_Slide_Speed_1_english.c"
#include	"ImageOutput\tv_IMG_ID_Slide_Speed_2_english.c"
#include	"ImageOutput\tv_IMG_ID_Small_Tv_english.c"
#include	"ImageOutput\tv_IMG_ID_Tool_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_Track_left_english.c"
#include	"ImageOutput\tv_IMG_ID_Track_right_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Pop_Info_left_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Pop_Info_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Pop_Info_right_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Video_left_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Video_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_Tv_Video_right_english.c"
#include	"ImageOutput\tv_IMG_ID_Video_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_Volume_White_english.c"
#include	"ImageOutput\tv_IMG_ID_Volume_progress1_english.c"
#include	"ImageOutput\tv_IMG_ID_Volume_progress2_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num0_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num1_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num2_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num3_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num4_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num5_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num6_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num7_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num8_english.c"
#include	"ImageOutput\tv_IMG_ID_Yellow_num9_english.c"
#include	"ImageOutput\tv_IMG_ID_button_pause1_english.c"
#include	"ImageOutput\tv_IMG_ID_button_pause2_english.c"
#include	"ImageOutput\tv_IMG_ID_button_play1_english.c"
#include	"ImageOutput\tv_IMG_ID_calendar_Button_english.c"
#include	"ImageOutput\tv_IMG_ID_calendar_manage2_english.c"
#include	"ImageOutput\tv_IMG_ID_disk_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_file_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num0_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num1_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num2_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num3_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num4_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num5_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num6_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num7_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num8_english.c"
#include	"ImageOutput\tv_IMG_ID_fm_num9_english.c"
#include	"ImageOutput\tv_IMG_ID_impulse1_english.c"
#include	"ImageOutput\tv_IMG_ID_impulse2_english.c"
#include	"ImageOutput\tv_IMG_ID_label_SD1_english.c"
#include	"ImageOutput\tv_IMG_ID_label_SD2_english.c"
#include	"ImageOutput\tv_IMG_ID_label_USB1_english.c"
#include	"ImageOutput\tv_IMG_ID_label_USB2_english.c"
#include	"ImageOutput\tv_IMG_ID_menu_backgroud_english.c"
#include	"ImageOutput\tv_IMG_ID_movie_manage2_english.c"
#include	"ImageOutput\tv_IMG_ID_mp3_icon1_english.c"
#include	"ImageOutput\tv_IMG_ID_mp3_icon2_english.c"
#include	"ImageOutput\tv_IMG_ID_mum0_english.c"
#include	"ImageOutput\tv_IMG_ID_mum1_english.c"
#include	"ImageOutput\tv_IMG_ID_mum2_english.c"
#include	"ImageOutput\tv_IMG_ID_mum3_english.c"
#include	"ImageOutput\tv_IMG_ID_mum4_english.c"
#include	"ImageOutput\tv_IMG_ID_mum5_english.c"
#include	"ImageOutput\tv_IMG_ID_mum6_english.c"
#include	"ImageOutput\tv_IMG_ID_mum7_english.c"
#include	"ImageOutput\tv_IMG_ID_mum8_english.c"
#include	"ImageOutput\tv_IMG_ID_mum9_english.c"
#include	"ImageOutput\tv_IMG_ID_music_bottom_left_english.c"
#include	"ImageOutput\tv_IMG_ID_music_bottom_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_music_bottom_right_english.c"
#include	"ImageOutput\tv_IMG_ID_music_progress_left_english.c"
#include	"ImageOutput\tv_IMG_ID_music_progress_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_music_progress_right_english.c"
#include	"ImageOutput\tv_IMG_ID_no_photo_english.c"
#include	"ImageOutput\tv_IMG_ID_photo_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_progress_red_left_english.c"
#include	"ImageOutput\tv_IMG_ID_progress_red_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_progress_red_right_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_button_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_icon1_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_icon2_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_icon3_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_image_left_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_image_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_image_right_english.c"
#include	"ImageOutput\tv_IMG_ID_pvr_small_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_sd_icon1_english.c"
#include	"ImageOutput\tv_IMG_ID_small_Ebook_english.c"
#include	"ImageOutput\tv_IMG_ID_small_file_manage_english.c"
#include	"ImageOutput\tv_IMG_ID_small_fm_english.c"
#include	"ImageOutput\tv_IMG_ID_small_movie_manage_english.c"
#include	"ImageOutput\tv_IMG_ID_small_music_english.c"
#include	"ImageOutput\tv_IMG_ID_small_photo_english.c"
#include	"ImageOutput\tv_IMG_ID_small_set_english.c"
#include	"ImageOutput\tv_IMG_ID_small_tool_english.c"
#include	"ImageOutput\tv_IMG_ID_small_video_english.c"
#include	"ImageOutput\tv_IMG_ID_sound_volume_english.c"
#include	"ImageOutput\tv_IMG_ID_time_AM_english.c"
#include	"ImageOutput\tv_IMG_ID_time_PM_english.c"
#include	"ImageOutput\tv_IMG_ID_tool_manage2_english.c"
#include	"ImageOutput\tv_IMG_ID_tool_set2_english.c"
#include	"ImageOutput\tv_IMG_ID_tv_progress_red_left_english.c"
#include	"ImageOutput\tv_IMG_ID_tv_progress_red_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_tv_progress_red_right_english.c"
#include	"ImageOutput\tv_IMG_ID_tv_progress_white_left_english.c"
#include	"ImageOutput\tv_IMG_ID_tv_progress_white_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_tv_progress_white_right_english.c"
#include	"ImageOutput\tv_IMG_ID_unknown_file_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_usb_icon1_english.c"
#include	"ImageOutput\tv_IMG_ID_video_icon_english.c"
#include	"ImageOutput\tv_IMG_ID_video_list_left_english.c"
#include	"ImageOutput\tv_IMG_ID_video_list_middle_english.c"
#include	"ImageOutput\tv_IMG_ID_video_num5_english.c"
#include	"ImageOutput\tv_IMG_ID_video_num6_english.c"
#include	"ImageOutput\tv_IMG_ID_video_num7_english.c"
#include	"ImageOutput\tv_IMG_ID_video_num8_english.c"
#include	"ImageOutput\tv_IMG_ID_video_num9_english.c"
#include	"ImageOutput\tv_IMG_ID_video_num_wait_english.c"
#include	"ImageOutput\tv_IMG_ID_video_progress_pos_english.c"




typedef struct
{
	unsigned char *imgName;
	int imgSize;
}IMGITEM;




static PREFIXCONST IMGITEM POSTCONST _img_array__english[]=
{
	{tv_IMG_ID_Video_Button_english, 10828},
	{tv_IMG_ID_calendar_Button_english, 10021},
	{tv_IMG_ID_Elect_volume1_english, 498},
	{tv_IMG_ID_Elect_volume2_english, 505},
	{tv_IMG_ID_Elect_volume3_english, 504},
	{tv_IMG_ID_Elect_volume4_english, 510},
	{tv_IMG_ID_Elect_volume_english, 454},
	{tv_IMG_ID_FM_Button_english, 10384},
	{tv_IMG_ID_mum0_english, 1289},
	{tv_IMG_ID_mum1_english, 458},
	{tv_IMG_ID_mum2_english, 1363},
	{tv_IMG_ID_mum3_english, 1482},
	{tv_IMG_ID_mum4_english, 891},
	{tv_IMG_ID_mum5_english, 1263},
	{tv_IMG_ID_mum6_english, 1329},
	{tv_IMG_ID_mum7_english, 1049},
	{tv_IMG_ID_mum8_english, 1559},
	{tv_IMG_ID_mum9_english, 1491},
	{tv_IMG_ID_Music_Button_english, 10096},
	{tv_IMG_ID_Photo_Button_english, 10235},
	{tv_IMG_ID_Select_Button_english, 1866},
	{tv_IMG_ID_sound_volume_english, 1202},
	{tv_IMG_ID_time_AM_english, 1256},
	{tv_IMG_ID_time_PM_english, 1182},
	{tv_IMG_ID_Tool_Button_english, 10039},
	{tv_IMG_ID_Tv_Button_english, 9526},
	{tv_IMG_ID_Signal6_english, 676},
	{tv_IMG_ID_Signal1_english, 591},
	{tv_IMG_ID_Signal2_english, 551},
	{tv_IMG_ID_Signal3_english, 507},
	{tv_IMG_ID_Signal4_english, 474},
	{tv_IMG_ID_Signal5_english, 441},
	{tv_IMG_ID_Tv_Pop_Info_left_english, 557},
	{tv_IMG_ID_Tv_Pop_Info_middle_english, 269},
	{tv_IMG_ID_Tv_Pop_Info_right_english, 483},
	{tv_IMG_ID_Tv_Video_right_english, 3138},
	{tv_IMG_ID_Bottom_Black_english, 5051},
	{tv_IMG_ID_Bottom_Bright1_english, 2424},
	{tv_IMG_ID_Bottom_Channel_list1_english, 667},
	{tv_IMG_ID_Bottom_list_left_english, 1490},
	{tv_IMG_ID_Bottom_list_middle_english, 239},
	{tv_IMG_ID_Bottom_Red_english, 6131},
	{tv_IMG_ID_Bottom_Search_Channel1_english, 2725},
	{tv_IMG_ID_Bottom_Show_Scale1_english, 995},
	{tv_IMG_ID_Bottom_Track1_english, 2028},
	{tv_IMG_ID_Bright_Sign1_english, 48},
	{tv_IMG_ID_Bright_Sign2_english, 48},
	{tv_IMG_ID_Button_Yes1_english, 994},
	{tv_IMG_ID_Button_Yes2_english, 890},
	{tv_IMG_ID_Left1_english, 2460},
	{tv_IMG_ID_Left2_english, 2467},
	{tv_IMG_ID_Pop_Box_left_english, 580},
	{tv_IMG_ID_Pop_Box_middle_english, 334},
	{tv_IMG_ID_Pop_Box_right_english, 609},
	{tv_IMG_ID_Right1_english, 2342},
	{tv_IMG_ID_Right2_english, 2408},
	{tv_IMG_ID_Select_english, 402},
	{tv_IMG_ID_Small_Tv_english, 2655},
	{tv_IMG_ID_Tv_Video_left_english, 3005},
	{tv_IMG_ID_Tv_Video_middle_english, 375},
	{tv_IMG_ID_video_progress_pos_english, 902},
	{tv_IMG_ID_label_SD1_english, 3223},
	{tv_IMG_ID_label_SD2_english, 2837},
	{tv_IMG_ID_label_USB1_english, 3478},
	{tv_IMG_ID_label_USB2_english, 3391},
	{tv_IMG_ID_small_video_english, 2864},
	{tv_IMG_ID_video_icon_english, 1510},
	{tv_IMG_ID_video_num5_english, 428},
	{tv_IMG_ID_video_num6_english, 557},
	{tv_IMG_ID_video_num7_english, 370},
	{tv_IMG_ID_video_num8_english, 620},
	{tv_IMG_ID_video_num9_english, 575},
	{tv_IMG_ID_video_num_wait_english, 151},
	{tv_IMG_ID_video_list_left_english, 1042},
	{tv_IMG_ID_video_list_middle_english, 227},
	{tv_IMG_ID_music_bottom_middle_english, 318},
	{tv_IMG_ID_music_bottom_right_english, 1781},
	{tv_IMG_ID_small_music_english, 2805},
	{tv_IMG_ID_impulse1_english, 119},
	{tv_IMG_ID_impulse2_english, 116},
	{tv_IMG_ID_mp3_icon1_english, 1388},
	{tv_IMG_ID_mp3_icon2_english, 1598},
	{tv_IMG_ID_music_bottom_left_english, 1683},
	{tv_IMG_ID_music_progress_right_english, 803},
	{tv_IMG_ID_music_progress_left_english, 784},
	{tv_IMG_ID_music_progress_middle_english, 206},
	{tv_IMG_ID_Volume_progress2_english, 18694},
	{tv_IMG_ID_Volume_progress1_english, 16714},
	{tv_IMG_ID_Volume_White_english, 1918},
	{tv_IMG_ID_Full_Screen_White_english, 1894},
	{tv_IMG_ID_Slide_Pause_english, 736},
	{tv_IMG_ID_Audio_Progress_Bg_english, 2942},
	{tv_IMG_ID_One_Loop_Play_english, 2783},
	{tv_IMG_ID_Random_Play_english, 2083},
	{tv_IMG_ID_Loop_Play_english, 2521},
	{tv_IMG_ID_Order_Play_english, 1229},
	{tv_IMG_ID_FM_Freq_Dian_english, 178},
	{tv_IMG_ID_FM_MHz_english, 1622},
	{tv_IMG_ID_tool_manage2_english, 9052},
	{tv_IMG_ID_tool_set2_english, 10902},
	{tv_IMG_ID_movie_manage2_english, 10500},
	{tv_IMG_ID_no_photo_english, 29661},
	{tv_IMG_ID_photo_icon_english, 1044},
	{tv_IMG_ID_small_file_manage_english, 2491},
	{tv_IMG_ID_small_movie_manage_english, 2712},
	{tv_IMG_ID_small_photo_english, 2829},
	{tv_IMG_ID_small_set_english, 2832},
	{tv_IMG_ID_small_tool_english, 2630},
	{tv_IMG_ID_Slide_Play_english, 1450},
	{tv_IMG_ID_Music_On_english, 1496},
	{tv_IMG_ID_Slide_Speed_1_english, 2137},
	{tv_IMG_ID_Slide_Speed_2_english, 2446},
	{tv_IMG_ID_Music_Off_english, 2827},
	{tv_IMG_ID_Select_Backgroud_english, 522},
	{tv_IMG_ID_Select_Time_english, 1310},
	{tv_IMG_ID_small_Ebook_english, 2512},
	{tv_IMG_ID_EBook_icon_english, 1317},
	{tv_IMG_ID_usb_icon1_english, 1792},
	{tv_IMG_ID_sd_icon1_english, 1291},
	{tv_IMG_ID_Screen_16_White_english, 1972},
	{tv_IMG_ID_Track_right_english, 1509},
	{tv_IMG_ID_Track_left_english, 1426},
	{tv_IMG_ID_Screen_4_White_english, 1715},
	{tv_IMG_ID_Progress_Bar1_english, 1541},
	{tv_IMG_ID_Search_Box_english, 5269},
	{tv_IMG_ID_button_pause1_english, 730},
	{tv_IMG_ID_button_pause2_english, 1296},
	{tv_IMG_ID_progress_red_left_english, 319},
	{tv_IMG_ID_progress_red_middle_english, 159},
	{tv_IMG_ID_progress_red_right_english, 366},
	{tv_IMG_ID_Fm_bottom_right_english, 601},
	{tv_IMG_ID_Channel_List_left1_english, 97},
	{tv_IMG_ID_Channel_List_left2_english, 882},
	{tv_IMG_ID_Channel_List_middle1_english, 57},
	{tv_IMG_ID_Channel_List_middle2_english, 839},
	{tv_IMG_ID_Channel_List_right2_english, 882},
	{tv_IMG_ID_Fm_bottom_left_english, 1001},
	{tv_IMG_ID_Fm_bottom_middle_english, 463},
	{tv_IMG_ID_tv_progress_white_right_english, 202},
	{tv_IMG_ID_tv_progress_red_left_english, 138},
	{tv_IMG_ID_tv_progress_red_middle_english, 129},
	{tv_IMG_ID_tv_progress_red_right_english, 146},
	{tv_IMG_ID_tv_progress_white_left_english, 188},
	{tv_IMG_ID_tv_progress_white_middle_english, 144},
	{tv_IMG_ID_Channel_List_right1_english, 97},
	{tv_IMG_ID_calendar_manage2_english, 9013},
	{tv_IMG_ID_Ebook_manage2_english, 8871},
	{tv_IMG_ID_fm_num9_english, 954},
	{tv_IMG_ID_fm_num0_english, 809},
	{tv_IMG_ID_fm_num1_english, 337},
	{tv_IMG_ID_fm_num2_english, 697},
	{tv_IMG_ID_fm_num3_english, 812},
	{tv_IMG_ID_fm_num4_english, 467},
	{tv_IMG_ID_fm_num5_english, 615},
	{tv_IMG_ID_fm_num6_english, 913},
	{tv_IMG_ID_fm_num7_english, 603},
	{tv_IMG_ID_fm_num8_english, 965},
	{tv_IMG_ID_disk_icon_english, 921},
	{tv_IMG_ID_file_icon_english, 535},
	{tv_IMG_ID_unknown_file_icon_english, 1848},
	{tv_IMG_ID_menu_backgroud_english, 42497},
	{tv_IMG_ID_button_play1_english, 1047},
	{tv_IMG_ID_small_fm_english, 2798},
	{tv_IMG_ID_Background_english, 140103},
	{tv_IMG_ID_Menu_Buttom_english, 39711},
	{tv_IMG_ID_pvr_small_icon_english, 2446},
	{tv_IMG_ID_pvr_button_english, 8830},
	{tv_IMG_ID_pvr_icon1_english, 1149},
	{tv_IMG_ID_pvr_icon2_english, 1319},
	{tv_IMG_ID_pvr_icon3_english, 3674},
	{tv_IMG_ID_pvr_image_right_english, 190},
	{tv_IMG_ID_pvr_image_left_english, 187},
	{tv_IMG_ID_pvr_image_middle_english, 128},
	{tv_IMG_ID_Yellow_num0_english, 1068},
	{tv_IMG_ID_Yellow_num1_english, 269},
	{tv_IMG_ID_Yellow_num2_english, 1051},
	{tv_IMG_ID_Yellow_num3_english, 1239},
	{tv_IMG_ID_Yellow_num4_english, 681},
	{tv_IMG_ID_Yellow_num5_english, 1114},
	{tv_IMG_ID_Yellow_num6_english, 1251},
	{tv_IMG_ID_Yellow_num7_english, 741},
	{tv_IMG_ID_Yellow_num8_english, 1460},
	{tv_IMG_ID_Yellow_num9_english, 1222},
	{tv_IMG_ID_Calendar_time_english, 5850},
	{tv_IMG_ID_Bottom_Calendar_date1_english, 1833},
	{tv_IMG_ID_Bottom_Calendar_date2_english, 2265},
	{tv_IMG_ID_Bottom_Calendar_set1_english, 3143},
	{tv_IMG_ID_Bottom_Calendar_set2_english, 3214},
	{tv_IMG_ID_Calendar_focus_english, 549},
	{tv_IMG_ID_Calendar_icon_english, 2476},
	{tv_IMG_ID_Calendar_input_long_english, 829},
	{tv_IMG_ID_Calendar_input_short_english, 785},
};

static PREFIXCONST IMGITEM POSTCONST _img_array__chinese[]=
{
	{tv_IMG_ID_Video_Button_english, 10828},
	{tv_IMG_ID_calendar_Button_english, 10021},
	{tv_IMG_ID_Elect_volume1_english, 498},
	{tv_IMG_ID_Elect_volume2_english, 505},
	{tv_IMG_ID_Elect_volume3_english, 504},
	{tv_IMG_ID_Elect_volume4_english, 510},
	{tv_IMG_ID_Elect_volume_english, 454},
	{tv_IMG_ID_FM_Button_english, 10384},
	{tv_IMG_ID_mum0_english, 1289},
	{tv_IMG_ID_mum1_english, 458},
	{tv_IMG_ID_mum2_english, 1363},
	{tv_IMG_ID_mum3_english, 1482},
	{tv_IMG_ID_mum4_english, 891},
	{tv_IMG_ID_mum5_english, 1263},
	{tv_IMG_ID_mum6_english, 1329},
	{tv_IMG_ID_mum7_english, 1049},
	{tv_IMG_ID_mum8_english, 1559},
	{tv_IMG_ID_mum9_english, 1491},
	{tv_IMG_ID_Music_Button_english, 10096},
	{tv_IMG_ID_Photo_Button_english, 10235},
	{tv_IMG_ID_Select_Button_english, 1866},
	{tv_IMG_ID_sound_volume_english, 1202},
	{tv_IMG_ID_time_AM_english, 1256},
	{tv_IMG_ID_time_PM_english, 1182},
	{tv_IMG_ID_Tool_Button_english, 10039},
	{tv_IMG_ID_Tv_Button_english, 9526},
	{tv_IMG_ID_Signal6_english, 676},
	{tv_IMG_ID_Signal1_english, 591},
	{tv_IMG_ID_Signal2_english, 551},
	{tv_IMG_ID_Signal3_english, 507},
	{tv_IMG_ID_Signal4_english, 474},
	{tv_IMG_ID_Signal5_english, 441},
	{tv_IMG_ID_Tv_Pop_Info_left_english, 557},
	{tv_IMG_ID_Tv_Pop_Info_middle_english, 269},
	{tv_IMG_ID_Tv_Pop_Info_right_english, 483},
	{tv_IMG_ID_Tv_Video_right_english, 3138},
	{tv_IMG_ID_Bottom_Black_english, 5051},
	{tv_IMG_ID_Bottom_Bright1_english, 2424},
	{tv_IMG_ID_Bottom_Channel_list1_english, 667},
	{tv_IMG_ID_Bottom_list_left_english, 1490},
	{tv_IMG_ID_Bottom_list_middle_english, 239},
	{tv_IMG_ID_Bottom_Red_english, 6131},
	{tv_IMG_ID_Bottom_Search_Channel1_english, 2725},
	{tv_IMG_ID_Bottom_Show_Scale1_english, 995},
	{tv_IMG_ID_Bottom_Track1_english, 2028},
	{tv_IMG_ID_Bright_Sign1_english, 48},
	{tv_IMG_ID_Bright_Sign2_english, 48},
	{tv_IMG_ID_Button_Yes1_english, 994},
	{tv_IMG_ID_Button_Yes2_english, 890},
	{tv_IMG_ID_Left1_english, 2460},
	{tv_IMG_ID_Left2_english, 2467},
	{tv_IMG_ID_Pop_Box_left_english, 580},
	{tv_IMG_ID_Pop_Box_middle_english, 334},
	{tv_IMG_ID_Pop_Box_right_english, 609},
	{tv_IMG_ID_Right1_english, 2342},
	{tv_IMG_ID_Right2_english, 2408},
	{tv_IMG_ID_Select_english, 402},
	{tv_IMG_ID_Small_Tv_english, 2655},
	{tv_IMG_ID_Tv_Video_left_english, 3005},
	{tv_IMG_ID_Tv_Video_middle_english, 375},
	{tv_IMG_ID_video_progress_pos_english, 902},
	{tv_IMG_ID_label_SD1_english, 3223},
	{tv_IMG_ID_label_SD2_english, 2837},
	{tv_IMG_ID_label_USB1_english, 3478},
	{tv_IMG_ID_label_USB2_english, 3391},
	{tv_IMG_ID_small_video_english, 2864},
	{tv_IMG_ID_video_icon_english, 1510},
	{tv_IMG_ID_video_num5_english, 428},
	{tv_IMG_ID_video_num6_english, 557},
	{tv_IMG_ID_video_num7_english, 370},
	{tv_IMG_ID_video_num8_english, 620},
	{tv_IMG_ID_video_num9_english, 575},
	{tv_IMG_ID_video_num_wait_english, 151},
	{tv_IMG_ID_video_list_left_english, 1042},
	{tv_IMG_ID_video_list_middle_english, 227},
	{tv_IMG_ID_music_bottom_middle_english, 318},
	{tv_IMG_ID_music_bottom_right_english, 1781},
	{tv_IMG_ID_small_music_english, 2805},
	{tv_IMG_ID_impulse1_english, 119},
	{tv_IMG_ID_impulse2_english, 116},
	{tv_IMG_ID_mp3_icon1_english, 1388},
	{tv_IMG_ID_mp3_icon2_english, 1598},
	{tv_IMG_ID_music_bottom_left_english, 1683},
	{tv_IMG_ID_music_progress_right_english, 803},
	{tv_IMG_ID_music_progress_left_english, 784},
	{tv_IMG_ID_music_progress_middle_english, 206},
	{tv_IMG_ID_Volume_progress2_english, 18694},
	{tv_IMG_ID_Volume_progress1_english, 16714},
	{tv_IMG_ID_Volume_White_english, 1918},
	{tv_IMG_ID_Full_Screen_White_english, 1894},
	{tv_IMG_ID_Slide_Pause_english, 736},
	{tv_IMG_ID_Audio_Progress_Bg_english, 2942},
	{tv_IMG_ID_One_Loop_Play_english, 2783},
	{tv_IMG_ID_Random_Play_english, 2083},
	{tv_IMG_ID_Loop_Play_english, 2521},
	{tv_IMG_ID_Order_Play_english, 1229},
	{tv_IMG_ID_FM_Freq_Dian_english, 178},
	{tv_IMG_ID_FM_MHz_english, 1622},
	{tv_IMG_ID_tool_manage2_english, 9052},
	{tv_IMG_ID_tool_set2_english, 10902},
	{tv_IMG_ID_movie_manage2_english, 10500},
	{tv_IMG_ID_no_photo_english, 29661},
	{tv_IMG_ID_photo_icon_english, 1044},
	{tv_IMG_ID_small_file_manage_english, 2491},
	{tv_IMG_ID_small_movie_manage_english, 2712},
	{tv_IMG_ID_small_photo_english, 2829},
	{tv_IMG_ID_small_set_english, 2832},
	{tv_IMG_ID_small_tool_english, 2630},
	{tv_IMG_ID_Slide_Play_english, 1450},
	{tv_IMG_ID_Music_On_english, 1496},
	{tv_IMG_ID_Slide_Speed_1_english, 2137},
	{tv_IMG_ID_Slide_Speed_2_english, 2446},
	{tv_IMG_ID_Music_Off_english, 2827},
	{tv_IMG_ID_Select_Backgroud_english, 522},
	{tv_IMG_ID_Select_Time_english, 1310},
	{tv_IMG_ID_small_Ebook_english, 2512},
	{tv_IMG_ID_EBook_icon_english, 1317},
	{tv_IMG_ID_usb_icon1_english, 1792},
	{tv_IMG_ID_sd_icon1_english, 1291},
	{tv_IMG_ID_Screen_16_White_english, 1972},
	{tv_IMG_ID_Track_right_english, 1509},
	{tv_IMG_ID_Track_left_english, 1426},
	{tv_IMG_ID_Screen_4_White_english, 1715},
	{tv_IMG_ID_Progress_Bar1_english, 1541},
	{tv_IMG_ID_Search_Box_english, 5269},
	{tv_IMG_ID_button_pause1_english, 730},
	{tv_IMG_ID_button_pause2_english, 1296},
	{tv_IMG_ID_progress_red_left_english, 319},
	{tv_IMG_ID_progress_red_middle_english, 159},
	{tv_IMG_ID_progress_red_right_english, 366},
	{tv_IMG_ID_Fm_bottom_right_english, 601},
	{tv_IMG_ID_Channel_List_left1_english, 97},
	{tv_IMG_ID_Channel_List_left2_english, 882},
	{tv_IMG_ID_Channel_List_middle1_english, 57},
	{tv_IMG_ID_Channel_List_middle2_english, 839},
	{tv_IMG_ID_Channel_List_right2_english, 882},
	{tv_IMG_ID_Fm_bottom_left_english, 1001},
	{tv_IMG_ID_Fm_bottom_middle_english, 463},
	{tv_IMG_ID_tv_progress_white_right_english, 202},
	{tv_IMG_ID_tv_progress_red_left_english, 138},
	{tv_IMG_ID_tv_progress_red_middle_english, 129},
	{tv_IMG_ID_tv_progress_red_right_english, 146},
	{tv_IMG_ID_tv_progress_white_left_english, 188},
	{tv_IMG_ID_tv_progress_white_middle_english, 144},
	{tv_IMG_ID_Channel_List_right1_english, 97},
	{tv_IMG_ID_calendar_manage2_english, 9013},
	{tv_IMG_ID_Ebook_manage2_english, 8871},
	{tv_IMG_ID_fm_num9_english, 954},
	{tv_IMG_ID_fm_num0_english, 809},
	{tv_IMG_ID_fm_num1_english, 337},
	{tv_IMG_ID_fm_num2_english, 697},
	{tv_IMG_ID_fm_num3_english, 812},
	{tv_IMG_ID_fm_num4_english, 467},
	{tv_IMG_ID_fm_num5_english, 615},
	{tv_IMG_ID_fm_num6_english, 913},
	{tv_IMG_ID_fm_num7_english, 603},
	{tv_IMG_ID_fm_num8_english, 965},
	{tv_IMG_ID_disk_icon_english, 921},
	{tv_IMG_ID_file_icon_english, 535},
	{tv_IMG_ID_unknown_file_icon_english, 1848},
	{tv_IMG_ID_menu_backgroud_english, 42497},
	{tv_IMG_ID_button_play1_english, 1047},
	{tv_IMG_ID_small_fm_english, 2798},
	{tv_IMG_ID_Background_english, 140103},
	{tv_IMG_ID_Menu_Buttom_english, 39711},
	{tv_IMG_ID_pvr_small_icon_english, 2446},
	{tv_IMG_ID_pvr_button_english, 8830},
	{tv_IMG_ID_pvr_icon1_english, 1149},
	{tv_IMG_ID_pvr_icon2_english, 1319},
	{tv_IMG_ID_pvr_icon3_english, 3674},
	{tv_IMG_ID_pvr_image_right_english, 190},
	{tv_IMG_ID_pvr_image_left_english, 187},
	{tv_IMG_ID_pvr_image_middle_english, 128},
	{tv_IMG_ID_Yellow_num0_english, 1068},
	{tv_IMG_ID_Yellow_num1_english, 269},
	{tv_IMG_ID_Yellow_num2_english, 1051},
	{tv_IMG_ID_Yellow_num3_english, 1239},
	{tv_IMG_ID_Yellow_num4_english, 681},
	{tv_IMG_ID_Yellow_num5_english, 1114},
	{tv_IMG_ID_Yellow_num6_english, 1251},
	{tv_IMG_ID_Yellow_num7_english, 741},
	{tv_IMG_ID_Yellow_num8_english, 1460},
	{tv_IMG_ID_Yellow_num9_english, 1222},
	{tv_IMG_ID_Calendar_time_english, 5850},
	{tv_IMG_ID_Bottom_Calendar_date1_english, 1833},
	{tv_IMG_ID_Bottom_Calendar_date2_english, 2265},
	{tv_IMG_ID_Bottom_Calendar_set1_english, 3143},
	{tv_IMG_ID_Bottom_Calendar_set2_english, 3214},
	{tv_IMG_ID_Calendar_focus_english, 549},
	{tv_IMG_ID_Calendar_icon_english, 2476},
	{tv_IMG_ID_Calendar_input_long_english, 829},
	{tv_IMG_ID_Calendar_input_short_english, 785},
};

static PREFIXCONST IMGITEM POSTCONST * _img_array_entries[]=
{
	_img_array__english,
	_img_array__chinese,
};
PREFIXCONST unsigned char *POSTCONST tv_LoadImageData(int ids, int lanid, int *size)
{
	if(ids>=tv_IMG_ID_ENUM_MAX||ids<tv_IMG_ID_START )
	{
		return NULL;
	}
	ids-=tv_IMG_ID_START;
	if(size)
	{
		*size=_img_array_entries[lanid][ids].imgSize;
	}
	return _img_array_entries[lanid][ids].imgName;
}
