/*
* This file is a part of the Maxwell's Firmware Library.
* (C)2017 Maxwell, All Rights Reserved.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
* FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*
* History:  2017-Feb-05 V0.1.0
*
*
*/

#ifndef _MCU_HAL_COMMON_H_
#define _MCU_HAL_COMMON_H_

/* FW library version. */
#define MCU_HAL_VERSION     (0x7E1)

#ifndef MCU_HAL_API
    #define MCU_HAL_API  
#endif

#ifndef MCU_HAL_EXTERN
    #define MCU_HAL_EXTERN  extern
#endif

/* Select user-specific compiler. */
#if defined (__CSMC__)
    #define _COSMIC_COMPILER_  
#elif defined(__ICCSTM8__)
    #define _IAR_STM8_COMPILER_
#elif defined(__C51__)
    #define _KEIL_COMPILER_
#elif defined(__GNUC__)
    #define _GNU_COMPILER_
#endif 

#include "mcu_hal_includes.h" 

#endif
