#
##  project根Makefile
#
include $(PROJECT_CONFIG)

## 子目录
SUBDIRS	=	tools stb

## 目标文件
OBJS	+=
OBJS	+=

## 生成可执行文件
EXECUTE_TARGET	=	app

## 编译规则
include $(WORKROOT)/project/$(PROJECT)/make/libs.mk
include $(WORKROOT)/project/$(PROJECT)/make/project_rule.mk
