//This file is generated by make version
//Please do not manully edit it
#ifndef __D_HTK_VERSION_H__
#define __D_HTK_VERSION_H__

#define HIHTK_KERNEL_VERSION  750
#define HIHTK_LIB_VERSION  178
#endif
