/*DO NOT modify this file*/
#ifndef	__HEADER_FOR_FORMAT__AND__ITS_PREDEFINED_ENUM_CONSTANT__
#define	__HEADER_FOR_FORMAT__AND__ITS_PREDEFINED_ENUM_CONSTANT__


#include	"dFrame.h"
// global FORMATs used by entire project
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h05_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h10_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h15_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h20_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h10_v10_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h15_v15_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_multi_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_multi_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_multi_grey;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_single_white_scroll_R2L;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h05_v00_single_white_scroll_R2L;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_single_grey;
extern PREFIXCONST D_Format POSTCONST atv_fmt_middle_h00_v00_single_orange;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h05_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h10_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h15_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h20_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h10_v10_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h15_v15_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_right_middle_h00_v00_single_white;
extern PREFIXCONST D_Format POSTCONST atv_fmt_right_middle_h00_v00_single_black;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_signal_whilte_scroll_R2L;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_signal_black_scroll_R2L;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_signal_black_scroll_R2L;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_single_grey;
extern PREFIXCONST D_Format POSTCONST atv_fmt_left_middle_h00_v00_single_red;
extern PREFIXCONST D_Format POSTCONST atv_fmt_center_middle_h00_v00_single_whilte_scroll_R2L;


#endif//__HEADER_FOR_FORMAT__AND__ITS_PREDEFINED_ENUM_CONSTANT__
