#ifndef	__atv_IMG_RESOURCE_HEADER_FILE_PRODUCED_AUTOMATICALLY_BY_GUI_TOOL
#define	__atv_IMG_RESOURCE_HEADER_FILE_PRODUCED_AUTOMATICALLY_BY_GUI_TOOL
#include	"dGuitooldraw.h"
#ifdef	__cplusplus
extern "C" {
#endif//__cplusplus
#define	atv_IMG_ID_START	0x4000
enum{
	//////////////////////////////////////////////////////////////////////////
	// single image resource
	atv_IMG_ID_scrool_two=atv_IMG_ID_START,
	atv_IMG_ID_background,	//=0x0001,
	atv_IMG_ID_function_icon_big,	//=0x0002,
	atv_IMG_ID_time_icon_big,	//=0x0003,
	atv_IMG_ID_image_icon_big,	//=0x0004,
	atv_IMG_ID_voice_icon_big,	//=0x0005,
	atv_IMG_ID_title_usb,	//=0x0006,
	atv_IMG_ID_adjust_icon_big,	//=0x0007,
	atv_IMG_ID_tuning_icon_big,	//=0x0008,
	atv_IMG_ID_title_setting_en,	//=0x0009,
	atv_IMG_ID_icon_setting,	//=0x000a,
	atv_IMG_ID_component01,	//=0x000b,
	atv_IMG_ID_tv_signal01,	//=0x000c,
	atv_IMG_ID_pvr_title_ch,	//=0x000d,
	atv_IMG_ID_usb01,	//=0x000e,
	atv_IMG_ID_title_movie_en,	//=0x000f,
	atv_IMG_ID_icon_movie,	//=0x0010,
	atv_IMG_ID_title_picture_en,	//=0x0011,
	atv_IMG_ID_title_music_en,	//=0x0012,
	atv_IMG_ID_computer01,	//=0x0013,
	atv_IMG_ID_disk_normal,	//=0x0014,
	atv_IMG_ID_HDMI01,	//=0x0015,
	atv_IMG_ID_tv_signal02,	//=0x0016,
	atv_IMG_ID_title_movie,	//=0x0017,
	atv_IMG_ID_icon_file_up_level,	//=0x0018,
	atv_IMG_ID_title_setting,	//=0x0019,
	atv_IMG_ID_usb02,	//=0x001a,
	atv_IMG_ID_component02,	//=0x001b,
	atv_IMG_ID_ebook_title_cn,	//=0x001c,
	atv_IMG_ID_HDMI02,	//=0x001d,
	atv_IMG_ID_ebook_title_en,	//=0x001e,
	atv_IMG_ID_title_usb_en,	//=0x001f,
	atv_IMG_ID_menu_backgroud_blue,	//=0x0020,
	atv_IMG_ID_icon_picture,	//=0x0021,
	atv_IMG_ID_Mute_Icon,	//=0x0022,
	atv_IMG_ID_title_music,	//=0x0023,
	atv_IMG_ID_computer02,	//=0x0024,
	atv_IMG_ID_video02,	//=0x0025,
	atv_IMG_ID_title_picture,	//=0x0026,
	atv_IMG_ID_hint_direction,	//=0x0027,
	atv_IMG_ID_icon_music,	//=0x0028,
	atv_IMG_ID_focus_background,	//=0x0029,
	atv_IMG_ID_signal_background02,	//=0x002a,
	atv_IMG_ID_signal_background01,	//=0x002b,
	atv_IMG_ID_title_backgroud,	//=0x002c,
	atv_IMG_ID_warnning_icon,	//=0x002d,
	atv_IMG_ID_num_8,	//=0x002e,
	atv_IMG_ID_num_6,	//=0x002f,
	atv_IMG_ID_num_9,	//=0x0030,
	atv_IMG_ID_pvr_title_en,	//=0x0031,
	atv_IMG_ID_num_3,	//=0x0032,
	atv_IMG_ID_icon_file,	//=0x0033,
	atv_IMG_ID_icon_setting_focus,	//=0x0034,
	atv_IMG_ID_movie_background,	//=0x0035,
	atv_IMG_ID_num_0,	//=0x0036,
	atv_IMG_ID_pvr_focus,	//=0x0037,
	atv_IMG_ID_num_5,	//=0x0038,
	atv_IMG_ID_num_2,	//=0x0039,
	atv_IMG_ID_Clock,	//=0x003a,
	atv_IMG_ID_video01,	//=0x003b,
	atv_IMG_ID_function_icon_small,	//=0x003c,
	atv_IMG_ID_ebook_icon_focus,	//=0x003d,
	atv_IMG_ID_icon_movie_focus,	//=0x003e,
	atv_IMG_ID_time_icon_small,	//=0x003f,
	atv_IMG_ID_disk_focus,	//=0x0040,
	atv_IMG_ID_image_icon_small,	//=0x0041,
	atv_IMG_ID_voice_icon_small,	//=0x0042,
	atv_IMG_ID_icon_picture_focus,	//=0x0043,
	atv_IMG_ID_time_icon_small_forbidden,	//=0x0044,
	atv_IMG_ID_icon_file_up_level_focus,	//=0x0045,
	atv_IMG_ID_picture_menu_rotate_left,	//=0x0046,
	atv_IMG_ID_voice_icon,	//=0x0047,
	atv_IMG_ID_picture_menu_big,	//=0x0048,
	atv_IMG_ID_picture_menu_rotate_right,	//=0x0049,
	atv_IMG_ID_tune_adjust_background1,	//=0x004a,
	atv_IMG_ID_picture_menu_small,	//=0x004b,
	atv_IMG_ID_num_7,	//=0x004c,
	atv_IMG_ID_num_4,	//=0x004d,
	atv_IMG_ID_usb_small,	//=0x004e,
	atv_IMG_ID_tuning_icon_small,	//=0x004f,
	atv_IMG_ID_icon_music_focus,	//=0x0050,
	atv_IMG_ID_adjust_icon_small,	//=0x0051,
	atv_IMG_ID_Green,	//=0x0052,
	atv_IMG_ID_Yellow,	//=0x0053,
	atv_IMG_ID_hint_background,	//=0x0054,
	atv_IMG_ID_Blue,	//=0x0055,
	atv_IMG_ID_Red,	//=0x0056,
	atv_IMG_ID_position_bg,	//=0x0057,
	atv_IMG_ID_icon_file_focus,	//=0x0058,
	atv_IMG_ID_adjust_icon_small_forbidden,	//=0x0059,
	atv_IMG_ID_music_pitch_on,	//=0x005a,
	atv_IMG_ID_picture_menu_next,	//=0x005b,
	atv_IMG_ID_picture_menu_last,	//=0x005c,
	atv_IMG_ID_media_disk,	//=0x005d,
	atv_IMG_ID_tuning_icon_small_forbidden,	//=0x005e,
	atv_IMG_ID_search_bg,	//=0x005f,
	atv_IMG_ID_ebk_icon_focus_small,	//=0x0060,
	atv_IMG_ID_icon_music_play,	//=0x0061,
	atv_IMG_ID_media_play,	//=0x0062,
	atv_IMG_ID_txt_icon_focus_small,	//=0x0063,
	atv_IMG_ID_picture_menu_bg,	//=0x0064,
	atv_IMG_ID_music_select_focus,	//=0x0065,
	atv_IMG_ID_music_select_up_level,	//=0x0066,
	atv_IMG_ID_music_select,	//=0x0067,
	atv_IMG_ID_voice_bg,	//=0x0068,
	atv_IMG_ID_left_arrow_focus,	//=0x0069,
	atv_IMG_ID_picture_menu_button,	//=0x006a,
	atv_IMG_ID_pvr_normal,	//=0x006b,
	atv_IMG_ID_right_arrow_focus,	//=0x006c,
	atv_IMG_ID_ebook_icon_normal,	//=0x006d,
	atv_IMG_ID_button_left_focus,	//=0x006e,
	atv_IMG_ID_music_select_file,	//=0x006f,
	atv_IMG_ID_position_right_focus,	//=0x0070,
	atv_IMG_ID_tune_adjust_background2,	//=0x0071,
	atv_IMG_ID_position_left,	//=0x0072,
	atv_IMG_ID_position_right,	//=0x0073,
	atv_IMG_ID_button_right_focus,	//=0x0074,
	atv_IMG_ID_position_left_focus,	//=0x0075,
	atv_IMG_ID_program_info_direction_left,	//=0x0076,
	atv_IMG_ID_program_info_direction_right,	//=0x0077,
	atv_IMG_ID_left_arrow_no_focus,	//=0x0078,
	atv_IMG_ID_program_info_direction_up,	//=0x0079,
	atv_IMG_ID_right_arrow_no_focus,	//=0x007a,
	atv_IMG_ID_tunning_pop_backplane,	//=0x007b,
	atv_IMG_ID_music_pitch_on_focus,	//=0x007c,
	atv_IMG_ID_program_info_direction_down,	//=0x007d,
	atv_IMG_ID_num_1,	//=0x007e,
	atv_IMG_ID_pvr_bottom,	//=0x007f,
	atv_IMG_ID_position_down,	//=0x0080,
	atv_IMG_ID_position_down_focus,	//=0x0081,
	atv_IMG_ID_button_left,	//=0x0082,
	atv_IMG_ID_tune_adjust_bar2,	//=0x0083,
	atv_IMG_ID_music_select_pane,	//=0x0084,
	atv_IMG_ID_ebk_icon_normal_small,	//=0x0085,
	atv_IMG_ID_txt_icon_normal_small,	//=0x0086,
	atv_IMG_ID_button_right,	//=0x0087,
	atv_IMG_ID_position_up_focus,	//=0x0088,
	atv_IMG_ID_media_pause,	//=0x0089,
	atv_IMG_ID_position_up,	//=0x008a,
	atv_IMG_ID_pvr_read_pos,	//=0x008b,
	atv_IMG_ID_tune_adjust_bar1,	//=0x008c,
	atv_IMG_ID_tune_adjust_bar,	//=0x008d,
	atv_IMG_ID_music_select_up_level_focus,	//=0x008e,
	atv_IMG_ID_media_stop,	//=0x008f,
	atv_IMG_ID_pop_bg,	//=0x0090,
	atv_IMG_ID_voice_banner,	//=0x0091,
	atv_IMG_ID_icon_background,	//=0x0092,
	atv_IMG_ID_movie_background_rd,	//=0x0093,
	atv_IMG_ID_music_select_right,	//=0x0094,
	atv_IMG_ID_music_select_focus_right,	//=0x0095,
	atv_IMG_ID_media_background,	//=0x0096,
	atv_IMG_ID_red_info_icon,	//=0x0097,
	atv_IMG_ID_music_select_focus_left,	//=0x0098,
	atv_IMG_ID_movie_background_ld,	//=0x0099,
	atv_IMG_ID_music_select_left,	//=0x009a,
	atv_IMG_ID_scroll_right_focus,	//=0x009b,
	atv_IMG_ID_music_select_file_focus,	//=0x009c,
	atv_IMG_ID_scroll_left_focus,	//=0x009d,
	atv_IMG_ID_tune_6db,	//=0x009e,
	atv_IMG_ID_tune10K,	//=0x009f,
	atv_IMG_ID_tune300,	//=0x00a0,
	atv_IMG_ID_tune15K,	//=0x00a1,
	atv_IMG_ID_tune3K,	//=0x00a2,
	atv_IMG_ID_tune50,	//=0x00a3,
	atv_IMG_ID_movie_background_ru,	//=0x00a4,
	atv_IMG_ID_music_select_pane_focus,	//=0x00a5,
	atv_IMG_ID_tune5K,	//=0x00a6,
	atv_IMG_ID_hint_button,	//=0x00a7,
	atv_IMG_ID_scroll_left_no_focus,	//=0x00a8,
	atv_IMG_ID_scroll_right_no_focus,	//=0x00a9,
	atv_IMG_ID_tune75,	//=0x00aa,
	atv_IMG_ID_tune100,	//=0x00ab,
	atv_IMG_ID_movie_background_lu,	//=0x00ac,
	atv_IMG_ID_tune1K,	//=0x00ad,
	atv_IMG_ID_tune0,	//=0x00ae,
	atv_IMG_ID_box_focus,	//=0x00af,
	atv_IMG_ID_menu_button_left_focus,	//=0x00b0,
	atv_IMG_ID_Scroll_Vernier,	//=0x00b1,
	atv_IMG_ID_voice_left,	//=0x00b2,
	atv_IMG_ID_menu_button_right_focus,	//=0x00b3,
	atv_IMG_ID_movie_background_md,	//=0x00b4,
	atv_IMG_ID_program_info_backplane_wide_R,	//=0x00b5,
	atv_IMG_ID_program_info_backplane_wide_L,	//=0x00b6,
	atv_IMG_ID_search_rightx,	//=0x00b7,
	atv_IMG_ID_Scroll_Bg,	//=0x00b8,
	atv_IMG_ID_search_leftx,	//=0x00b9,
	atv_IMG_ID_voice_right,	//=0x00ba,
	atv_IMG_ID_program_info_backplane_narrow_L,	//=0x00bb,
	atv_IMG_ID_program_info_backplane_narrow_R,	//=0x00bc,
	atv_IMG_ID_search_left,	//=0x00bd,
	atv_IMG_ID_menu_button_left,	//=0x00be,
	atv_IMG_ID_signal_progress_background,	//=0x00bf,
	atv_IMG_ID_signal_progress,	//=0x00c0,
	atv_IMG_ID_movie_background_rm,	//=0x00c1,
	atv_IMG_ID_movie_background_lm,	//=0x00c2,
	atv_IMG_ID_search_right,	//=0x00c3,
	atv_IMG_ID_button_background_left,	//=0x00c4,
	atv_IMG_ID_menu_button_right,	//=0x00c5,
	atv_IMG_ID_button_background_right,	//=0x00c6,
	atv_IMG_ID_scroll_normal_focus,	//=0x00c7,
	atv_IMG_ID_menu_button_normal_focus,	//=0x00c8,
	atv_IMG_ID_pos,	//=0x00c9,
	atv_IMG_ID_movie_background_mu,	//=0x00ca,
	atv_IMG_ID_white_background_ld,	//=0x00cb,
	atv_IMG_ID_white_background_ru,	//=0x00cc,
	atv_IMG_ID_white_background_rd,	//=0x00cd,
	atv_IMG_ID_white_background_lu,	//=0x00ce,
	atv_IMG_ID_white_background_md,	//=0x00cf,
	atv_IMG_ID_white_background_rm,	//=0x00d0,
	atv_IMG_ID_white_background_mu,	//=0x00d1,
	atv_IMG_ID_white_background_lm,	//=0x00d2,
	atv_IMG_ID_movie_background_middle,	//=0x00d3,
	atv_IMG_ID_program_info_backplane_wide_M,	//=0x00d4,
	atv_IMG_ID_button_background_middle,	//=0x00d5,
	atv_IMG_ID_white_background_middle,	//=0x00d6,
	atv_IMG_ID_voice_middle,	//=0x00d7,
	atv_IMG_ID_program_info_backplane_narrow_M,	//=0x00d8,
	atv_IMG_ID_music_select_middle,	//=0x00d9,
	atv_IMG_ID_music_select_focus_middle,	//=0x00da,
	atv_IMG_ID_scroll_normal_no_focus,	//=0x00db,
	atv_IMG_ID_menu_button_normal,	//=0x00dc,
	atv_IMG_ID_progress_front,	//=0x00dd,
	atv_IMG_ID_scrool_one,	//=0x00de,
	atv_IMG_ID_no_signal_backgroud,	//=0x00df,
	atv_IMG_ID_menu_button_right_disable,	//=0x00e0,
	atv_IMG_ID_menu_button_left_disable,	//=0x00e1,
	atv_IMG_ID_menu_button_normal_disable,	//=0x00e2,
	atv_IMG_ID_music_list_play,	//=0x00e3,
	atv_IMG_ID_music_one_loop,	//=0x00e4,
	atv_IMG_ID_music_list_loop,	//=0x00e5,
	atv_IMG_ID_music_random,	//=0x00e6,
	atv_IMG_ID_ENUM_MAX,	//=0x40e7,

	//////////////////////////////////////////////////////////////////////////
	// combine image resource
	atv_IMG_ID_COMB_button_backgroud,	//=0x0000,
	atv_IMG_ID_COMB_scroll_no_focus,	//=0x0001,
	atv_IMG_ID_COMB_scroll_focus,	//=0x0002,
	atv_IMG_ID_COMB_button_menu,	//=0x0003,
	atv_IMG_ID_COMB_button_menu_focus,	//=0x0004,
	atv_IMG_ID_COMB_voice_bar,	//=0x0005,
	atv_IMG_ID_COMB_music_select,	//=0x0006,
	atv_IMG_ID_COMB_music_select_focus,	//=0x0007,
	atv_IMB_ID_COMB_white_background,	//=0x0008,
	atv_IMB_ID_COMB_small_window,	//=0x0009,
	atv_IMG_ID_COMB_program_info_backplane_narrow,	//=0x000a,
	atv_IMG_ID_COMB_program_info_backplane_wide,	//=0x000b,
	atv_IMG_ID_COMB_menu_button_normal_disable,	//=0x000c,
	atv_IMG_ID_COMB_scroll_enable,	//=0x000d,
	atv_COMB_ID_ENUM_MAX,

	//////////////////////////////////////////////////////////////////////////
	// userdefine image resource
	atv_IMG_ID_FS_Signal_HDMI_Focus,	//=0x0000,
	atv_IMG_ID_FS_Signal_HDMI_Normal,	//=0x0001,
	atv_IMG_ID_FS_Signal_Tv_Focus,	//=0x0002,
	atv_IMG_ID_FS_Signal_Tv_Normal,	//=0x0003,
	atv_IMG_ID_FS_Signal_Av1_Focus,	//=0x0004,
	atv_IMG_ID_FS_Signal_Av1_Normal,	//=0x0005,
	atv_IMG_ID_FS_Signal_Component_Focus,	//=0x0006,
	atv_IMG_ID_FS_Signal_Component_Normal,	//=0x0007,
	atv_IMG_ID_FS_Signal_Computer_Focus,	//=0x0008,
	atv_IMG_ID_FS_Signal_Computer_Normal,	//=0x0009,
	atv_IMG_ID_FS_Signal_Usb_Focus,	//=0x000a,
	atv_IMG_ID_FS_Signal_Usb_Normal,	//=0x000b,
	atv_IMG_ID_FS_Move,	//=0x000c,
	atv_IMG_ID_FS_audio_tune_bg,	//=0x000d,
	atv_IMG_ID_FS_Media_movie,	//=0x000e,
	atv_IMG_ID_FS_Media_Music,	//=0x000f,
	atv_IMG_ID_FS_Media_Picture,	//=0x0010,
	atv_IMG_ID_FS_Media_Setting,	//=0x0011,
	atv_IMG_ID_FS_Media_Movie_Focus,	//=0x0012,
	atv_IMG_ID_FS_Media_Music_Focus,	//=0x0013,
	atv_IMG_ID_FS_Media_Picture_Focus,	//=0x0014,
	atv_IMG_ID_FS_Media_Setting_Focus,	//=0x0015,
	atv_IMG_ID_FS_Media_Folder_Normal,	//=0x0016,
	atv_IMG_ID_FS_Media_Folder_Focus,	//=0x0017,
	atv_IMG_ID_FS_Media_Floder1_Normal,	//=0x0018,
	atv_IMG_ID_FS_Media_Folder1_Focus,	//=0x0019,
	atv_IMG_ID_FS_Media_disk_normal,	//=0x001a,
	atv_IMG_ID_FS_Media_disk_focus,	//=0x001b,
	atv_IMG_ID_FS_Media_PictureMenu_Play_Focus,	//=0x001c,
	atv_IMG_ID_FS_Media_PictureMenu_Pause_Focus,	//=0x001d,
	atv_IMG_ID_FS_Media_PictureMenu_Last_Focus,	//=0x001e,
	atv_IMG_ID_FS_Media_PictureMenu_Next_Focus,	//=0x001f,
	atv_IMG_ID_FS_Media_PictureMenu_LeftRotate_Focus,	//=0x0020,
	atv_IMG_ID_FS_Media_PictureMenu_RightRotate_Focus,	//=0x0021,
	atv_IMG_ID_FS_Media_PictureMenu_Play,	//=0x0022,
	atv_IMG_ID_FS_Media_PictureMenu_Pause,	//=0x0023,
	atv_IMG_ID_FS_Media_PictureMenu_Last,	//=0x0024,
	atv_IMG_ID_FS_Media_PictureMenu_Next,	//=0x0025,
	atv_IMG_ID_FS_Media_PictureMenu_LeftRotate,	//=0x0026,
	atv_IMG_ID_FS_Media_PictureMenu_RightRotate,	//=0x0027,
	atv_IMG_ID_FS_Media_ebook_focus,	//=0x0028,
	atv_IMG_ID_FS_Media_ebook_normal,	//=0x0029,
	atv_IMG_ID_FS_Media_PVR_FOCUS,	//=0x002a,
	atv_IMG_ID_FS_Media_Normal,	//=0x002b,
	atv_IMG_ID_FS_Media_Stop_Focus,	//=0x002c,
	atv_IMG_ID_FS_Media_Last_Focus,	//=0x002d,
	atv_IMG_ID_FS_Media_Next_focus,	//=0x002e,
	atv_IMG_ID_FS_Media_Pause_Focus,	//=0x002f,
	atv_IMG_ID_FS_Window_black_bg,	//=0x0030,
	atv_IMG_ID_FS_ENUM_MAX,

};

//////////////////////////////////////////////////////////////////////////
// single image resource


PREFIXCONST unsigned char *POSTCONST atv_LoadImageData(int ids, int lanid, int *size);

//////////////////////////////////////////////////////////////////////////
// combine image resource
#define	atv_IMG_ID_COMB_START	atv_IMG_ID_COMB_button_backgroud
typedef enum{
	atv_IID_HOR=0,
	atv_IID_VER=1,
	atv_IID_MAT=2,
	atv_IID_USER=3,
}atv_COMBINE_IMG_TYPE;

const short* atv_LoadCombineImageData(int ids);

//////////////////////////////////////////////////////////////////////////
// userdefine image resource
#define	atv_IMG_ID_FS_START	atv_IMG_ID_FS_Signal_HDMI_Focus

fGuiTool atv_LoadFreeShape(int id, int lanid);

#ifdef	__cplusplus
}
#endif//__cplusplus
#endif//	__atv_IMG_RESOURCE_HEADER_FILE_PRODUCED_AUTOMATICALLY_BY_GUI_TOOL
